// Definición Centralizada de Códigos de Error y Análisis
// Este archivo actúa como contrato entre el Motor (Python/TS) y la UI (React)

export const ErrorCodes = {
    // --- STATIC ANALYSIS (LINTER) ---
    STYLE_SNAKE_CASE_VAR: 'STYLE_SNAKE_CASE_VAR', // Params: { name }
    STYLE_SNAKE_CASE_FUNC: 'STYLE_SNAKE_CASE_FUNC', // Params: { name }
    STYLE_PRIVATE_VAR: 'STYLE_PRIVATE_VAR', // Params: { name }
    STYLE_IMPORTS_TOP: 'STYLE_IMPORTS_TOP',
    
    LOGIC_UNUSED_VAR: 'LOGIC_UNUSED_VAR', // Params: { name }
    LOGIC_DEEP_NESTING: 'LOGIC_DEEP_NESTING',
    LOGIC_ASSIGN_IN_COND: 'LOGIC_ASSIGN_IN_COND',
    
    PERF_RANGE_LEN: 'PERF_RANGE_LEN',
    
    BEST_PRACTICE_DOCSTRING: 'BEST_PRACTICE_DOCSTRING', // Params: { name }
    BEST_PRACTICE_MANY_PRINT: 'BEST_PRACTICE_MANY_PRINT',
    BEST_PRACTICE_COMMENTS: 'BEST_PRACTICE_COMMENTS',
    
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',

    // --- PYTHON AST ANALYSIS (AnalysisEngine.ts) ---
    AST_MISSING_COLON: 'AST_MISSING_COLON',
    AST_LEADING_ZEROS: 'AST_LEADING_ZEROS',
    AST_OUTSIDE_LOOP: 'AST_OUTSIDE_LOOP',
    AST_UNMATCHED_PAREN: 'AST_UNMATCHED_PAREN',
    AST_INDENTATION: 'AST_INDENTATION',
    AST_ASSIGN_COMPARE: 'AST_ASSIGN_COMPARE',
    AST_EOL_STRING: 'AST_EOL_STRING',
    
    AST_STR_NO_APPEND: 'AST_STR_NO_APPEND',
    AST_LIST_NO_ADD: 'AST_LIST_NO_ADD',
    AST_STR_NO_REVERSE: 'AST_STR_NO_REVERSE',
    AST_TYPE_MATH: 'AST_TYPE_MATH',
    AST_NOT_SUBSCRIPTABLE: 'AST_NOT_SUBSCRIPTABLE',
    AST_NOT_CALLABLE: 'AST_NOT_CALLABLE',
    AST_ARG_COUNT: 'AST_ARG_COUNT',
    
    AST_VALUE_INT: 'AST_VALUE_INT',
    AST_UNPACKING: 'AST_UNPACKING',
    AST_INDEX_ERROR: 'AST_INDEX_ERROR',
    AST_KEY_ERROR: 'AST_KEY_ERROR',
    AST_DICT_SIZE: 'AST_DICT_SIZE',
    
    AST_ATTR_NONE: 'AST_ATTR_NONE',
    AST_ZERO_DIV: 'AST_ZERO_DIV',
    AST_MODULE_NOT_FOUND: 'AST_MODULE_NOT_FOUND',
    AST_EOF: 'AST_EOF',
    AST_UNBOUND_LOCAL: 'AST_UNBOUND_LOCAL',
    AST_RECURSION: 'AST_RECURSION',
    
    AST_INIT_TYPO: 'AST_INIT_TYPO', // Params: { class, method }
    AST_MISSING_SELF: 'AST_MISSING_SELF', // Params: { method }
    AST_PRINT_NO_RETURN: 'AST_PRINT_NO_RETURN', // Params: { func }
    AST_SHADOWING: 'AST_SHADOWING', // Params: { names }
    AST_MUTABLE_DEFAULT: 'AST_MUTABLE_DEFAULT', // Params: { funcs }
    AST_INPLACE_ASSIGN: 'AST_INPLACE_ASSIGN', // Params: { method }
    AST_TUPLE_COMMA: 'AST_TUPLE_COMMA',
    AST_LIST_MULT: 'AST_LIST_MULT',
    AST_MODIFY_ITER: 'AST_MODIFY_ITER', // Params: { name }
    AST_WHILE_TRUE: 'AST_WHILE_TRUE',
    AST_FLOAT_EQ: 'AST_FLOAT_EQ',
    AST_IS_LITERAL: 'AST_IS_LITERAL',
    AST_BOOL_TRAP: 'AST_BOOL_TRAP', // Params: { value }
    AST_BITWISE_XOR: 'AST_BITWISE_XOR',
    AST_OPEN_NO_WITH: 'AST_OPEN_NO_WITH',
    AST_PRINT_FUNC: 'AST_PRINT_FUNC', // Params: { name }
    AST_BARE_EXCEPT: 'AST_BARE_EXCEPT',
    AST_EXCEPT_PASS: 'AST_EXCEPT_PASS',
    
    // --- PARETO EXPANSION (NEW) ---
    AST_TUPLE_ITEM_ASSIGN: 'AST_TUPLE_ITEM_ASSIGN',
    AST_STR_ITEM_ASSIGN: 'AST_STR_ITEM_ASSIGN',
    AST_LEN_AS_METHOD: 'AST_LEN_AS_METHOD',
    AST_NULL_CHECK: 'AST_NULL_CHECK',
    AST_RETURN_LOOP_EARLY: 'AST_RETURN_LOOP_EARLY',
    AST_UNREACHABLE_CODE: 'AST_UNREACHABLE_CODE',
    AST_COMPARE_BOOL: 'AST_COMPARE_BOOL',
    AST_REDUNDANT_KEYS: 'AST_REDUNDANT_KEYS',
    AST_RANGE_ZERO: 'AST_RANGE_ZERO',
    SYNTAX_ELSE_IF: 'SYNTAX_ELSE_IF',
    
    // --- EXPANDED RULES (CLEANUP) ---
    AST_POINTLESS_STATEMENT: 'AST_POINTLESS_STATEMENT',
    AST_IMMUTABLE_STR: 'AST_IMMUTABLE_STR', // Params: { method }
    AST_GLOBAL_STMT: 'AST_GLOBAL_STMT',
    AST_CONFUSING_TUPLE: 'AST_CONFUSING_TUPLE',
    AST_DUPLICATE_KEY: 'AST_DUPLICATE_KEY',

    // --- RUNTIME ERRORS (ErrorTranslator.ts) ---
    RUNTIME_SYNTAX_PRINT: 'RUNTIME_SYNTAX_PRINT',
    RUNTIME_SYNTAX_INVALID: 'RUNTIME_SYNTAX_INVALID',
    RUNTIME_NAME_ERROR: 'RUNTIME_NAME_ERROR', // Params: { name }
    RUNTIME_INDENT_BLOCK: 'RUNTIME_INDENT_BLOCK',
    RUNTIME_INDENT_ALIGN: 'RUNTIME_INDENT_ALIGN',
    RUNTIME_TYPE_CALLABLE: 'RUNTIME_TYPE_CALLABLE',
    RUNTIME_ZERO_DIV: 'RUNTIME_ZERO_DIV',
    
    // --- ASSERTIONS (TestRunner.ts) ---
    ASSERT_EQUAL_STR: 'ASSERT_EQUAL_STR', // Params: { expected, actual }
    ASSERT_EQUAL_NUM: 'ASSERT_EQUAL_NUM', // Params: { expected, actual }
    ASSERT_GENERIC: 'ASSERT_GENERIC', // Params: { message }
    
    // --- SYSTEM ---
    SYS_INTERNAL: 'SYS_INTERNAL',
    SYS_TIMEOUT: 'SYS_TIMEOUT',
    SYS_OUTPUT_CORRUPT: 'SYS_OUTPUT_CORRUPT'
} as const;

export type ErrorCode = keyof typeof ErrorCodes;

export interface AnalysisMessage {
    code: ErrorCode;
    params?: Record<string, string | number>;
    line?: number;
    severity?: 'error' | 'warning' | 'info' | 'suggestion';
}
