const restContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Sorting lists",
      "",
      "The items in a list can be *sorted* from smallest to greatest with the method `sort`.",
      "",
      "```python",
      "my_list = [2,5,1,2,4]",
      "my_list.sort()",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Notice how the method modifies the list itself. Sometimes we don't want to change the original list, so we use the function `sorted` instead. It *returns* a sorted list:",
      "",
      "```python",
      "my_list = [2,5,1,2,4]",
      "print(sorted(my_list))",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Remember the difference between the two: `sort` changes the order of the original list in place, whereas `sorted` creates a new, ordered copy of the list. With `sorted` we can preserve the original order of the list:",
      "",
      "```python",
      "original = [2, 5, 1, 2, 4]",
      "in_order = sorted(original)",
      "print(original)",
      "print(in_order)",
      "```",
      "",
      "```text",
      "[2, 5, 1, 2, 4]",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "## Maximum, minimum and sum",
      "",
      "The functions `max` and `min`, short for maximum and minimum, return the greatest and smallest item in a list, respectively. The function `sum` returns the sum of all items in a list.",
      "",
      "```python",
      "my_list = [5, 2, 3, 1, 4]",
      "",
      "greatest = max(my_list)",
      "smallest = min(my_list)",
      "list_sum = sum(my_list)",
      "",
      "print(\"Smallest:\", smallest)",
      "print(\"Greatest:\", greatest)",
      "print(\"Sum:\", list_sum)",
      "```",
      "",
      "```text",
      "Smallest: 1",
      "Greatest: 5",
      "Sum: 15",
      "```",
      "",
      "## Methods vs functions",
      "",
      "There are two different ways of processing lists in Python, which can get confusing. For the most part you will use list *methods*, such as `append` and `sort`. They are used with the dot `.` operator on the list variable:",
      "",
      "```python",
      "my_list = []",
      "",
      "# method calls",
      "my_list.append(3)",
      "my_list.append(1)",
      "my_list.append(7)",
      "my_list.append(2)",
      "",
      "# another method call",
      "my_list.sort()",
      "```",
      "",
      "Some *functions* are happy to take a list as an argument. Above we saw the functions `max`, `min`, `len` and `sorted` do just that:",
      "",
      "```python",
      "my_list = [3, 2, 7, 1]",
      "",
      "# function calls take the list as an argument",
      "greatest = max(my_list)",
      "smallest = min(my_list)",
      "length = len(my_list)",
      "",
      "print(\"Smallest:\", smallest)",
      "print(\"Greatest:\", greatest)",
      "print(\"Length of the list:\", length)",
      "",
      "# another function call",
      "# the list itself is an argument, the function returns a sorted copy",
      "in_order = sorted(my_list)",
      "print(in_order)",
      "```",
      "",
      "```text",
      "Smallest: 1",
      "Greatest: 7",
      "Length of the list: 4",
      "[1, 2, 3, 7]",
      "```",
      "",
      "## A list as an argument or a return value",
      "",
      "Just like the built-in functions above, our own functions can also take a list as an argument and produce a list as a return value. The following function works out the central value in an ordered list, also called the *median* value:",
      "",
      "```python",
      "def median(my_list: list):",
      "    ordered = sorted(my_list)",
      "    list_centre = len(ordered) // 2",
      "    return ordered[list_centre]",
      "```",
      "",
      "The function creates an ordered version of the list given as an argument and returns the item in the very middle. Notice the integer division operator `//` used here. The index of a list should always be an integer.",
      "",
      "The function works like this:",
      "",
      "```python",
      "shoe_sizes = [45, 44, 36, 39, 40]",
      "print(\"The median of the shoe sizes is\", median(shoe_sizes))",
      "",
      "ages = [1, 56, 34, 22, 5, 77, 5]",
      "print(\"The median of the ages is\", median(ages))",
      "```",
      "",
      "```text",
      "The median of the shoe sizes is 40",
      "The median of the ages is 22",
      "```",
      "",
      "A function can also return a list. The following function asks the user to type in integers and returns the input as a list:",
      "",
      "```python",
      "def input_numbers():",
      "    numbers = []",
      "    while True:",
      "        user_input = input(\"Please type in an integer, leave empty to exit: \")",
      "        if len(user_input) == 0:",
      "            break",
      "        numbers.append(int(user_input))",
      "    return numbers",
      "```",
      "",
      "The function makes use of a helper variable `numbers`, which is a list. All the numbers typed in by the user are added to the list. When the loop is exited from, the function returns the list with the statement `return numbers`.",
      "",
      "Calling the function like this",
      "",
      "```python",
      "numbers = input_numbers()",
      "",
      "print(\"The greatest number is\", max(numbers))",
      "print(\"The median of the numbers is\", median(numbers))",
      "```",
      "",
      "could print this, for example:",
      "",
      "```text",
      "Please type in an integer, leave empty to exit: 5",
      "Please type in an integer, leave empty to exit: -22",
      "Please type in an integer, leave empty to exit: 4",
      "Please type in an integer, leave empty to exit: 35",
      "Please type in an integer, leave empty to exit: 1",
      "Please type in an integer, leave empty to exit:",
      "The greatest number is 35",
      "The median of the numbers is 4",
      "```",
      "",
      "This small example demonstrates one of the most important uses of functions: they can help you divide your code into smaller, easily understandable and logical wholes.",
      "",
      "Of course the same functionality could be achieved without writing any of our own functions:",
      "",
      "```python",
      "numbers = []",
      "while True:",
      "    user_input = input(\"Please type in an integer, leave empty to exit: \")",
      "    if len(user_input) == 0:",
      "        break",
      "    numbers.append(int(user_input))",
      "",
      "ordered = sorted(numbers)",
      "list_centre = len(ordered) // 2",
      "median = ordered[list_centre]",
      "",
      "print(\"The greatest number is\", max(numbers))",
      "print(\"The median of the numbers is\", median)",
      "```",
      "",
      "In this version, following the programming logic is more difficult, as it is no longer clear which commands are a part of which functionality. The code fulfils the same purposes - reading in input, calculating the median value, and so on - but the structure is less clear.",
      "",
      "Organising your code into separate functions will improve you program's readability, but also make it easier to handle logical wholes. This in turn helps you verify that the program works as intended, as each function can be tested separately.",
      "",
      "Another important use for functions is making code *reusable*. If you need to achieve some functionality multiple times in your program, it is a good idea to create your own function and name it appropriately:",
      "",
      "```python",
      "print(\"Shoe sizes:\")",
      "shoe_sizes = input_numbers()",
      "",
      "print(\"Weights:\")",
      "weights = input_numbers()",
      "",
      "print(\"Heights:\")",
      "heights = input_numbers()",
      "```"
    ].join("\n"),
    CAS: [
      "## Ordenando listas",
      "",
      "Los elementos en una lista se pueden *ordenar* de menor a mayor con el método `sort`.",
      "",
      "```python",
      "mi_lista = [2,5,1,2,4]",
      "mi_lista.sort()",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Observa cómo el método modifica la lista en sí. A veces no queremos cambiar la lista original, por lo que usamos la función `sorted` en su lugar. Esta *devuelve* una lista ordenada:",
      "",
      "```python",
      "mi_lista = [2,5,1,2,4]",
      "print(sorted(mi_lista))",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Recuerda la diferencia entre los dos: `sort` cambia el orden de la lista original in situ, mientras que `sorted` crea una copia nueva y ordenada de la lista. Con `sorted` podemos preservar el orden original de la lista:",
      "",
      "```python",
      "original = [2, 5, 1, 2, 4]",
      "en_orden = sorted(original)",
      "print(original)",
      "print(en_orden)",
      "```",
      "",
      "```text",
      "[2, 5, 1, 2, 4]",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "## Máximo, mínimo y suma",
      "",
      "Las funciones `max` y `min`, abreviaturas de máximo y mínimo, devuelven el elemento mayor y menor de una lista, respectivamente. La función `sum` devuelve la suma de todos los elementos en una lista.",
      "",
      "```python",
      "mi_lista = [5, 2, 3, 1, 4]",
      "",
      "mayor = max(mi_lista)",
      "menor = min(mi_lista)",
      "suma_lista = sum(mi_lista)",
      "",
      "print(\"Menor:\", menor)",
      "print(\"Mayor:\", mayor)",
      "print(\"Suma:\", suma_lista)",
      "```",
      "",
      "```text",
      "Menor: 1",
      "Mayor: 5",
      "Suma: 15",
      "```",
      "",
      "## Métodos vs funciones",
      "",
      "Hay dos formas diferentes de procesar listas en Python, lo que puede resultar confuso. En su mayor parte, utilizarás *métodos* de lista, como `append` y `sort`. Se utilizan con el operador punto `.` en la variable de la lista:",
      "",
      "```python",
      "mi_lista = []",
      "",
      "# llamadas a métodos",
      "mi_lista.append(3)",
      "mi_lista.append(1)",
      "mi_lista.append(7)",
      "mi_lista.append(2)",
      "",
      "# otra llamada a método",
      "mi_lista.sort()",
      "```",
      "",
      "Algunas *funciones* aceptan una lista como argumento. Arriba vimos que las funciones `max`, `min`, `len` y `sorted` hacen exactamente eso:",
      "",
      "```python",
      "mi_lista = [3, 2, 7, 1]",
      "",
      "# las llamadas a funciones toman la lista como argumento",
      "mayor = max(mi_lista)",
      "menor = min(mi_lista)",
      "longitud = len(mi_lista)",
      "",
      "print(\"Menor:\", menor)",
      "print(\"Mayor:\", mayor)",
      "print(\"Longitud de la lista:\", longitud)",
      "",
      "# otra llamada a función",
      "# la lista en sí es un argumento, la función devuelve una copia ordenada",
      "en_orden = sorted(mi_lista)",
      "print(en_orden)",
      "```",
      "",
      "```text",
      "Menor: 1",
      "Mayor: 7",
      "Longitud de la lista: 4",
      "[1, 2, 3, 7]",
      "```",
      "",
      "## Una lista como argumento o valor de retorno",
      "",
      "Al igual que las funciones incorporadas anteriores, nuestras propias funciones también pueden tomar una lista como argumento y producir una lista como valor de retorno. La siguiente función calcula el valor central en una lista ordenada, también llamado valor *mediano*:",
      "",
      "```python",
      "def mediana(mi_lista: list):",
      "    ordenada = sorted(mi_lista)",
      "    centro_lista = len(ordenada) // 2",
      "    return ordenada[centro_lista]",
      "```",
      "",
      "La función crea una versión ordenada de la lista dada como argumento y devuelve el elemento en el mismo centro. Observa el operador de división entera `//` utilizado aquí. El índice de una lista siempre debe ser un entero.",
      "",
      "La función funciona así:",
      "",
      "```python",
      "tallas_zapatos = [45, 44, 36, 39, 40]",
      "print(\"La mediana de las tallas de zapatos es\", mediana(tallas_zapatos))",
      "",
      "edades = [1, 56, 34, 22, 5, 77, 5]",
      "print(\"La mediana de las edades es\", mediana(edades))",
      "```",
      "",
      "```text",
      "La mediana de las tallas de zapatos es 40",
      "La mediana de las edades es 22",
      "```",
      "",
      "Una función también puede devolver una lista. La siguiente función pide al usuario que escriba números enteros y devuelve la entrada como una lista:",
      "",
      "```python",
      "def ingresar_numeros():",
      "    numeros = []",
      "    while True:",
      "        entrada_usuario = input(\"Por favor escribe un entero, deja vacío para salir: \")",
      "        if len(entrada_usuario) == 0:",
      "            break",
      "        numeros.append(int(entrada_usuario))",
      "    return numeros",
      "```",
      "",
      "La función hace uso de una variable auxiliar `numeros`, que es una lista. Todos los números escritos por el usuario se añaden a la lista. Cuando se sale del bucle, la función devuelve la lista con la sentencia `return numeros`.",
      "",
      "Llamando a la función así",
      "",
      "```python",
      "numeros = ingresar_numeros()",
      "",
      "print(\"El número mayor es\", max(numeros))",
      "print(\"La mediana de los números es\", mediana(numeros))",
      "```",
      "",
      "podría imprimir esto, por ejemplo:",
      "",
      "```text",
      "Por favor escribe un entero, deja vacío para salir: 5",
      "Por favor escribe un entero, deja vacío para salir: -22",
      "Por favor escribe un entero, deja vacío para salir: 4",
      "Por favor escribe un entero, deja vacío para salir: 35",
      "Por favor escribe un entero, deja vacío para salir: 1",
      "Por favor escribe un entero, deja vacío para salir:",
      "El número mayor es 35",
      "La mediana de los números es 4",
      "```",
      "",
      "Este pequeño ejemplo demuestra uno de los usos más importantes de las funciones: pueden ayudarte a dividir tu código en partes lógicas más pequeñas y fáciles de entender.",
      "",
      "Por supuesto, la misma funcionalidad se podría lograr sin escribir ninguna de nuestras propias funciones:",
      "",
      "```python",
      "numeros = []",
      "while True:",
      "    entrada_usuario = input(\"Por favor escribe un entero, deja vacío para salir: \")",
      "    if len(entrada_usuario) == 0:",
      "        break",
      "    numeros.append(int(entrada_usuario))",
      "",
      "ordenada = sorted(numeros)",
      "centro_lista = len(ordenada) // 2",
      "mediana = ordenada[centro_lista]",
      "",
      "print(\"El número mayor es\", max(numeros))",
      "print(\"La mediana de los números es\", mediana)",
      "```",
      "",
      "En esta versión, seguir la lógica de programación es más difícil, ya que ya no está claro qué comandos son parte de qué funcionalidad. El código cumple los mismos propósitos (leer la entrada, calcular el valor mediano, etc.), pero la estructura es menos clara.",
      "",
      "Organizar tu código en funciones separadas mejorará la legibilidad de tu programa, pero también facilitará el manejo de conjuntos lógicos. Esto a su vez te ayuda a verificar que el programa funciona según lo previsto, ya que cada función se puede probar por separado.",
      "",
      "Otro uso importante para las funciones es hacer que el código sea *reutilizable*. Si necesitas lograr alguna funcionalidad varias veces en tu programa, es una buena idea crear tu propia función y nombrarla adecuadamente:",
      "",
      "```python",
      "print(\"Tallas de zapatos:\")",
      "tallas_zapatos = ingresar_numeros()",
      "",
      "print(\"Pesos:\")",
      "pesos = ingresar_numeros()",
      "",
      "print(\"Alturas:\")",
      "alturas = ingresar_numeros()",
      "```"
    ].join("\n"),
    EUS: [
      "## Zerrendak ordenatzen",
      "",
      "Zerrenda bateko elementuak txikienetik handienera *ordenatu* daitezke `sort` metodoarekin.",
      "",
      "```python",
      "nire_zerrenda = [2,5,1,2,4]",
      "nire_zerrenda.sort()",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Ohartu metodoak zerrenda bera aldatzen duela. Batzuetan ez dugu jatorrizko zerrenda aldatu nahi, beraz, `sorted` funtzioa erabiltzen dugu horren ordez. Honek zerrenda ordenatu bat *itzultzen* du:",
      "",
      "```python",
      "nire_zerrenda = [2,5,1,2,4]",
      "print(sorted(nire_zerrenda))",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Gogoratu bien arteko aldea: `sort`-ek jatorrizko zerrendaren ordena aldatzen du, eta `sorted`-ek zerrendaren kopia berri eta ordenatu bat sortzen du. `sorted`-ekin zerrendaren jatorrizko ordena gorde dezakegu:",
      "",
      "```python",
      "jatorrizkoa = [2, 5, 1, 2, 4]",
      "ordenatua = sorted(jatorrizkoa)",
      "print(jatorrizkoa)",
      "print(ordenatua)",
      "```",
      "",
      "```text",
      "[2, 5, 1, 2, 4]",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "## Maximoa, minimoa eta batura",
      "",
      "`max` eta `min` funtzioek, maximo eta minimoaren laburdurak, zerrenda bateko elementu handiena eta txikiena itzultzen dute, hurrenez hurren. `sum` funtzioak zerrenda bateko elementu guztien batura itzultzen du.",
      "",
      "```python",
      "nire_zerrenda = [5, 2, 3, 1, 4]",
      "",
      "handiena = max(nire_zerrenda)",
      "txikiena = min(nire_zerrenda)",
      "zerrenda_batura = sum(nire_zerrenda)",
      "",
      "print(\"Txikiena:\", txikiena)",
      "print(\"Handiena:\", handiena)",
      "print(\"Batura:\", zerrenda_batura)",
      "```",
      "",
      "```text",
      "Txikiena: 1",
      "Handiena: 5",
      "Batura: 15",
      "```",
      "",
      "## Metodoak vs funtzioak",
      "",
      "Python-en zerrendak prozesatzeko bi modu desberdin daude, eta horrek nahasmena sor dezake. Gehienetan zerrenda *metodoak* erabiliko dituzu, adibidez `append` eta `sort`. Puntu `.` eragilearekin erabiltzen dira zerrenda aldagaian:",
      "",
      "```python",
      "nire_zerrenda = []",
      "",
      "# metodo deiak",
      "nire_zerrenda.append(3)",
      "nire_zerrenda.append(1)",
      "nire_zerrenda.append(7)",
      "nire_zerrenda.append(2)",
      "",
      "# beste metodo dei bat",
      "nire_zerrenda.sort()",
      "```",
      "",
      "*Funtzio* batzuek zerrenda bat argumentu gisa onartzen dute. Goian ikusi ditugu `max`, `min`, `len` eta `sorted` funtzioak horixe egiten:",
      "",
      "```python",
      "nire_zerrenda = [3, 2, 7, 1]",
      "",
      "# funtzio deiek zerrenda argumentu gisa hartzen dute",
      "handiena = max(nire_zerrenda)",
      "txikiena = min(nire_zerrenda)",
      "luzera = len(nire_zerrenda)",
      "",
      "print(\"Txikiena:\", txikiena)",
      "print(\"Handiena:\", handiena)",
      "print(\"Zerrendaren luzera:\", luzera)",
      "",
      "# beste funtzio dei bat",
      "# zerrenda bera da argumentua, funtzioak kopia ordenatu bat itzultzen du",
      "ordenatua = sorted(nire_zerrenda)",
      "print(ordenatua)",
      "```",
      "",
      "```text",
      "Txikiena: 1",
      "Handiena: 7",
      "Zerrendaren luzera: 4",
      "[1, 2, 3, 7]",
      "```",
      "",
      "## Zerrenda bat argumentu edo itzulera-balio gisa",
      "",
      "Goiko funtzio integratuak bezala, gure funtzioek ere zerrenda bat har dezakete argumentu gisa eta zerrenda bat sor dezakete itzulera-balio gisa. Hurrengo funtzioak zerrenda ordenatu bateko erdiko balioa kalkulatzen du, *mediana* balioa ere deitua:",
      "",
      "```python",
      "def mediana(nire_zerrenda: list):",
      "    ordenatua = sorted(nire_zerrenda)",
      "    zerrenda_erdia = len(ordenatua) // 2",
      "    return ordenada[zerrenda_erdia]",
      "```",
      "",
      "Funtzioak argumentu gisa emandako zerrendaren bertsio ordenatu bat sortzen du eta erdian dagoen elementua itzultzen du. Ohartu hemen erabilitako `//` zatiketa osoaren eragileaz. Zerrenda baten indizeak beti zenbaki osoa izan behar du.",
      "",
      "Funtzioak horrela funtzionatzen du:",
      "",
      "```python",
      "oinetako_neurriak = [45, 44, 36, 39, 40]",
      "print(\"Oinetako neurrien mediana da\", mediana(oinetako_neurriak))",
      "",
      "adinak = [1, 56, 34, 22, 5, 77, 5]",
      "print(\"Adinen mediana da\", mediana(adinak))",
      "```",
      "",
      "```text",
      "Oinetako neurrien mediana da 40",
      "Adinen mediana da 22",
      "```",
      "",
      "Funtzio batek zerrenda bat ere itzul dezake. Hurrengo funtzioak erabiltzaileari zenbaki osoak idazteko eskatzen dio eta sarrera zerrenda gisa itzultzen du:",
      "",
      "```python",
      "def zenbakiak_sartu():",
      "    zenbakiak = []",
      "    while True:",
      "        erabiltzaile_sarrera = input(\"Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: \")",
      "        if len(erabiltzaile_sarrera) == 0:",
      "            break",
      "        zenbakiak.append(int(erabiltzaile_sarrera))",
      "    return zenbakiak",
      "```",
      "",
      "Funtzioak `zenbakiak` aldagai laguntzailea erabiltzen du, zerrenda bat dena. Erabiltzaileak idatzitako zenbaki guztiak zerrendara gehitzen dira. Begiztatik irteten denean, funtzioak zerrenda itzultzen du `return zenbakiak` sententziarekin.",
      "",
      "Funtzioa horrela deituz",
      "",
      "```python",
      "zenbakiak = zenbakiak_sartu()",
      "",
      "print(\"Zenbaki handiena da\", max(zenbakiak))",
      "print(\"Zenbakien mediana da\", mediana(zenbakiak))",
      "```",
      "",
      "hau inprimatu lezake, adibidez:",
      "",
      "```text",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 5",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: -22",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 4",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 35",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 1",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko:",
      "Zenbaki handiena da 35",
      "Zenbakien mediana da 4",
      "```",
      "",
      "Adibide txiki honek funtzioen erabilera garrantzitsuenetako bat erakusten du: zure kodea zati logiko txikiago eta ulerterrazagoetan banatzen lagun dezakete.",
      "",
      "Jakina, funtzionalitate bera lor liteke gure funtziorik idatzi gabe:",
      "",
      "```python",
      "zenbakiak = []",
      "while True:",
      "    erabiltzaile_sarrera = input(\"Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: \")",
      "    if len(erabiltzaile_sarrera) == 0:",
      "        break",
      "    zenbakiak.append(int(erabiltzaile_sarrera))",
      "",
      "ordenatua = sorted(zenbakiak)",
      "zerrenda_erdia = len(ordenatua) // 2",
      "mediana = ordenatua[zerrenda_erdia]",
      "",
      "print(\"Zenbaki handiena da\", max(zenbakiak))",
      "print(\"Zenbakien mediana da\", mediana)",
      "```",
      "",
      "Bertsio honetan, programazio-logika jarraitzea zailagoa da, jada ez baitago argi zein komando diren zein funtzionalitateren parte. Kodeak helburu berberak betetzen ditu - sarrera irakurtzea, mediana kalkulatzea, eta abar - baina egitura ez da hain argia.",
      "",
      "Zure kodea funtzio bereizietan antolatzeak zure programaren irakurgarritasuna hobetuko du, baina baita osotasun logikoak maneiatzea erraztuko ere. Honek, aldi berean, programak nahi bezala funtzionatzen duela egiaztatzen laguntzen dizu, funtzio bakoitza bere aldetik probatu baitaiteke.",
      "",
      "Funtzioen beste erabilera garrantzitsu bat kodea *berrerabilgarria* egitea da. Zure programan funtzionalitateren bat hainbat aldiz lortu behar baduzu, ideia ona da zure funtzioa sortzea eta egoki izendatzea:",
      "",
      "```python",
      "print(\"Oinetako neurriak:\")",
      "oinetako_neurriak = zenbakiak_sartu()",
      "",
      "print(\"Pisuak:\")",
      "pesos = zenbakiak_sartu()",
      "",
      "print(\"Altuerak:\")",
      "altuerak = zenbakiak_sartu()",
      "```"
    ].join("\n")
  }
};

module.exports = { restContent };
