const addingItemsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Adding items to a list",
      "",
      "The `append` method adds items to the end of a list. It works like this:",
      "",
      "```python",
      "numbers = []",
      "numbers.append(5)",
      "numbers.append(10)",
      "numbers.append(3)",
      "print(numbers)",
      "```",
      "",
      "```text",
      "[5, 10, 3]",
      "```",
      "",
      "The following example makes use of two separate lists:",
      "",
      "```python",
      "numbers = []",
      "shoe_sizes = []",
      "",
      "numbers.append(5)",
      "numbers.append(10)",
      "numbers.append(3)",
      "",
      "shoe_sizes.append(37)",
      "shoe_sizes.append(44)",
      "shoe_sizes.append(40)",
      "shoe_sizes.append(28)",
      "",
      "print(\"Numbers:\")",
      "print(numbers)",
      "",
      "print(\"Shoe sizes:\")",
      "print(shoe_sizes)",
      "```",
      "",
      "The item is appended to the list on which the method is called:",
      "",
      "```text",
      "Numbers:",
      "[5, 10, 3]",
      "Shoe sizes:",
      "[37, 44, 40, 28]",
      "```",
      "",
      "## Adding to a specific location",
      "",
      "If you want to specify a location in the list where an item should be added, you can use the `insert` method. The method adds an item at the specified index. All the items already in the list with an index equal to or higher than the specified index are moved one index further, \"to the right:\"",
      "",
      "![Inserting an item to a list](images/4_3_2.png)",
      "",
      "So, for instance this program",
      "",
      "```python",
      "numbers = [1, 2, 3, 4, 5, 6]",
      "numbers.insert(0, 10)",
      "print(numbers)",
      "numbers.insert(2, 20)",
      "print(numbers)",
      "```",
      "",
      "prints out this:",
      "",
      "```text",
      "[10, 1, 2, 3, 4, 5, 6]",
      "[10, 1, 20, 2, 3, 4, 5, 6]",
      "```"
    ].join("\n"),
    CAS: [
      "## Añadir elementos a una lista",
      "",
      "El método `append` añade elementos al final de una lista. Funciona así:",
      "",
      "```python",
      "numeros = []",
      "numeros.append(5)",
      "numeros.append(10)",
      "numeros.append(3)",
      "print(numeros)",
      "```",
      "",
      "```text",
      "[5, 10, 3]",
      "```",
      "",
      "El siguiente ejemplo hace uso de dos listas separadas:",
      "",
      "```python",
      "numeros = []",
      "tallas_zapatos = []",
      "",
      "numeros.append(5)",
      "numeros.append(10)",
      "numeros.append(3)",
      "",
      "tallas_zapatos.append(37)",
      "tallas_zapatos.append(44)",
      "tallas_zapatos.append(40)",
      "tallas_zapatos.append(28)",
      "",
      "print(\"Números:\")",
      "print(numeros)",
      "",
      "print(\"Tallas de zapatos:\")",
      "print(tallas_zapatos)",
      "```",
      "",
      "El elemento se añade a la lista sobre la que se llama el método:",
      "",
      "```text",
      "Números:",
      "[5, 10, 3]",
      "Tallas de zapatos:",
      "[37, 44, 40, 28]",
      "```",
      "",
      "## Añadir a una ubicación específica",
      "",
      "Si quieres especificar una ubicación en la lista donde se debe añadir un elemento, puedes usar el método `insert`. El método añade un elemento en el índice especificado. Todos los elementos que ya están en la lista con un índice igual o superior al índice especificado se mueven un índice más allá, \"a la derecha:\"",
      "",
      "![Insertar un elemento en una lista](images/4_3_2.png)",
      "",
      "Así, por ejemplo, este programa",
      "",
      "```python",
      "numeros = [1, 2, 3, 4, 5, 6]",
      "numeros.insert(0, 10)",
      "print(numeros)",
      "numeros.insert(2, 20)",
      "print(numeros)",
      "```",
      "",
      "imprime esto:",
      "",
      "```text",
      "[10, 1, 2, 3, 4, 5, 6]",
      "[10, 1, 20, 2, 3, 4, 5, 6]",
      "```"
    ].join("\n"),
    EUS: [
      "## Elementuak zerrenda batera gehitzen",
      "",
      "`append` metodoak elementuak gehitzen ditu zerrenda baten amaieran. Horrela funtzionatzen du:",
      "",
      "```python",
      "zenbakiak = []",
      "zenbakiak.append(5)",
      "zenbakiak.append(10)",
      "zenbakiak.append(3)",
      "print(zenbakiak)",
      "```",
      "",
      "```text",
      "[5, 10, 3]",
      "```",
      "",
      "Hurrengo adibideak bi zerrenda bereizi erabiltzen ditu:",
      "",
      "```python",
      "zenbakiak = []",
      "oinetako_neurriak = []",
      "",
      "zenbakiak.append(5)",
      "zenbakiak.append(10)",
      "zenbakiak.append(3)",
      "",
      "oinetako_neurriak.append(37)",
      "oinetako_neurriak.append(44)",
      "oinetako_neurriak.append(40)",
      "oinetako_neurriak.append(28)",
      "",
      "print(\"Zenbakiak:\")",
      "print(zenbakiak)",
      "",
      "print(\"Oinetako neurriak:\")",
      "print(oinetako_neurriak)",
      "```",
      "",
      "Elementua metodoa deitzen den zerrendari gehitzen zaio:",
      "",
      "```text",
      "Zenbakiak:",
      "[5, 10, 3]",
      "Oinetako neurriak:",
      "[37, 44, 40, 28]",
      "```",
      "",
      "## Kokapen zehatz batera gehitzen",
      "",
      "Elementu bat zerrendako zein kokapenetan gehitu behar den zehaztu nahi baduzu, `insert` metodoa erabil dezakezu. Metodoak elementu bat gehitzen du zehaztutako indizean. Zerrendan lehendik dauden elementu guztiak, zehaztutako indizearen berdina edo handiagoa dutenak, indize bat harago mugitzen dira, \"eskuinera:\"",
      "",
      "![Elementu bat zerrenda batera txertatzen](images/4_3_2.png)",
      "",
      "Beraz, adibidez programa honek",
      "",
      "```python",
      "zenbakiak = [1, 2, 3, 4, 5, 6]",
      "zenbakiak.insert(0, 10)",
      "print(zenbakiak)",
      "zenbakiak.insert(2, 20)",
      "print(zenbakiak)",
      "```",
      "",
      "hau inprimatzen du:",
      "",
      "```text",
      "[10, 1, 2, 3, 4, 5, 6]",
      "[10, 1, 20, 2, 3, 4, 5, 6]",
      "```"
    ].join("\n")
  }
};

const exerciseAddItems = {
  type: "exercise",
  exerciseId: "part04-13_add_items_to_list",
  title: {
    ENG: "Add items to a list",
    CAS: "Añadir elementos a una lista",
    EUS: "Gehitu elementuak zerrenda batera"
  },
  description: {
    ENG: "Write a program that asks the user to input the number of items they want to add to a list. Then, ask for the items one by one and add them to the list. Finally, print the list.",
    CAS: "Escribe un programa que pida al usuario el número de elementos que quiere añadir a una lista. Luego, pide los elementos uno por uno y añádelos a la lista. Finalmente, imprime la lista.",
    EUS: "Idatzi programa bat erabiltzaileari galdetzen diona zenbat elementu gehitu nahi dituen zerrenda batera. Ondoren, eskatu elementuak banan-banan eta gehitu zerrendara. Azkenik, inprimatu zerrenda."
  },
  initialCode: {
    ENG: "# Write your solution here",
    CAS: "# Escribe tu solución aquí",
    EUS: "# Idatzi zure soluzioa hemen"
  },
  testCode: [
    'import unittest',
    'from unittest.mock import patch',
    'class TestAddItems(unittest.TestCase):',
    '    def test_run(self):',
    '        inputs = ["3", "10", "20", "30"]',
    '        out = run_student_code(inputs=inputs)',
    '        self.assertIn("[10, 20, 30]", out, "Should print the list [10, 20, 30] | Debería imprimir la lista [10, 20, 30] | [10, 20, 30] zerrenda inprimatu beharko luke")'
  ].join("\n")
};

const removingItemsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Removing items from a list",
      "",
      "There are two different approaches to removing an item from a list:",
      "",
      "- If the *index* of the item is known, you can use the method `pop`.",
      "- If the *contents* of the item are known, you can use the method `remove`.",
      "",
      "So, the method `pop` takes the index of the item you want to remove as its argument. The following program removes items at indexes 2 and 3 from the list. Notice how the indexes of the remaining items change when one is removed.",
      "",
      "```python",
      "my_list = [1, 2, 3, 4, 5, 6]",
      "",
      "my_list.pop(2)",
      "print(my_list)",
      "my_list.pop(3)",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[1, 2, 4, 5, 6]",
      "[1, 2, 4, 6]",
      "```",
      "",
      "It's useful to remember that the method `pop` also *returns* the removed item:",
      "",
      "```python",
      "my_list = [4, 2, 7, 2, 5]",
      "",
      "number = my_list.pop(2)",
      "print(number)",
      "print(my_list)",
      "```",
      "",
      "```text",
      "7",
      "[4, 2, 2, 5]",
      "```",
      "",
      "The method `remove`, on the other hand, takes the value of the item to be removed as its argument. For example, this program",
      "",
      "```python",
      "my_list = [1, 2, 3, 4, 5, 6]",
      "",
      "my_list.remove(2)",
      "print(my_list)",
      "my_list.remove(5)",
      "print(my_list)",
      "```",
      "",
      "prints out this:",
      "",
      "```text",
      "[1, 3, 4, 5, 6]",
      "[1, 3, 4, 6]",
      "```",
      "",
      "The method removes the *first* occurrence of the value in the list, much like the string function `find` returns the first occurrence of a substring:",
      "",
      "```python",
      "my_list = [1, 2, 1, 2]",
      "",
      "my_list.remove(1)",
      "print(my_list)",
      "my_list.remove(1)",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[2, 1, 2]",
      "[2, 2]",
      "```",
      "",
      "If the specified item is not in the list, the `remove` function causes an error. Just like with strings, we can check for the presence of an item with the `in` operator:",
      "",
      "```python",
      "my_list = [1, 3, 4]",
      "",
      "if 1 in my_list:",
      "    print(\"The list contains item 1\")",
      "",
      "if 2 in my_list:",
      "    print(\"The list contains item 2\")",
      "```",
      "",
      "```text",
      "The list contains item 1",
      "```"
    ].join("\n"),
    CAS: [
      "## Eliminando elementos de una lista",
      "",
      "Hay dos enfoques diferentes para eliminar un elemento de una lista:",
      "",
      "- Si se conoce el *índice* del elemento, puedes usar el método `pop`.",
      "- Si se conoce el *contenido* del elemento, puedes usar el método `remove`.",
      "",
      "Así, el método `pop` toma el índice del elemento que quieres eliminar como argumento. El siguiente programa elimina los elementos en los índices 2 y 3 de la lista. Observa cómo cambian los índices de los elementos restantes cuando se elimina uno.",
      "",
      "```python",
      "mi_lista = [1, 2, 3, 4, 5, 6]",
      "",
      "mi_lista.pop(2)",
      "print(mi_lista)",
      "mi_lista.pop(3)",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[1, 2, 4, 5, 6]",
      "[1, 2, 4, 6]",
      "```",
      "",
      "Es útil recordar que el método `pop` también *devuelve* el elemento eliminado:",
      "",
      "```python",
      "mi_lista = [4, 2, 7, 2, 5]",
      "",
      "numero = mi_lista.pop(2)",
      "print(numero)",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "7",
      "[4, 2, 2, 5]",
      "```",
      "",
      "El método `remove`, por otro lado, toma el valor del elemento a eliminar como argumento. Por ejemplo, este programa",
      "",
      "```python",
      "mi_lista = [1, 2, 3, 4, 5, 6]",
      "",
      "mi_lista.remove(2)",
      "print(mi_lista)",
      "mi_lista.remove(5)",
      "print(mi_lista)",
      "```",
      "",
      "imprime esto:",
      "",
      "```text",
      "[1, 3, 4, 5, 6]",
      "[1, 3, 4, 6]",
      "```",
      "",
      "El método elimina la *primera* aparición del valor en la lista, muy parecido a como la función de cadena `find` devuelve la primera aparición de una subcadena:",
      "",
      "```python",
      "mi_lista = [1, 2, 1, 2]",
      "",
      "mi_lista.remove(1)",
      "print(mi_lista)",
      "mi_lista.remove(1)",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[2, 1, 2]",
      "[2, 2]",
      "```",
      "",
      "Si el elemento especificado no está en la lista, la función `remove` causa un error. Al igual que con las cadenas, podemos verificar la presencia de un elemento con el operador `in`:",
      "",
      "```python",
      "mi_lista = [1, 3, 4]",
      "",
      "if 1 in mi_lista:",
      "    print(\"La lista contiene el elemento 1\")",
      "",
      "if 2 in mi_lista:",
      "    print(\"La lista contiene el elemento 2\")",
      "```",
      "",
      "```text",
      "La lista contiene el elemento 1",
      "```"
    ].join("\n"),
    EUS: [
      "## Elementuak zerrenda batetik kentzen",
      "",
      "Zerrenda batetik elementu bat kentzeko bi ikuspegi desberdin daude:",
      "",
      "- Elementuaren *indizea* ezaguna bada, `pop` metodoa erabil dezakezu.",
      "- Elementuaren *edukia* ezaguna bada, `remove` metodoa erabil dezakezu.",
      "",
      "Beraz, `pop` metodoak kendu nahi duzun elementuaren indizea hartzen du argumentu gisa. Hurrengo programak 2 eta 3 indizeetako elementuak kentzen ditu zerrendatik. Ohartu nola aldatzen diren gainerako elementuen indizeak bat kentzen denean.",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 3, 4, 5, 6]",
      "",
      "nire_zerrenda.pop(2)",
      "print(nire_zerrenda)",
      "nire_zerrenda.pop(3)",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[1, 2, 4, 5, 6]",
      "[1, 2, 4, 6]",
      "```",
      "",
      "Komenigarria da gogoratzea `pop` metodoak kendutako elementua ere *itzultzen* duela:",
      "",
      "```python",
      "nire_zerrenda = [4, 2, 7, 2, 5]",
      "",
      "zenbakia = nire_zerrenda.pop(2)",
      "print(zenbakia)",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "7",
      "[4, 2, 2, 5]",
      "```",
      "",
      "`remove` metodoak, bestalde, kendu beharreko elementuaren balioa hartzen du argumentu gisa. Adibidez, programa honek",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 3, 4, 5, 6]",
      "",
      "nire_zerrenda.remove(2)",
      "print(nire_zerrenda)",
      "nire_zerrenda.remove(5)",
      "print(nire_zerrenda)",
      "```",
      "",
      "hau inprimatzen du:",
      "",
      "```text",
      "[1, 3, 4, 5, 6]",
      "[1, 3, 4, 6]",
      "```",
      "",
      "Metodoak zerrendako balioaren *lehenengo* agerraldia kentzen du, kateen `find` funtzioak azpikate baten lehen agerraldia itzultzen duen antzera:",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 1, 2]",
      "",
      "nire_zerrenda.remove(1)",
      "print(nire_zerrenda)",
      "nire_zerrenda.remove(1)",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[2, 1, 2]",
      "[2, 2]",
      "```",
      "",
      "Zehaztutako elementua ez badago zerrendan, `remove` funtzioak errore bat eragiten du. Kateekin bezala, elementu baten presentzia egiaztatu dezakegu `in` eragilearekin:",
      "",
      "```python",
      "nire_zerrenda = [1, 3, 4]",
      "",
      "if 1 in nire_zerrenda:",
      "    print(\"Zerrendak 1 elementua dauka\")",
      "",
      "if 2 in nire_zerrenda:",
      "    print(\"Zerrendak 2 elementua dauka\")",
      "```",
      "",
      "```text",
      "Zerrendak 1 elementua dauka",
      "```"
    ].join("\n")
  }
};

const exerciseAddRemove = {
  type: "exercise",
  exerciseId: "part04-14_addition_and_removal",
  title: {
    ENG: "Addition and removal",
    CAS: "Adición y eliminación",
    EUS: "Gehiketa eta ezabaketa"
  },
  description: {
    ENG: "Write a program that asks the user to choose between adding (d), removing (r) or exiting (x). The program starts with an empty list. 'd' adds the next integer (starting from 1) to the end of the list. 'r' removes the last item. Print the list after each operation.",
    CAS: "Escribe un programa que pida al usuario elegir entre añadir (d), eliminar (r) o salir (x). El programa comienza con una lista vacía. 'd' añade el siguiente entero (comenzando desde 1) al final de la lista. 'r' elimina el último elemento. Imprime la lista después de cada operación.",
    EUS: "Idatzi programa bat erabiltzaileari aukeratzeko eskatzen diona gehitzea (d), kentzea (r) edo irtetea (x). Programa zerrenda huts batekin hasten da. 'd'-k hurrengo zenbaki osoa (1etik hasita) gehitzen du zerrendaren amaieran. 'r'-k azken elementua kentzen du. Inprimatu zerrenda eragiketa bakoitzaren ondoren."
  },
  initialCode: {
    ENG: "# Write your solution here",
    CAS: "# Escribe tu solución aquí",
    EUS: "# Idatzi zure soluzioa hemen"
  },
  testCode: [
    'import unittest',
    'from unittest.mock import patch',
    'class TestAddRemove(unittest.TestCase):',
    '    def test_run(self):',
    '        inputs = ["d", "d", "r", "x"]',
    '        out = run_student_code(inputs=inputs)',
    '        self.assertIn("[1, 2]", out, "Should print [1, 2] | Debería imprimir [1, 2] | [1, 2] inprimatu beharko luke")',
    '        self.assertIn("[1]", out, "Should print [1] after removal | Debería imprimir [1] después de eliminar | [1] inprimatu beharko luke kendu ondoren")'
  ].join("\n")
};

module.exports = { addingItemsContent, exerciseAddItems, removingItemsContent, exerciseAddRemove };
