const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will be able to create lists with different types of items",
      "- You will know how to use lists to organise data",
      "- You will be able to store a matrix as a two-dimensional list"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Podrás crear listas con diferentes tipos de elementos",
      "- Sabrás cómo usar listas para organizar datos",
      "- Podrás almacenar una matriz como una lista bidimensional"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Mota desberdinetako elementuak dituzten zerrendak sortzeko gai izango zara",
      "- Datuak antolatzeko zerrendak nola erabili jakingo duzu",
      "- Matrize bat bi dimentsioko zerrenda gisa gordetzeko gai izango zara"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Lists with different types of data",
      "",
      "In the previous part we mainly handled lists with integer items, but any types of values can be stored in lists. A list of strings could look like this:",
      "",
      "```python",
      "names = [\"Marlyn\", \"Ruth\", \"Paul\"]",
      "print(names)",
      "names.append(\"David\")",
      "print(names)",
      "",
      "print(\"Number of names on the list:\", len(names))",
      "print(\"Names in alphabetical order:\")",
      "names.sort()",
      "for name in names:",
      "  print(name)",
      "```",
      "",
      "```text",
      "['Marlyn', 'Ruth', 'Paul']",
      "['Marlyn', 'Ruth', 'Paul', 'David']",
      "Number of names on the list: 4",
      "Names in alphabetical order:",
      "David",
      "Marlyn",
      "Paul",
      "Ruth",
      "```",
      "",
      "Floating point numbers are also valid list items:",
      "",
      "```python",
      "measurements = [-2.5, 1.1, 7.5, 14.6, 21.0, 19.2]",
      "",
      "for measure in measurements:",
      "    print(measure)",
      "",
      "mean = sum(measurements) / len(measurements)",
      "",
      "print(\"The mean is:\", mean)",
      "```",
      "",
      "```text",
      "-2.5",
      "1.1",
      "7.5",
      "14.6",
      "21.0",
      "19.2",
      "The mean is: 10.15",
      "```",
      "",
      "## Warning: overwriting a parameter and returning too early",
      "",
      "There are a couple of novel sources of bugs we should look at before jumping into the exercises in this part. Let's have a look at a function which tells us whether an integer is found within a list. Both are defined as parameters of the function:",
      "",
      "```python",
      "def number_in_list(numbers: list, number: int):",
      "    for number in numbers:",
      "        if number == number:",
      "            return True",
      "        else:",
      "            return False",
      "```",
      "",
      "This function seems to always return `True`. The reason is that the `for` loop overwrites the value stored in the parameter `number`. Thus the condition in the `if` statement is always true.",
      "",
      "Renaming the parameter solves the problem:",
      "",
      "```python",
      "def number_in_list(numbers: list, searched_number: int):",
      "    for number in numbers:",
      "        if number == searched_number:",
      "            return True",
      "        else:",
      "            return False",
      "```",
      "",
      "Now the condition in the `if` statement looks better. But there is a new problem, since the function still doesn't seem to work correctly. Trying out the following manifests a bug:",
      "",
      "```python",
      "found = number_in_list([1, 2, 3, 4], 3)",
      "print(found)  # prints out False",
      "```",
      "",
      "The issue here is that the function returns too early, without checking all the numbers in the list. In fact, the function takes only the first item in the list, and returns `True` or `False` depending on its value. We cannot know whether a number is *not present* in the list until we have checked all the items in the list. The `return False` command should be placed outside the `for` loop:",
      "",
      "```python",
      "def number_in_list(numbers: list, searched_number: int):",
      "    for number in numbers:",
      "        if number == searched_number:",
      "            return True",
      "",
      "    return False",
      "```"
    ].join("\n"),
    CAS: [
      "## Listas con diferentes tipos de datos",
      "",
      "En la parte anterior manejamos principalmente listas con elementos enteros, pero cualquier tipo de valor puede almacenarse en listas. Una lista de cadenas podría verse así:",
      "",
      "```python",
      "nombres = [\"Marlyn\", \"Ruth\", \"Paul\"]",
      "print(nombres)",
      "nombres.append(\"David\")",
      "print(nombres)",
      "",
      "print(\"Número de nombres en la lista:\", len(nombres))",
      "print(\"Nombres en orden alfabético:\")",
      "nombres.sort()",
      "for nombre in nombres:",
      "  print(nombre)",
      "```",
      "",
      "```text",
      "['Marlyn', 'Ruth', 'Paul']",
      "['Marlyn', 'Ruth', 'Paul', 'David']",
      "Número de nombres en la lista: 4",
      "Nombres en orden alfabético:",
      "David",
      "Marlyn",
      "Paul",
      "Ruth",
      "```",
      "",
      "Los números de punto flotante también son elementos de lista válidos:",
      "",
      "```python",
      "mediciones = [-2.5, 1.1, 7.5, 14.6, 21.0, 19.2]",
      "",
      "for medida in mediciones:",
      "    print(medida)",
      "",
      "media = sum(mediciones) / len(mediciones)",
      "",
      "print(\"La media es:\", media)",
      "```",
      "",
      "```text",
      "-2.5",
      "1.1",
      "7.5",
      "14.6",
      "21.0",
      "19.2",
      "La media es: 10.15",
      "```",
      "",
      "## Advertencia: sobrescribir un parámetro y devolver demasiado pronto",
      "",
      "Hay un par de fuentes novedosas de errores que deberíamos ver antes de saltar a los ejercicios de esta parte. Echemos un vistazo a una función que nos dice si un entero se encuentra dentro de una lista. Ambos se definen como parámetros de la función:",
      "",
      "```python",
      "def numero_en_lista(numeros: list, numero: int):",
      "    for numero in numeros:",
      "        if numero == numero:",
      "            return True",
      "        else:",
      "            return False",
      "```",
      "",
      "Esta función parece devolver siempre `True`. La razón es que el bucle `for` sobrescribe el valor almacenado en el parámetro `numero`. Por lo tanto, la condición en la declaración `if` siempre es verdadera.",
      "",
      "Renombrar el parámetro resuelve el problema:",
      "",
      "```python",
      "def numero_en_lista(numeros: list, numero_buscado: int):",
      "    for numero in numeros:",
      "        if numero == numero_buscado:",
      "            return True",
      "        else:",
      "            return False",
      "```",
      "",
      "Ahora la condición en la declaración `if` se ve mejor. Pero hay un nuevo problema, ya que la función todavía no parece funcionar correctamente. Probar lo siguiente manifiesta un error:",
      "",
      "```python",
      "encontrado = numero_en_lista([1, 2, 3, 4], 3)",
      "print(encontrado)  # imprime False",
      "```",
      "",
      "El problema aquí es que la función devuelve demasiado pronto, sin comprobar todos los números de la lista. De hecho, la función toma solo el primer elemento de la lista y devuelve `True` o `False` dependiendo de su valor. No podemos saber si un número *no está presente* en la lista hasta que hayamos comprobado todos los elementos de la lista. El comando `return False` debe colocarse fuera del bucle `for`:",
      "",
      "```python",
      "def numero_en_lista(numeros: list, numero_buscado: int):",
      "    for numero in numeros:",
      "        if numero == numero_buscado:",
      "            return True",
      "",
      "    return False",
      "```"
    ].join("\n"),
    EUS: [
      "## Zerrendak zerrenden barruan",
      "",
      "Zerrenda bateko elementuak zerrendak izan daitezke beraiek ere:",
      "",
      "```python",
      "nire_zerrenda = [[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "print(nire_zerrenda)",
      "print(nire_zerrenda[1])",
      "print(nire_zerrenda[1][0])",
      "```",
      "```text",
      "[[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "[4, 1]",
      "4",
      "```",
      "",
      "Zergatik lirateke erabilgarriak zerrenden barruko zerrendak?",
      "",
      "Gogoratu zerrendek mota desberdinetako elementuak eduki ditzaketela. Pertsona bati buruzko informazioa zerrenda batean gorde zenezake. Adibidez, bere izena lehen elementu gisa sar zenezake, bere adina bigarren elementu gisa, eta bere altuera metrotan hirugarren elementu gisa:",
      "",
      "```python",
      "[\"Anne\", 12, 1.45]",
      "```",
      "",
      "Pertsonen datu-base bat orduan zerrenda bat izan liteke, eta bere elementuak pertsona bakar bati buruzko informazioa duten zerrendak lirateke:",
      "",
      "```python",
      "pertsonak = [[\"Betty\", 10, 1.37], [\"Peter\", 7, 1.25], [\"Emily\", 32, 1.64], [\"Alan\", 39, 1.78]]",
      "",
      "for pertsona in pertsonak:",
      "  izena = pertsona[0]",
      "  adina = pertsona[1]",
      "  altuera = pertsona[2]",
      "  print(f\"{izena}: {adina} urte, {altuera} metroko altuera\")",
      "```",
      "",
      "```text",
      "Betty: 10 urte, 1.37 metroko altuera",
      "Peter: 7 urte, 1.25 metroko altuera",
      "Emily: 32 urte, 1.64 metroko altuera",
      "Alan: 39 urte, 1.78 metroko altuera",
      "```"
    ].join("\n")
  }
};

const exerciseLongestString = {
  type: "exercise",
  exerciseId: "part05-01_longest_string",
  title: {
    ENG: "The longest string",
    CAS: "La cadena más larga",
    EUS: "Kate luzeena"
  },
  description: {
    ENG: "Please write a function named `longest(strings: list)`, which takes a list of strings as its argument. The function finds and returns the longest string in the list. You may assume there is always a single longest string in the list.",
    CAS: "Por favor escribe una función llamada `longest(strings: list)`, que tome una lista de cadenas como argumento. La función encuentra y devuelve la cadena más larga de la lista. Puedes asumir que siempre hay una única cadena más larga en la lista.",
    EUS: "Mesedez idatzi `longest(strings: list)` izeneko funtzio bat, kate zerrenda bat argumentu gisa hartzen duena. Funtzioak zerrendako kate luzeena aurkitu eta itzultzen du. Suposa dezakezu beti dagoela kate luzeen bakar bat zerrendan."
  },
  initialCode: {
    ENG: [
      "def longest(strings: list):",
      "    # Write your solution here",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    strings = [\"hi\", \"hiya\", \"hello\", \"howdydoody\", \"hi there\"]",
      "    print(longest(strings))"
    ].join("\n"),
    CAS: [
      "def longest(strings: list):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    strings = [\"hi\", \"hiya\", \"hello\", \"howdydoody\", \"hi there\"]",
      "    print(longest(strings))"
    ].join("\n"),
    EUS: [
      "def longest(strings: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    strings = [\"hi\", \"hiya\", \"hello\", \"howdydoody\", \"hi there\"]",
      "    print(longest(strings))"
    ].join("\n")
  },
  testCode: ""
};

const listsWithinListsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Lists within lists",
      "",
      "The items in a list can be lists themselves:",
      "",
      "```python",
      "my_list = [[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "print(my_list)",
      "print(my_list[1])",
      "print(my_list[1][0])",
      "```",
      "```text",
      "[[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "[4, 1]",
      "4",
      "```",
      "",
      "Why would lists within lists be useful?",
      "",
      "Remember that lists can contain items of different types. You could store information about a person in a list. For instance, you could include their name as the first item, their age as the second item, and their height in meters as the third item:",
      "",
      "```python",
      "[\"Anne\", 12, 1.45]",
      "```",
      "",
      "A database of persons could then be a list, whose items would be lists containing information about a single person:",
      "",
      "```python",
      "persons = [[\"Betty\", 10, 1.37], [\"Peter\", 7, 1.25], [\"Emily\", 32, 1.64], [\"Alan\", 39, 1.78]]",
      "",
      "for person in persons:",
      "  name = person[0]",
      "  age = person[1]",
      "  height = person[2]",
      "  print(f\"{name}: age {age} years, height {height} meters\")",
      "```",
      "",
      "```text",
      "Betty: age 10 years, height 1.37 meters",
      "Peter: age 7 years, height 1.25 meters",
      "Emily: age 32 years, height 1.64 meters",
      "Alan: age 39 years, height 1.78 meters",
      "```"
    ].join("\n"),
    CAS: [
      "## Listas dentro de listas",
      "",
      "Los elementos de una lista pueden ser listas a su vez:",
      "",
      "```python",
      "mi_lista = [[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "print(mi_lista)",
      "print(mi_lista[1])",
      "print(mi_lista[1][0])",
      "```",
      "```text",
      "[[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "[4, 1]",
      "4",
      "```",
      "",
      "¿Por qué serían útiles las listas dentro de listas?",
      "",
      "Recuerda que las listas pueden contener elementos de diferentes tipos. Podrías almacenar información sobre una persona en una lista. Por ejemplo, podrías incluir su nombre como el primer elemento, su edad como el segundo elemento y su altura en metros como el tercer elemento:",
      "",
      "```python",
      "[\"Anne\", 12, 1.45]",
      "```",
      "",
      "Una base de datos de personas podría ser entonces una lista, cuyos elementos serían listas que contienen información sobre una sola persona:",
      "",
      "```python",
      "personas = [[\"Betty\", 10, 1.37], [\"Peter\", 7, 1.25], [\"Emily\", 32, 1.64], [\"Alan\", 39, 1.78]]",
      "",
      "for persona in personas:",
      "  nombre = persona[0]",
      "  edad = persona[1]",
      "  altura = persona[2]",
      "  print(f\"{nombre}: edad {edad} años, altura {altura} metros\")",
      "```",
      "",
      "```text",
      "Betty: edad 10 años, altura 1.37 metros",
      "Peter: edad 7 años, altura 1.25 metros",
      "Emily: edad 32 años, altura 1.64 metros",
      "Alan: edad 39 años, altura 1.78 metros",
      "```"
    ].join("\n"),
    EUS: [
      "## Zerrendak zerrenden barruan",
      "",
      "Zerrenda bateko elementuak zerrendak izan daitezke beraiek ere:",
      "",
      "```python",
      "nire_zerrenda = [[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "print(nire_zerrenda)",
      "print(nire_zerrenda[1])",
      "print(nire_zerrenda[1][0])",
      "```",
      "```text",
      "[[5, 2, 3], [4, 1], [2, 2, 5, 1]]",
      "[4, 1]",
      "4",
      "```",
      "",
      "Zergatik lirateke erabilgarriak zerrenden barruko zerrendak?",
      "",
      "Gogoratu zerrendek mota desberdinetako elementuak eduki ditzaketela. Pertsona bati buruzko informazioa zerrenda batean gorde zenezake. Adibidez, bere izena lehen elementu gisa sar zenezake, bere adina bigarren elementu gisa, eta bere altuera metrotan hirugarren elementu gisa:",
      "",
      "```python",
      "[\"Anne\", 12, 1.45]",
      "```",
      "",
      "Pertsonen datu-base bat orduan zerrenda bat izan liteke, eta bere elementuak pertsona bakar bati buruzko informazioa duten zerrendak lirateke:",
      "",
      "```python",
      "pertsonak = [[\"Betty\", 10, 1.37], [\"Peter\", 7, 1.25], [\"Emily\", 32, 1.64], [\"Alan\", 39, 1.78]]",
      "",
      "for pertsona in pertsonak:",
      "  izena = pertsona[0]",
      "  adina = pertsona[1]",
      "  altuera = pertsona[2]",
      "  print(f\"{izena}: {adina} urte, {altuera} metroko altuera\")",
      "```",
      "",
      "```text",
      "Betty: 10 urte, 1.37 metroko altuera",
      "Peter: 7 urte, 1.25 metroko altuera",
      "Emily: 32 urte, 1.64 metroko altuera",
      "Alan: 39 urte, 1.78 metroko altuera",
      "```"
    ].join("\n")
  }
};

const matricesContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Matrices",
      "",
      "A two-dimensional array, or a *matrix*, is also a natural application of a list within a list.",
      "",
      "For example, the following matrix",
      "",
      "![A matrix](images/5_1_1.png)",
      "",
      "could be presented as a two-dimensional list in Python like so:",
      "",
      "```python",
      "my_matrix = [[1, 2, 3], [3, 2, 1], [4, 5, 6]]",
      "```",
      "",
      "Since a matrix is a list containing lists, the individual elements within the matrix can be accessed using consecutive square brackets. The first index refers to the row, and the second to the column. Indexing starts from zero, so for example `my_matrix[0][1]` refers to the second item on the first row.",
      "",
      "```python",
      "my_matrix = [[1, 2, 3], [3, 2, 1], [4, 5, 6]]",
      "",
      "print(my_matrix[0][1])",
      "my_matrix[1][0] = 10",
      "print(my_matrix)",
      "```",
      "",
      "```text",
      "2",
      "[[1, 2, 3], [10, 2, 1], [4, 5, 6]]",
      "```",
      "",
      "Like any other list, the rows of the matrix can be traversed with a `for` loop. The following code prints out each row of the matrix on a separate line:",
      "",
      "```python",
      "my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      "",
      "for row in my_matrix:",
      "    print(row)",
      "```",
      "",
      "```text",
      "[1, 2, 3]",
      "[4, 5, 6]",
      "[7, 8, 9]",
      "```",
      "",
      "Likewise, nested loops can be used to access the individual elements. The following code prints out each element in the matrix on a separate line with the help of two `for` loops:",
      "",
      "```python",
      "my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      "",
      "for row in my_matrix:",
      "    print(\"a new row\")",
      "    for element in row:",
      "        print(element)",
      "```",
      "",
      "```text",
      "a new row",
      "1",
      "2",
      "3",
      "a new row",
      "4",
      "5",
      "6",
      "a new row",
      "7",
      "8",
      "9",
      "```"
    ].join("\n"),
    CAS: [
      "## Matrices",
      "",
      "Un arreglo bidimensional, o una *matriz*, es también una aplicación natural de una lista dentro de una lista.",
      "",
      "Por ejemplo, la siguiente matriz",
      "",
      "![Una matriz](images/5_1_1.png)",
      "",
      "podría presentarse como una lista bidimensional en Python así:",
      "",
      "```python",
      "mi_matriz = [[1, 2, 3], [3, 2, 1], [4, 5, 6]]",
      "```",
      "",
      "Dado que una matriz es una lista que contiene listas, se puede acceder a los elementos individuales dentro de la matriz utilizando corchetes consecutivos. El primer índice se refiere a la fila, y el segundo a la columna. La indexación comienza desde cero, por lo que por ejemplo `mi_matriz[0][1]` se refiere al segundo elemento en la primera fila.",
      "",
      "```python",
      "mi_matriz = [[1, 2, 3], [3, 2, 1], [4, 5, 6]]",
      "",
      "print(mi_matriz[0][1])",
      "mi_matriz[1][0] = 10",
      "print(mi_matriz)",
      "```",
      "",
      "```text",
      "2",
      "[[1, 2, 3], [10, 2, 1], [4, 5, 6]]",
      "```",
      "",
      "Como cualquier otra lista, las filas de la matriz se pueden recorrer con un bucle `for`. El siguiente código imprime cada fila de la matriz en una línea separada:",
      "",
      "```python",
      "mi_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      "",
      "for fila in mi_matriz:",
      "    print(fila)",
      "```",
      "",
      "```text",
      "[1, 2, 3]",
      "[4, 5, 6]",
      "[7, 8, 9]",
      "```",
      "",
      "Asimismo, se pueden usar bucles anidados para acceder a los elementos individuales. El siguiente código imprime cada elemento en la matriz en una línea separada con la ayuda de dos bucles `for`:",
      "",
      "```python",
      "mi_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      "",
      "for fila in mi_matriz:",
      "    print(\"una nueva fila\")",
      "    for elemento in fila:",
      "        print(elemento)",
      "```",
      "",
      "```text",
      "una nueva fila",
      "1",
      "2",
      "3",
      "una nueva fila",
      "4",
      "5",
      "6",
      "una nueva fila",
      "7",
      "8",
      "9",
      "```"
    ].join("\n"),
    EUS: [
      "## Matrizeak",
      "",
      "Bi dimentsioko array bat, edo *matrize* bat, zerrenda barruko zerrenda baten aplikazio naturala ere bada.",
      "",
      "Adibidez, honako matrize hau",
      "",
      "![Matrize bat](images/5_1_1.png)",
      "",
      "bi dimentsioko zerrenda gisa aurkez liteke Python-en honela:",
      "",
      "```python",
      "nire_matrizea = [[1, 2, 3], [3, 2, 1], [4, 5, 6]]",
      "```",
      "",
      "Matrize bat zerrendak dituen zerrenda bat denez, matrize barruko banakako elementuetara ondoz ondoko kortxeteak erabiliz sartu daiteke. Lehenengo indizea errenkadari dagokio, eta bigarrena zutabeari. Indizeak zerotik hasten dira, beraz, adibidez `nire_matrizea[0][1]` lehen errenkadako bigarren elementuari dagokio.",
      "",
      "```python",
      "nire_matrizea = [[1, 2, 3], [3, 2, 1], [4, 5, 6]]",
      "",
      "print(nire_matrizea[0][1])",
      "nire_matrizea[1][0] = 10",
      "print(nire_matrizea)",
      "```",
      "",
      "```text",
      "2",
      "[[1, 2, 3], [10, 2, 1], [4, 5, 6]]",
      "```",
      "",
      "Beste edozein zerrenda bezala, matrizeko errenkadak `for` begizta batekin zeharka daitezke. Hurrengo kodeak matrizeko errenkada bakoitza lerro bereizi batean inprimatzen du:",
      "",
      "```python",
      "nire_matrizea = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      "",
      "for errenkada in nire_matrizea:",
      "    print(errenkada)",
      "```",
      "",
      "```text",
      "[1, 2, 3]",
      "[4, 5, 6]",
      "[7, 8, 9]",
      "```",
      "",
      "Era berean, habiaratutako begiztak erabil daitezke banakako elementuetara sartzeko. Hurrengo kodeak matrizeko elementu bakoitza lerro bereizi batean inprimatzen du bi `for` begiztaren laguntzarekin:",
      "",
      "```python",
      "nire_matrizea = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      "",
      "for errenkada in nire_matrizea:",
      "    print(\"errenkada berri bat\")",
      "    for elementua in errenkada:",
      "        print(elementua)",
      "```",
      "",
      "```text",
      "errenkada berri bat",
      "1",
      "2",
      "3",
      "errenkada berri bat",
      "4",
      "5",
      "6",
      "errenkada berri bat",
      "7",
      "8",
      "9",
      "```"
    ].join("\n")
  }
};

const accessingMatrixContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Accessing items in a matrix",
      "",
      "Accessing a single row within a matrix is simple - just choose the desired row. The following function calculates the sum of the elements on a chosen row:",
      "",
      "```python",
      "def sum_of_row(my_matrix, row_no: int):",
      "    # choose the desired row from within the matrix",
      "    row = my_matrix[row_no]",
      "    row_sum = 0",
      "    for item in row:",
      "        row_sum += item",
      "",
      "    return row_sum",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "my_sum = sum_of_row(m, 1)",
      "print(my_sum) # prints out 33 (which equals 9 + 1 + 12 + 11)",
      "```",
      "",
      "Working with columns within a matrix is slightly more complicated, as the matrix is stored by rows:",
      "",
      "```python",
      "def sum_of_column(my_matrix, column_no: int):",
      "    # go through each row and select the item at the chosen position",
      "    column_sum = 0",
      "    for row in my_matrix:",
      "        column_sum += row[column_no]",
      "",
      "    return column_sum",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "my_sum = sum_of_column(m, 2)",
      "print(my_sum) # prints out 39 (which equals 3 + 12 + 9 + 15)",
      "```",
      "",
      "Changing the value of a single element within the matrix is simple: choose a row within the matrix, and then a column within the row:",
      "",
      "```python",
      "def change_value(my_matrix, row_no: int, column_no: int, new_value: int):",
      "    # choose the desired row",
      "    row = my_matrix[row_no]",
      "    # select the correct item within the row",
      "    row[column_no] = new_value",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "print(m)",
      "change_value(m, 2, 3, 1000)",
      "print(m)",
      "```",
      "",
      "```text",
      "[[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "[[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 1000], [2, 9, 15, 1]]",
      "```",
      "",
      "Notice how above we used the indexes of the row and column to access a chosen element. If we want to change the contents of the matrix, we have to access the elements by their indexes. This means that we can't use a simple `for item in list` loop to traverse the matrix if we want to change the contents of the matrix.",
      "",
      "Instead, we will have to keep track of the indexes of the elements, for example with a `while` loop, or a `for` loop using the `range` function. The following code increases the value of each element in the matrix by one:",
      "",
      "```python",
      "m = [[1,2,3], [4,5,6], [7,8,9]]",
      "",
      "for i in range(len(m)): # using the number of rows in the matrix",
      "    for j in range(len(m[i])): # using the number of items on each row ",
      "        m[i][j] += 1",
      "",
      "print(m)",
      "```",
      "",
      "```text",
      "[[2, 3, 4], [5, 6, 7], [8, 9, 10]]",
      "```"
    ].join("\n"),
    CAS: [
      "## Accediendo a elementos en una matriz",
      "",
      "Acceder a una sola fila dentro de una matriz es simple: simplemente elige la fila deseada. La siguiente función calcula la suma de los elementos en una fila elegida:",
      "",
      "```python",
      "def suma_de_fila(mi_matriz, num_fila: int):",
      "    # elegir la fila deseada dentro de la matriz",
      "    fila = mi_matriz[num_fila]",
      "    suma_fila = 0",
      "    for elemento in fila:",
      "        suma_fila += elemento",
      "",
      "    return suma_fila",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "mi_suma = suma_de_fila(m, 1)",
      "print(mi_suma) # imprime 33 (que es igual a 9 + 1 + 12 + 11)",
      "```",
      "",
      "Trabajar con columnas dentro de una matriz es un poco más complicado, ya que la matriz se almacena por filas:",
      "",
      "```python",
      "def suma_de_columna(mi_matriz, num_columna: int):",
      "    # recorrer cada fila y seleccionar el elemento en la posición elegida",
      "    suma_columna = 0",
      "    for fila in mi_matriz:",
      "        suma_columna += fila[num_columna]",
      "",
      "    return suma_columna",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "mi_suma = suma_de_columna(m, 2)",
      "print(mi_suma) # imprime 39 (que es igual a 3 + 12 + 9 + 15)",
      "```",
      "",
      "Cambiar el valor de un solo elemento dentro de la matriz es simple: elige una fila dentro de la matriz y luego una columna dentro de la fila:",
      "",
      "```python",
      "def cambiar_valor(mi_matriz, num_fila: int, num_columna: int, nuevo_valor: int):",
      "    # elegir la fila deseada",
      "    fila = mi_matriz[num_fila]",
      "    # seleccionar el elemento correcto dentro de la fila",
      "    fila[num_columna] = nuevo_valor",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "print(m)",
      "cambiar_valor(m, 2, 3, 1000)",
      "print(m)",
      "```",
      "",
      "```text",
      "[[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "[[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 1000], [2, 9, 15, 1]]",
      "```",
      "",
      "Observa cómo arriba usamos los índices de la fila y columna para acceder a un elemento elegido. Si queremos cambiar el contenido de la matriz, tenemos que acceder a los elementos por sus índices. Esto significa que no podemos usar un simple bucle `for elemento in lista` para recorrer la matriz si queremos cambiar el contenido de la matriz.",
      "",
      "En su lugar, tendremos que realizar un seguimiento de los índices de los elementos, por ejemplo con un bucle `while`, o un bucle `for` usando la función `range`. El siguiente código aumenta el valor de cada elemento en la matriz en uno:",
      "",
      "```python",
      "m = [[1,2,3], [4,5,6], [7,8,9]]",
      "",
      "for i in range(len(m)): # usando el número de filas en la matriz",
      "    for j in range(len(m[i])): # usando el número de elementos en cada fila ",
      "        m[i][j] += 1",
      "",
      "print(m)",
      "```",
      "",
      "```text",
      "[[2, 3, 4], [5, 6, 7], [8, 9, 10]]",
      "```"
    ].join("\n"),
    EUS: [
      "## Matrize bateko elementuetara sartzen",
      "",
      "Matrize baten barruko errenkada bakar batera sartzea erraza da - aukeratu nahi duzun errenkada. Hurrengo funtzioak aukeratutako errenkada bateko elementuen batura kalkulatzen du:",
      "",
      "```python",
      "def errenkada_batura(nire_matrizea, err_zenb: int):",
      "    # aukeratu nahi duzun errenkada matrize barrutik",
      "    errenkada = nire_matrizea[err_zenb]",
      "    err_batura = 0",
      "    for elementua in errenkada:",
      "        err_batura += elementua",
      "",
      "    return err_batura",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "nire_batura = errenkada_batura(m, 1)",
      "print(nire_batura) # 33 inprimatzen du (berdin 9 + 1 + 12 + 11)",
      "```",
      "",
      "Matrize baten barruko zutabeekin lan egitea apur bat konplikatuagoa da, matrizea errenkadaka gordetzen baita:",
      "",
      "```python",
      "def zutabe_batura(nire_matrizea, zut_zenb: int):",
      "    # zeharkatu errenkada bakoitza eta aukeratu elementua hautatutako posizioan",
      "    zut_batura = 0",
      "    for errenkada in nire_matrizea:",
      "        zut_batura += errenkada[zut_zenb]",
      "",
      "    return zut_batura",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "nire_batura = zutabe_batura(m, 2)",
      "print(nire_batura) # 39 inprimatzen du (berdin 3 + 12 + 9 + 15)",
      "```",
      "",
      "Matrize barruko elementu bakar baten balioa aldatzea erraza da: aukeratu errenkada bat matrizearen barruan, eta gero zutabe bat errenkadaren barruan:",
      "",
      "```python",
      "def balioa_aldatu(nire_matrizea, err_zenb: int, zut_zenb: int, balio_berria: int):",
      "    # aukeratu nahi duzun errenkada",
      "    errenkada = nire_matrizea[err_zenb]",
      "    # aukeratu elementu zuzena errenkadaren barruan",
      "    errenkada[zut_zenb] = balio_berria",
      "",
      "m = [[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "",
      "print(m)",
      "balioa_aldatu(m, 2, 3, 1000)",
      "print(m)",
      "```",
      "",
      "```text",
      "[[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 5], [2, 9, 15, 1]]",
      "[[4, 2, 3, 2], [9, 1, 12, 11], [7, 8, 9, 1000], [2, 9, 15, 1]]",
      "```",
      "",
      "Ohartu nola goian errenkada eta zutabearen indizeak erabili genituen aukeratutako elementu batera sartzeko. Matrizearen edukia aldatu nahi badugu, elementuetara haien indizeen bidez sartu behar dugu. Horrek esan nahi du ezin dugula erabili `for elementua in zerrenda` begizta sinple bat matrizea zeharkatzeko, matrizearen edukia aldatu nahi badugu.",
      "",
      "Horren ordez, elementuen indizeen jarraipena egin beharko dugu, adibidez `while` begizta batekin, edo `for` begizta batekin `range` funtzioa erabiliz. Hurrengo kodeak matrizeko elementu bakoitzaren balioa batean handitzen du:",
      "",
      "```python",
      "m = [[1,2,3], [4,5,6], [7,8,9]]",
      "",
      "for i in range(len(m)): # matrizeko errenkada kopurua erabiliz",
      "    for j in range(len(m[i])): # errenkada bakoitzeko elementu kopurua erabiliz",
      "        m[i][j] += 1",
      "",
      "print(m)",
      "```",
      "",
      "```text",
      "[[2, 3, 4], [5, 6, 7], [8, 9, 10]]",
      "```"
    ].join("\n")
  }
};

const exerciseMatchingElements = {
  type: "exercise",
  exerciseId: "part05-02_number_of_matching_elements",
  title: {
    ENG: "Number of matching elements",
    CAS: "Número de elementos coincidentes",
    EUS: "Bat datozen elementuen kopurua"
  },
  description: {
    ENG: "Please write a function named `count_matching_elements(my_matrix: list, element: int)`, which takes a two-dimensional array of integers and a single integer value as its arguments. The function then counts how many elements within the matrix match the argument value.",
    CAS: "Por favor escribe una función llamada `count_matching_elements(my_matrix: list, element: int)`, que tome una matriz bidimensional de enteros y un valor entero único como sus argumentos. La función cuenta cuántos elementos dentro de la matriz coinciden con el valor del argumento.",
    EUS: "Mesedez idatzi `count_matching_elements(my_matrix: list, element: int)` izeneko funtzio bat, osoko zenbakien bi dimentsioko array bat eta osoko balio bakar bat argumentu gisa hartzen dituena. Funtzioak matrizearen barruan argumentuaren balioarekin bat datozen elementu kopurua zenbatzen du."
  },
  initialCode: {
    ENG: [
      "def count_matching_elements(my_matrix: list, element: int):",
      "    # Write your solution here",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    m = [[1, 2, 1], [0, 3, 4], [1, 0, 0]]",
      "    print(count_matching_elements(m, 1))"
    ].join("\n"),
    CAS: [
      "def count_matching_elements(my_matrix: list, element: int):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    m = [[1, 2, 1], [0, 3, 4], [1, 0, 0]]",
      "    print(count_matching_elements(m, 1))"
    ].join("\n"),
    EUS: [
      "def count_matching_elements(my_matrix: list, element: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    m = [[1, 2, 1], [0, 3, 4], [1, 0, 0]]",
      "    print(count_matching_elements(m, 1))"
    ].join("\n")
  },
  testCode: ""
};

const exerciseGo = {
  type: "exercise",
  exerciseId: "part05-03_go",
  title: {
    ENG: "Go",
    CAS: "Go",
    EUS: "Go"
  },
  description: {
    ENG: "Please write a function named `who_won(game_board: list)`, which takes a two-dimensional array as its argument. The array consists of integer values, where 0 is empty, 1 is player 1, and 2 is player 2. The function should return 1 if player 1 has more pieces, 2 if player 2 has more, and 0 if it's a tie.",
    CAS: "Por favor escribe una función llamada `who_won(game_board: list)`, que tome una matriz bidimensional como argumento. La matriz consta de valores enteros, donde 0 es vacío, 1 es jugador 1 y 2 es jugador 2. La función debe devolver 1 si el jugador 1 tiene más piezas, 2 si el jugador 2 tiene más, y 0 si es un empate.",
    EUS: "Mesedez idatzi `who_won(game_board: list)` izeneko funtzio bat, bi dimentsioko array bat argumentu gisa hartzen duena. Arraya osoko balioez osatuta dago, non 0 hutsik den, 1 jokalaria 1 den, eta 2 jokalaria 2 den. Funtzioak 1 itzuli behar du 1. jokalariak pieza gehiago baditu, 2 itzuli 2. jokalariak gehiago baditu, eta 0 berdinketa bada."
  },
  initialCode: {
    ENG: [
      "def who_won(game_board: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def who_won(game_board: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def who_won(game_board: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseSudokuRow = {
  type: "exercise",
  exerciseId: "part05-04_sudoku_row",
  title: {
    ENG: "Sudoku: check row",
    CAS: "Sudoku: comprobar fila",
    EUS: "Sudoku: errenkada egiaztatu"
  },
  description: {
    ENG: "Please write a function named `row_correct(sudoku: list, row_no: int)`, which takes a two-dimensional array representing a sudoku grid, and an integer referring to a single row. The function should return `True` or `False`, depending on whether the row is filled in correctly (each number 1-9 at most once).",
    CAS: "Por favor escribe una función llamada `row_correct(sudoku: list, row_no: int)`, que tome una matriz bidimensional representando una cuadrícula de sudoku, y un entero refiriéndose a una sola fila. La función debe devolver `True` o `False`, dependiendo de si la fila está rellenada correctamente (cada número 1-9 como máximo una vez).",
    EUS: "Mesedez idatzi `row_correct(sudoku: list, row_no: int)` izeneko funtzio bat, sudoku sareta bat adierazten duen bi dimentsioko array bat eta errenkada bakar bati erreferentzia egiten dion osoko zenbaki bat hartzen dituena. Funtzioak `True` edo `False` itzuli behar du, errenkada behar bezala beteta dagoen ala ez kontuan hartuta (1-9 zenbaki bakoitza gehienez behin)."
  },
  initialCode: {
    ENG: [
      "def row_correct(sudoku: list, row_no: int):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def row_correct(sudoku: list, row_no: int):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def row_correct(sudoku: list, row_no: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseSudokuColumn = {
  type: "exercise",
  exerciseId: "part05-05_sudoku_column",
  title: {
    ENG: "Sudoku: check column",
    CAS: "Sudoku: comprobar columna",
    EUS: "Sudoku: zutabea egiaztatu"
  },
  description: {
    ENG: "Please write a function named `column_correct(sudoku: list, column_no: int)`, which takes a two-dimensional array representing a sudoku grid, and an integer referring to a single column. The function should return `True` or `False`, depending on whether the column is filled in correctly.",
    CAS: "Por favor escribe una función llamada `column_correct(sudoku: list, column_no: int)`, que tome una matriz bidimensional representando una cuadrícula de sudoku, y un entero refiriéndose a una sola columna. La función debe devolver `True` o `False`, dependiendo de si la columna está rellenada correctamente.",
    EUS: "Mesedez idatzi `column_correct(sudoku: list, column_no: int)` izeneko funtzio bat, sudoku sareta bat adierazten duen bi dimentsioko array bat eta zutabe bakar bati erreferentzia egiten dion osoko zenbaki bat hartzen dituena. Funtzioak `True` edo `False` itzuli behar du, zutabea behar bezala beteta dagoen ala ez kontuan hartuta."
  },
  initialCode: {
    ENG: [
      "def column_correct(sudoku: list, column_no: int):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def column_correct(sudoku: list, column_no: int):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def column_correct(sudoku: list, column_no: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseSudokuBlock = {
  type: "exercise",
  exerciseId: "part05-06_sudoku_block",
  title: {
    ENG: "Sudoku: check block",
    CAS: "Sudoku: comprobar bloque",
    EUS: "Sudoku: blokea egiaztatu"
  },
  description: {
    ENG: "Please write a function named `block_correct(sudoku: list, row_no: int, column_no: int)`, which takes a two-dimensional array representing a sudoku grid, and two integers referring to the row and column indexes of a single square. The function should return `True` or `False` depending on whether the 3 by 3 block to the right and down from the given indexes is filled in correctly.",
    CAS: "Por favor escribe una función llamada `block_correct(sudoku: list, row_no: int, column_no: int)`, que tome una matriz bidimensional representando una cuadrícula de sudoku, y dos enteros refiriéndose a los índices de fila y columna de un solo cuadrado. La función debe devolver `True` o `False` dependiendo de si el bloque de 3 por 3 a la derecha y abajo de los índices dados está rellenado correctamente.",
    EUS: "Mesedez idatzi `block_correct(sudoku: list, row_no: int, column_no: int)` izeneko funtzio bat, sudoku sareta bat adierazten duen bi dimentsioko array bat eta karratu bakar baten errenkada eta zutabe indizeei erreferentzia egiten dieten bi osoko zenbaki hartzen dituena. Funtzioak `True` edo `False` itzuli behar du, emandako indizeetatik eskuinera eta behera dagoen 3 bider 3 blokea behar bezala beteta dagoen ala ez kontuan hartuta."
  },
  initialCode: {
    ENG: [
      "def block_correct(sudoku: list, row_no: int, column_no: int):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def block_correct(sudoku: list, row_no: int, column_no: int):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def block_correct(sudoku: list, row_no: int, column_no: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseSudokuGrid = {
  type: "exercise",
  exerciseId: "part05-07_sudoku_grid",
  title: {
    ENG: "Sudoku: check grid",
    CAS: "Sudoku: comprobar cuadrícula",
    EUS: "Sudoku: sareta egiaztatu"
  },
  description: {
    ENG: "Please write a function named `sudoku_grid_correct(sudoku: list)`, which takes a two-dimensional array representing a sudoku grid as its argument. The function should use the functions from the three previous exercises to determine whether the complete sudoku grid is filled in correctly.",
    CAS: "Por favor escribe una función llamada `sudoku_grid_correct(sudoku: list)`, que tome una matriz bidimensional representando una cuadrícula de sudoku como su argumento. La función debe usar las funciones de los tres ejercicios anteriores para determinar si la cuadrícula de sudoku completa está rellenada correctamente.",
    EUS: "Mesedez idatzi `sudoku_grid_correct(sudoku: list)` izeneko funtzio bat, sudoku sareta bat adierazten duen bi dimentsioko array bat argumentu gisa hartzen duena. Funtzioak aurreko hiru ariketetako funtzioak erabili behar ditu sudoku sareta osoa behar bezala beteta dagoen zehazteko."
  },
  initialCode: {
    ENG: [
      "def sudoku_grid_correct(sudoku: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def sudoku_grid_correct(sudoku: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def sudoku_grid_correct(sudoku: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const section1 = {
  id: "part5-1",
  title: {
    ENG: "More lists",
    CAS: "Más listas",
    EUS: "Zerrenda gehiago"
  },
  blocks: [
    learningObjectives,
    introContent,
    exerciseLongestString,
    listsWithinListsContent,
    matricesContent,
    accessingMatrixContent,
    exerciseMatchingElements,
    exerciseGo,
    exerciseSudokuRow,
    exerciseSudokuColumn,
    exerciseSudokuBlock,
    exerciseSudokuGrid
  ]
};

const outputPath = path.join(__dirname, '../src/data/part5/section1.json');
fs.writeFileSync(outputPath, JSON.stringify(section1, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);
