const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "- You will know what lists are in Python",
      "- You will be able access a specified item within a list",
      "- You will know how to add items to a list, and how to remove them",
      "- You will be familiar with built-in list functions and methods"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "- Sabrás qué son las listas en Python",
      "- Podrás acceder a un elemento específico dentro de una lista",
      "- Sabrás cómo añadir elementos a una lista y cómo eliminarlos",
      "- Te familiarizarás con las funciones y métodos de lista incorporados"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "- Jakingo duzu zer diren zerrendak Python-en",
      "- Zerrenda bateko elementu zehatz batera sartzeko gai izango zara",
      "- Jakingo duzu nola gehitu elementuak zerrenda batera, eta nola kendu",
      "- Zerrenda-funtzio eta metodo integratuak ezagutuko dituzu"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "Thus far in our programs we have stored data with variables, each bit of data usually having its own named variable. This obviously has some limitations, as it can get cumbersome to define separate variables for everything when there is a lot of data to handle.",
      "",
      "A Python *list* is a collection of values which is accessed via a single variable name. The contents of the list are written within square brackets. The values contained in the list are called *items*, or sometimes *elements*.",
      "",
      "The following command creates a new, empty list",
      "",
      "```python",
      "my_list = []",
      "```",
      "",
      "whereas this command creates a list with five items in it:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "```",
      "",
      "## Accessing items in a list",
      "",
      "A single list item can be accessed just like a single character in a string is accessed, with square brackets:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "",
      "print(my_list[0])",
      "print(my_list[1])",
      "print(my_list[3])",
      "",
      "print(\"The sum of the first two items:\", my_list[0] + my_list[1])",
      "```",
      "",
      "```text",
      "7",
      "2",
      "5",
      "The sum of the first two items: 9",
      "```",
      "",
      "The entire contents of the list can also be printed out:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "```",
      "",
      "Unlike strings, lists are mutable, which means their contents can change. You can assign a new value to an item within a list, just like you can assign a new value to a variable:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "print(my_list)",
      "my_list[1] = 3",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "[7, 3, 2, 5, 2]",
      "```",
      "",
      "The function `len` gives you the number of items in a list:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "print(len(my_list))",
      "```",
      "",
      "```text",
      "5",
      "```"
    ].join("\n"),
    CAS: [
      "Hasta ahora en nuestros programas hemos almacenado datos con variables, donde cada dato suele tener su propia variable con nombre. Esto obviamente tiene algunas limitaciones, ya que puede resultar engorroso definir variables separadas para todo cuando hay muchos datos que manejar.",
      "",
      "Una *lista* de Python es una colección de valores a los que se accede a través de un único nombre de variable. El contenido de la lista se escribe entre corchetes. Los valores contenidos en la lista se denominan *elementos*.",
      "",
      "El siguiente comando crea una lista nueva y vacía",
      "",
      "```python",
      "mi_lista = []",
      "```",
      "",
      "mientras que este comando crea una lista con cinco elementos en ella:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "```",
      "",
      "## Accediendo a elementos en una lista",
      "",
      "Se puede acceder a un solo elemento de la lista tal como se accede a un solo carácter en una cadena, con corchetes:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "",
      "print(mi_lista[0])",
      "print(mi_lista[1])",
      "print(mi_lista[3])",
      "",
      "print(\"La suma de los dos primeros elementos:\", mi_lista[0] + mi_lista[1])",
      "```",
      "",
      "```text",
      "7",
      "2",
      "5",
      "La suma de los dos primeros elementos: 9",
      "```",
      "",
      "El contenido completo de la lista también se puede imprimir:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "```",
      "",
      "A diferencia de las cadenas, las listas son mutables, lo que significa que su contenido puede cambiar. Puedes asignar un nuevo valor a un elemento dentro de una lista, al igual que puedes asignar un nuevo valor a una variable:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "print(mi_lista)",
      "mi_lista[1] = 3",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "[7, 3, 2, 5, 2]",
      "```",
      "",
      "La función `len` te da el número de elementos en una lista:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "print(len(mi_lista))",
      "```",
      "",
      "```text",
      "5",
      "```"
    ].join("\n"),
    EUS: [
      "Orain arte gure programetan datuak aldagaiekin gorde ditugu, datu bakoitzak normalean bere izeneko aldagaia duelarik. Honek, jakina, muga batzuk ditu; izan ere, maneiatzeko datu asko daudenean astuna izan daiteke denatarako aldagai bereiziak definitzea.",
      "",
      "Python *zerrenda* aldagai-izen bakar baten bidez atzitzen den balio bilduma bat da. Zerrendaren edukia kortxete artean idazten da. Zerrendan dauden balioei *elementu* deitzen zaie.",
      "",
      "Hurrengo komandoak zerrenda berri eta huts bat sortzen du",
      "",
      "```python",
      "nire_zerrenda = []",
      "```",
      "",
      "komando honek, berriz, bost elementu dituen zerrenda bat sortzen du:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "```",
      "",
      "## Zerrenda bateko elementuak atzitzen",
      "",
      "Zerrendako elementu bakar batera sartu daiteke kate bateko karaktere bakar batera sartzen den modu berean, kortxeteekin:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "",
      "print(nire_zerrenda[0])",
      "print(nire_zerrenda[1])",
      "print(nire_zerrenda[3])",
      "",
      "print(\"Lehen bi elementuen batura:\", nire_zerrenda[0] + nire_zerrenda[1])",
      "```",
      "",
      "```text",
      "7",
      "2",
      "5",
      "Lehen bi elementuen batura: 9",
      "```",
      "",
      "Zerrendaren eduki osoa ere inprimatu daiteke:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "```",
      "",
      "Kateak ez bezala, zerrendak aldagarriak dira, hau da, haien edukia alda daiteke. Balio berri bat esleitu diezaiokezu zerrenda bateko elementu bati, aldagai bati balio berria esleitzen diozun bezala:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "print(nire_zerrenda)",
      "nire_zerrenda[1] = 3",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "[7, 3, 2, 5, 2]",
      "```",
      "",
      "`len` funtzioak zerrenda bateko elementu kopurua ematen dizu:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "print(len(nire_zerrenda))",
      "```",
      "",
      "```text",
      "5",
      "```"
    ].join("\n")
  }
};

const exerciseChangeValue = {
  type: "exercise",
  exerciseId: "part04-12_change_value_of_item",
  title: {
    ENG: "Change the value of an item",
    CAS: "Cambiar el valor de un elemento",
    EUS: "Elementu baten balioa aldatu"
  },
  description: {
    ENG: "Write a program that initializes a list with the values `[1, 2, 3, 4, 5]`. Then, ask the user for an index and a new value, replace the item at that index, and print the list. Continue until the user inputs -1 for the index.",
    CAS: "Escribe un programa que inicialice una lista con los valores `[1, 2, 3, 4, 5]`. Luego, pide al usuario un índice y un nuevo valor, reemplaza el elemento en ese índice e imprime la lista. Continúa hasta que el usuario introduzca -1 para el índice.",
    EUS: "Idatzi programa bat zerrenda bat hasieratzen duena `[1, 2, 3, 4, 5]` balioekin. Ondoren, eskatu erabiltzaileari indize bat eta balio berri bat, ordezkatu indize horretako elementua eta inprimatu zerrenda. Jarraitu erabiltzaileak indizean -1 sartu arte."
  },
  initialCode: {
    ENG: [
      "# Write your solution here",
      "my_list = [1, 2, 3, 4, 5]"
    ].join("\n"),
    CAS: [
      "# Escribe tu solución aquí",
      "my_list = [1, 2, 3, 4, 5]"
    ].join("\n"),
    EUS: [
      "# Idatzi zure soluzioa hemen",
      "my_list = [1, 2, 3, 4, 5]"
    ].join("\n")
  },
  testCode: [
    'import unittest',
    'from unittest.mock import patch',
    'class TestChangeItem(unittest.TestCase):',
    '    def test_run(self):',
    '        inputs = ["0", "10", "2", "20", "-1"]',
    '        out = run_student_code(inputs=inputs)',
    '        self.assertIn("[10, 2, 3, 4, 5]", out, "Should print first change | Debería imprimir el primer cambio | Lehen aldaketa inprimatu beharko luke")',
    '        self.assertIn("[10, 2, 20, 4, 5]", out, "Should print second change | Debería imprimir el segundo cambio | Bigarren aldaketa inprimatu beharko luke")'
  ].join("\n")
};

module.exports = { learningObjectives, introContent, exerciseChangeValue };
