const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will know what is meant by a reference to a variable",
      "- You will understand that there can be multiple references to the same object",
      "- You will be able to use lists as parameters in functions",
      "- You will know what is meant by a side effect of a function"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Sabrás qué se entiende por una referencia a una variable",
      "- Entenderás que puede haber múltiples referencias al mismo objeto",
      "- Podrás usar listas como parámetros en funciones",
      "- Sabrás qué se entiende por un efecto secundario de una función"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Aldagai baten erreferentziarekin zer esan nahi den jakingo duzu",
      "- Objektu berberera erreferentzia anitz egon daitezkeela ulertuko duzu",
      "- Funtzioetan zerrendak parametro gisa erabiltzeko gai izango zara",
      "- Funtzio baten albo-efektuarekin zer esan nahi den jakingo duzu"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "Thus far we have thought of a variable as a sort of a \"box\" which contains the value of the variable. Technically this is not true in Python. What is stored in a variable is not the value per se, but a *reference* to the *object* which is the actual value of the variable. The object can be e.g. a number, a string or a list.",
      "",
      "In practice, this means that the value of the variable *is not stored* in the variable itself. Instead, there is information about the location in computer memory where the value can be found.",
      "",
      "A reference is often represented by an arrow from the variable to the actual value in memory:",
      "",
      "![Reference visualization](images/5_2_1.png)",
      "",
      "So, a reference tells us where the value can be found. The function `id` can be used to find out the exact location the variable points to:",
      "",
      "```python",
      "a = [1, 2, 3]",
      "print(id(a))",
      "b = \"This is a reference, too\"",
      "print(id(b))",
      "```",
      "",
      "```text",
      "4538357072",
      "4537788912",
      "```",
      "",
      "The reference, or the ID of the variable, is an integer, which can be thought of as the address in computer memory where the value of the variable is stored. If you execute the above code on your own computer, the result will likely be different, as your variables will point to different locations - the references will be different.",
      "",
      "It is good to keep in mind that *almost everything is a reference* in Python, but all this is rarely relevant to everyday programming tasks. So let's get back to more practical matters.",
      "",
      "## Multiple references to the same list",
      "",
      "What actually happens when you assign a list variable to a new variable - is the list copied over?",
      "",
      "```python",
      "a = [1, 2, 3]",
      "b = a",
      "b[0] = 10",
      "```",
      "",
      "The assignment `b = a` copies the value stored in variable `a` to the variable `b`. However, the value stored in `a` is not the list *itself*, but a *reference* to the list.",
      "",
      "So, the assignment `b = a` copies the reference. As a result there are now two references to the same memory location containing the list.",
      "",
      "![Multiple references](images/5_2_5.png)",
      "",
      "The list can be accessed through either of the two references:",
      "",
      "```python",
      "list1 = [1, 2, 3, 4]",
      "list2 = list1",
      "",
      "list1[0] = 10",
      "list2[1] = 20",
      "",
      "print(list1)",
      "print(list2)",
      "```",
      "",
      "```text",
      "[10, 20, 3, 4]",
      "[10, 20, 3, 4]",
      "```",
      "",
      "If there is more than one reference to the same list, any one of the references can be used to access the list. On the other hand, a change made through any one of the references affects also the other references, as their target is the same.",
      "",
      "## Copying a list",
      "",
      "If you want to create an actual separate copy of a list, you can create a new list and add each item from the original list in turn:",
      "",
      "```python",
      "my_list = [1, 2, 3, 3, 5]",
      "",
      "new_list = []",
      "for item in my_list:",
      "    new_list.append(item)",
      "",
      "new_list[0] = 10",
      "new_list.append(6)",
      "print(\"the original:\", my_list)",
      "print(\"the copy:\", new_list)",
      "```",
      "",
      "```text",
      "my_list [1, 2, 3, 3, 5]",
      "new_list [10, 2, 3, 3, 5, 6]",
      "```",
      "",
      "An easier way to copy a list is the bracket operator `[]`, which we used for slices previously. The notation `[:]` selects all items in the collection. As a side effect, it creates a copy of the list:",
      "",
      "```python",
      "my_list = [1,2,3,4]",
      "new_list = my_list[:]",
      "",
      "my_list[0] = 10",
      "new_list[1] = 20",
      "",
      "print(my_list)",
      "print(new_list)",
      "```",
      "",
      "```text",
      "[10, 2, 3, 4]",
      "[1, 20, 3, 4]",
      "```"
    ].join("\n"),
    CAS: [
      "Hasta ahora hemos pensado en una variable como una especie de \"caja\" que contiene el valor de la variable. Técnicamente esto no es cierto en Python. Lo que se almacena en una variable no es el valor en sí, sino una *referencia* al *objeto* que es el valor real de la variable. El objeto puede ser, por ejemplo, un número, una cadena o una lista.",
      "",
      "En la práctica, esto significa que el valor de la variable *no se almacena* en la variable misma. En cambio, hay información sobre la ubicación en la memoria del ordenador donde se puede encontrar el valor.",
      "",
      "Una referencia a menudo se representa mediante una flecha desde la variable hasta el valor real en la memoria:",
      "",
      "![Visualización de referencia](images/5_2_1.png)",
      "",
      "Entonces, una referencia nos dice dónde se puede encontrar el valor. La función `id` se puede utilizar para averiguar la ubicación exacta a la que apunta la variable:",
      "",
      "```python",
      "a = [1, 2, 3]",
      "print(id(a))",
      "b = \"Esta es una referencia, también\"",
      "print(id(b))",
      "```",
      "",
      "```text",
      "4538357072",
      "4537788912",
      "```",
      "",
      "La referencia, o el ID de la variable, es un número entero, que se puede considerar como la dirección en la memoria del ordenador donde se almacena el valor de la variable. Si ejecutas el código anterior en tu propio ordenador, es probable que el resultado sea diferente, ya que tus variables apuntarán a ubicaciones diferentes; las referencias serán diferentes.",
      "",
      "Es bueno tener en cuenta que *casi todo es una referencia* en Python, pero todo esto rara vez es relevante para las tareas de programación cotidianas. Así que volvamos a asuntos más prácticos.",
      "",
      "## Múltiples referencias a la misma lista",
      "",
      "¿Qué sucede realmente cuando asignas una variable de lista a una nueva variable? ¿Se copia la lista?",
      "",
      "```python",
      "a = [1, 2, 3]",
      "b = a",
      "b[0] = 10",
      "```",
      "",
      "La asignación `b = a` copia el valor almacenado en la variable `a` a la variable `b`. Sin embargo, el valor almacenado en `a` no es la lista *en sí misma*, sino una *referencia* a la lista.",
      "",
      "Así, la asignación `b = a` copia la referencia. Como resultado, ahora hay dos referencias a la misma ubicación de memoria que contiene la lista.",
      "",
      "![Múltiples referencias](images/5_2_5.png)",
      "",
      "Se puede acceder a la lista a través de cualquiera de las dos referencias:",
      "",
      "```python",
      "lista1 = [1, 2, 3, 4]",
      "lista2 = lista1",
      "",
      "lista1[0] = 10",
      "lista2[1] = 20",
      "",
      "print(lista1)",
      "print(lista2)",
      "```",
      "",
      "```text",
      "[10, 20, 3, 4]",
      "[10, 20, 3, 4]",
      "```",
      "",
      "Si hay más de una referencia a la misma lista, cualquiera de las referencias se puede usar para acceder a la lista. Por otro lado, un cambio realizado a través de cualquiera de las referencias afecta también a las otras referencias, ya que su objetivo es el mismo.",
      "",
      "## Copiar una lista",
      "",
      "Si deseas crear una copia separada real de una lista, puedes crear una nueva lista y agregar cada elemento de la lista original por turno:",
      "",
      "```python",
      "mi_lista = [1, 2, 3, 3, 5]",
      "",
      "nueva_lista = []",
      "for elemento in mi_lista:",
      "    nueva_lista.append(elemento)",
      "",
      "nueva_lista[0] = 10",
      "nueva_lista.append(6)",
      "print(\"la original:\", mi_lista)",
      "print(\"la copia:\", nueva_lista)",
      "```",
      "",
      "```text",
      "mi_lista [1, 2, 3, 3, 5]",
      "nueva_lista [10, 2, 3, 3, 5, 6]",
      "```",
      "",
      "Una forma más fácil de copiar una lista es el operador de corchetes `[]`, que usamos para rebanadas anteriormente. La notación `[:]` selecciona todos los elementos de la colección. Como efecto secundario, crea una copia de la lista:",
      "",
      "```python",
      "mi_lista = [1,2,3,4]",
      "nueva_lista = mi_lista[:]",
      "",
      "mi_lista[0] = 10",
      "nueva_lista[1] = 20",
      "",
      "print(mi_lista)",
      "print(nueva_lista)",
      "```",
      "",
      "```text",
      "[10, 2, 3, 4]",
      "[1, 20, 3, 4]",
      "```"
    ].join("\n"),
    EUS: [
      "Orain arte aldagai bat aldagaiaren balioa duen \"kutxa\" moduko bat bezala pentsatu dugu. Teknikoki hau ez da egia Python-en. Aldagai batean gordetzen dena ez da balioa berez, aldagaiaren benetako balioa den *objektuaren* *erreferentzia* bat baizik. Objektua izan daiteke adibidez zenbaki bat, kate bat edo zerrenda bat.",
      "",
      "Praktikan, honek esan nahi du aldagaiaren balioa *ez dela gordetzen* aldagaian bertan. Horren ordez, ordenagailuaren memorian balioa non aurki daitekeenari buruzko informazioa dago.",
      "",
      "Erreferentzia bat sarritan aldagaitik memoriako benetako baliora doan gezi baten bidez irudikatzen da:",
      "",
      "![Erreferentziaren bistaratzea](images/5_2_1.png)",
      "",
      "Beraz, erreferentzia batek balioa non aurki daitekeen esaten digu. `id` funtzioa erabil daiteke aldagaiak seinalatzen duen kokapen zehatza aurkitzeko:",
      "",
      "```python",
      "a = [1, 2, 3]",
      "print(id(a))",
      "b = \"Hau erreferentzia bat da, ere bai\"",
      "print(id(b))",
      "```",
      "",
      "```text",
      "4538357072",
      "4537788912",
      "```",
      "",
      "Erreferentzia, edo aldagaiaren IDa, zenbaki oso bat da, ordenagailuaren memorian aldagaiaren balioa gordetzen den helbide gisa pentsa daitekeena. Goiko kodea zure ordenagailuan exekutatzen baduzu, emaitza ziurrenik desberdina izango da, zure aldagaiek kokapen desberdinetara seinalatuko baitute - erreferentziak desberdinak izango dira.",
      "",
      "Komeni da gogoan izatea *ia dena erreferentzia bat dela* Python-en, baina hori guztia gutxitan da garrantzitsua eguneroko programazio-zereginetan. Beraz, itzul gaitezen gai praktikoagoetara.",
      "",
      "## Erreferentzia anitz zerrenda berdinera",
      "",
      "Zer gertatzen da benetan zerrenda aldagai bat aldagai berri bati esleitzen diozunean - zerrenda kopiatzen da?",
      "",
      "```python",
      "a = [1, 2, 3]",
      "b = a",
      "b[0] = 10",
      "```",
      "",
      "`b = a` esleipenak `a` aldagaian gordetako balioa `b` aldagaian kopiatzen du. Hala ere, `a`-n gordetako balioa ez da zerrenda *bera*, zerrendaren *erreferentzia* bat baizik.",
      "",
      "Beraz, `b = a` esleipenak erreferentzia kopiatzen du. Ondorioz, orain zerrenda duen memoria kokapen berdinera bi erreferentzia daude.",
      "",
      "![Erreferentzia anitz](images/5_2_5.png)",
      "",
      "Zerrendara bi erreferentzietako edozeinen bidez sar daiteke:",
      "",
      "```python",
      "zerrenda1 = [1, 2, 3, 4]",
      "zerrenda2 = zerrenda1",
      "",
      "zerrenda1[0] = 10",
      "zerrenda2[1] = 20",
      "",
      "print(zerrenda1)",
      "print(zerrenda2)",
      "```",
      "",
      "```text",
      "[10, 20, 3, 4]",
      "[10, 20, 3, 4]",
      "```",
      "",
      "Zerrenda berdinera erreferentzia bat baino gehiago badago, erreferentzietako edozein erabil daiteke zerrendara sartzeko. Bestalde, erreferentzietako edozeinen bidez egindako aldaketak beste erreferentziei ere eragiten die, haien helburua berdina baita.",
      "",
      "## Zerrenda bat kopiatzea",
      "",
      "Zerrenda baten benetako kopia bereizi bat sortu nahi baduzu, zerrenda berri bat sor dezakezu eta jatorrizko zerrendako elementu bakoitza gehitu txandaka:",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 3, 3, 5]",
      "",
      "zerrenda_berria = []",
      "for elementua in nire_zerrenda:",
      "    zerrenda_berria.append(elementua)",
      "",
      "zerrenda_berria[0] = 10",
      "zerrenda_berria.append(6)",
      "print(\"jatorrizkoa:\", nire_zerrenda)",
      "print(\"kopia:\", zerrenda_berria)",
      "```",
      "",
      "```text",
      "nire_zerrenda [1, 2, 3, 3, 5]",
      "zerrenda_berria [10, 2, 3, 3, 5, 6]",
      "```",
      "",
      "Zerrenda bat kopiatzeko modu errazago bat kortxete `[]` eragilea da, aurretik zatietarako erabili genuena. `[:]` notazioak bildumako elementu guztiak hautatzen ditu. Albo-efektu gisa, zerrendaren kopia bat sortzen du:",
      "",
      "```python",
      "nire_zerrenda = [1,2,3,4]",
      "zerrenda_berria = nire_zerrenda[:]",
      "",
      "nire_zerrenda[0] = 10",
      "zerrenda_berria[1] = 20",
      "",
      "print(nire_zerrenda)",
      "print(zerrenda_berria)",
      "```",
      "",
      "```text",
      "[10, 2, 3, 4]",
      "[1, 20, 3, 4]",
      "```"
    ].join("\n")
  }
};

const functionsAndListsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Using lists as parameters in functions",
      "",
      "When you pass a list as an argument to a function, you are passing a reference to that list. This means that the function can modify the list directly.",
      "",
      "The following function takes a list as an argument and adds a new item to the end of the list:",
      "",
      "```python",
      "def add_item(my_list: list):",
      "    new_item = 10",
      "    my_list.append(new_item)",
      "",
      "a_list = [1,2,3]",
      "print(a_list)",
      "add_item(a_list)",
      "print(a_list)",
      "```",
      "",
      "```text",
      "[1, 2, 3]",
      "[1, 2, 3, 10]",
      "```",
      "",
      "Notice the function `add_item` does not have a return value. It only changes the list it takes as an argument.",
      "",
      "Another way to implement this functionality would be to create a new list within the function, and return that:",
      "",
      "```python",
      "def add_item(my_list: list) -> list:",
      "    new_item = 10",
      "    my_list_copy = my_list[:]",
      "    my_list_copy.append(new_item)",
      "    return my_list_copy",
      "",
      "numbers = [1, 2, 3]",
      "numbers2 = add_item(numbers)",
      "",
      "print(\"original list:\", numbers)",
      "print(\"new list:\", numbers2)",
      "```",
      "",
      "```text",
      "original list: [1, 2, 3]",
      "new list: [1, 2, 3, 10]",
      "```",
      "",
      "## Editing a list given as an argument",
      "",
      "Actually, there is no need to create a new list within the function at all. We can just assign the new values directly into the original list:",
      "",
      "```python",
      "def augment_all(my_list: list):",
      "    for i in range(len(my_list)):",
      "        my_list[i] += 10",
      "```"
    ].join("\n"),
    CAS: [
      "## Usando listas como parámetros en funciones",
      "",
      "Cuando pasas una lista como argumento a una función, estás pasando una referencia a esa lista. Esto significa que la función puede modificar la lista directamente.",
      "",
      "La siguiente función toma una lista como argumento y agrega un nuevo elemento al final de la lista:",
      "",
      "```python",
      "def agregar_elemento(mi_lista: list):",
      "    nuevo_elemento = 10",
      "    mi_lista.append(nuevo_elemento)",
      "",
      "una_lista = [1,2,3]",
      "print(una_lista)",
      "agregar_elemento(una_lista)",
      "print(una_lista)",
      "```",
      "",
      "```text",
      "[1, 2, 3]",
      "[1, 2, 3, 10]",
      "```",
      "",
      "Observa que la función `agregar_elemento` no tiene un valor de retorno. Solo cambia la lista que toma como argumento.",
      "",
      "Otra forma de implementar esta funcionalidad sería crear una nueva lista dentro de la función y devolverla:",
      "",
      "```python",
      "def agregar_elemento(mi_lista: list) -> list:",
      "    nuevo_elemento = 10",
      "    copia_lista = mi_lista[:]",
      "    copia_lista.append(nuevo_elemento)",
      "    return copia_lista",
      "",
      "numeros = [1, 2, 3]",
      "numeros2 = agregar_elemento(numeros)",
      "",
      "print(\"lista original:\", numeros)",
      "print(\"lista nueva:\", numeros2)",
      "```",
      "",
      "```text",
      "lista original: [1, 2, 3]",
      "lista nueva: [1, 2, 3, 10]",
      "```",
      "",
      "## Editando una lista dada como argumento",
      "",
      "En realidad, no hay necesidad de crear una nueva lista dentro de la función en absoluto. Simplemente podemos asignar los nuevos valores directamente en la lista original:",
      "",
      "```python",
      "def aumentar_todo(mi_lista: list):",
      "    for i in range(len(mi_lista)):",
      "        mi_lista[i] += 10",
      "```"
    ].join("\n"),
    EUS: [
      "## Zerrendak parametro gisa erabiltzea funtzioetan",
      "",
      "Zerrenda bat funtzio bati argumentu gisa pasatzen diozunean, zerrenda horretarako erreferentzia bat pasatzen ari zara. Horrek esan nahi du funtzioak zerrenda zuzenean alda dezakeela.",
      "",
      "Hurrengo funtzioak zerrenda bat hartzen du argumentu gisa eta elementu berri bat gehitzen du zerrendaren amaieran:",
      "",
      "```python",
      "def gehitu_elementua(nire_zerrenda: list):",
      "    elementu_berria = 10",
      "    nire_zerrenda.append(elementu_berria)",
      "",
      "zerrenda_bat = [1,2,3]",
      "print(zerrenda_bat)",
      "gehitu_elementua(zerrenda_bat)",
      "print(zerrenda_bat)",
      "```",
      "",
      "```text",
      "[1, 2, 3]",
      "[1, 2, 3, 10]",
      "```",
      "",
      "Ohartu `gehitu_elementua` funtzioak ez duela itzulera-baliorik. Argumentu gisa hartzen duen zerrenda bakarrik aldatzen du.",
      "",
      "Funtzionalitate hau ezartzeko beste modu bat zerrenda berri bat funtzioaren barruan sortzea eta hori itzultzea litzateke:",
      "",
      "```python",
      "def gehitu_elementua(nire_zerrenda: list) -> list:",
      "    elementu_berria = 10",
      "    zerrenda_kopia = nire_zerrenda[:]",
      "    zerrenda_kopia.append(elementu_berria)",
      "    return zerrenda_kopia",
      "",
      "zenbakiak = [1, 2, 3]",
      "zenbakiak2 = gehitu_elementua(zenbakiak)",
      "",
      "print(\"jatorrizko zerrenda:\", zenbakiak)",
      "print(\"zerrenda berria:\", zenbakiak2)",
      "```",
      "",
      "```text",
      "jatorrizko zerrenda: [1, 2, 3]",
      "zerrenda berria: [1, 2, 3, 10]",
      "```",
      "",
      "## Argumentu gisa emandako zerrenda editatzen",
      "",
      "Egia esan, ez dago zerrenda berri bat sortu beharrik funtzioaren barruan. Balio berriak zuzenean jatorrizko zerrendan eslei ditzakegu:",
      "",
      "```python",
      "def handitu_dena(nire_zerrenda: list):",
      "    for i in range(len(nire_zerrenda)):",
      "        nire_zerrenda[i] += 10",
      "```"
    ].join("\n")
  }
};

const exerciseItemsMultipliedByTwo = {
  type: "exercise",
  exerciseId: "part05-08_items_multiplied_by_two",
  title: {
    ENG: "Items multiplied by two",
    CAS: "Elementos multiplicados por dos",
    EUS: "Elementuak biz biderkatuta"
  },
  description: {
    ENG: "Please write a function named `double_items(numbers: list)`, which takes a list of integers as its argument. The function should return a new list, which contains all values from the original list doubled. The function should not change the original list.",
    CAS: "Por favor escribe una función llamada `double_items(numbers: list)`, que tome una lista de enteros como argumento. La función debe devolver una nueva lista, que contenga todos los valores de la lista original duplicados. La función no debe cambiar la lista original.",
    EUS: "Mesedez idatzi `double_items(numbers: list)` izeneko funtzio bat, osoko zenbakien zerrenda bat argumentu gisa hartzen duena. Funtzioak zerrenda berri bat itzuli behar du, jatorrizko zerrendako balio guztiak bikoiztuta dituena. Funtzioak ez du jatorrizko zerrenda aldatu behar."
  },
  initialCode: {
    ENG: [
      "def double_items(numbers: list):",
      "    # Write your solution here",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numbers = [2, 4, 5, 3, 11, -4]",
      "    numbers_doubled = double_items(numbers)",
      "    print(\"original:\", numbers)",
      "    print(\"doubled:\", numbers_doubled)"
    ].join("\n"),
    CAS: [
      "def double_items(numbers: list):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numbers = [2, 4, 5, 3, 11, -4]",
      "    numbers_doubled = double_items(numbers)",
      "    print(\"original:\", numbers)",
      "    print(\"doubled:\", numbers_doubled)"
    ].join("\n"),
    EUS: [
      "def double_items(numbers: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numbers = [2, 4, 5, 3, 11, -4]",
      "    numbers_doubled = double_items(numbers)",
      "    print(\"original:\", numbers)",
      "    print(\"doubled:\", numbers_doubled)"
    ].join("\n")
  },
  testCode: ""
};

const exerciseRemoveSmallest = {
  type: "exercise",
  exerciseId: "part05-09_remove_smallest",
  title: {
    ENG: "Remove the smallest",
    CAS: "Eliminar el más pequeño",
    EUS: "Txikiena kendu"
  },
  description: {
    ENG: "Please write a function named `remove_smallest(numbers: list)`, which takes a list of integers as its argument. The functions should find and remove the smallest item in the list. The function should not have a return value - it should directly modify the list it receives as a parameter.",
    CAS: "Por favor escribe una función llamada `remove_smallest(numbers: list)`, que tome una lista de enteros como argumento. La función debe encontrar y eliminar el elemento más pequeño de la lista. La función no debe tener un valor de retorno - debe modificar directamente la lista que recibe como parámetro.",
    EUS: "Mesedez idatzi `remove_smallest(numbers: list)` izeneko funtzio bat, osoko zenbakien zerrenda bat argumentu gisa hartzen duena. Funtzioak zerrendako elementu txikiena aurkitu eta kendu behar du. Funtzioak ez du itzulera-baliorik izan behar - parametro gisa jasotzen duen zerrenda zuzenean aldatu behar du."
  },
  initialCode: {
    ENG: [
      "def remove_smallest(numbers: list):",
      "    # Write your solution here",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numbers = [2, 4, 6, 1, 3, 5]",
      "    remove_smallest(numbers)",
      "    print(numbers)"
    ].join("\n"),
    CAS: [
      "def remove_smallest(numbers: list):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numbers = [2, 4, 6, 1, 3, 5]",
      "    remove_smallest(numbers)",
      "    print(numbers)"
    ].join("\n"),
    EUS: [
      "def remove_smallest(numbers: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numbers = [2, 4, 6, 1, 3, 5]",
      "    remove_smallest(numbers)",
      "    print(numbers)"
    ].join("\n")
  },
  testCode: ""
};

const exerciseSudokuPrintAndAdd = {
  type: "exercise",
  exerciseId: "part05-10_sudoku_print_and_add",
  title: {
    ENG: "Sudoku: print out the grid and add a number",
    CAS: "Sudoku: imprimir la cuadrícula y añadir un número",
    EUS: "Sudoku: sareta inprimatu eta zenbaki bat gehitu"
  },
  description: {
    ENG: "In this exercise we will complete two more functions for the sudoku project: `print_sudoku(sudoku: list)` and `add_number(sudoku: list, row_no: int, column_no: int, number:int)`. `print_sudoku` prints the grid. `add_number` adds a number to the grid at the specified location.",
    CAS: "En este ejercicio completaremos dos funciones más para el proyecto sudoku: `print_sudoku(sudoku: list)` y `add_number(sudoku: list, row_no: int, column_no: int, number:int)`. `print_sudoku` imprime la cuadrícula. `add_number` añade un número a la cuadrícula en la ubicación especificada.",
    EUS: "Ariketa honetan sudoku proiekturako beste bi funtzio osatuko ditugu: `print_sudoku(sudoku: list)` eta `add_number(sudoku: list, row_no: int, column_no: int, number:int)`. `print_sudoku`-k sareta inprimatzen du. `add_number`-k zenbaki bat gehitzen du sareta zehaztutako kokapenean."
  },
  initialCode: {
    ENG: [
      "def print_sudoku(sudoku: list):",
      "    # Write your solution here",
      "    pass",
      "",
      "def add_number(sudoku: list, row_no: int, column_no: int, number: int):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def print_sudoku(sudoku: list):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "def add_number(sudoku: list, row_no: int, column_no: int, number: int):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def print_sudoku(sudoku: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "def add_number(sudoku: list, row_no: int, column_no: int, number: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseSudokuAddCopy = {
  type: "exercise",
  exerciseId: "part05-11_sudoku_add_to_copy",
  title: {
    ENG: "Sudoku: add number to a copy of the grid",
    CAS: "Sudoku: añadir número a una copia de la cuadrícula",
    EUS: "Sudoku: zenbakia gehitu saretaren kopia bati"
  },
  description: {
    ENG: "The function `copy_and_add(sudoku: list, row_no: int, column_no: int, number: int)` takes a sudoku grid and arguments. It should return a COPY of the grid with the new number added. It should NOT modify the original grid.",
    CAS: "La función `copy_and_add(sudoku: list, row_no: int, column_no: int, number: int)` toma una cuadrícula de sudoku y argumentos. Debe devolver una COPIA de la cuadrícula con el nuevo número añadido. NO debe modificar la cuadrícula original.",
    EUS: "`copy_and_add(sudoku: list, row_no: int, column_no: int, number: int)` funtzioak sudoku sareta bat eta argumentuak hartzen ditu. Saretaren KOPIA bat itzuli behar du zenbaki berria gehituta. EZ du jatorrizko sareta aldatu behar."
  },
  initialCode: {
    ENG: [
      "def copy_and_add(sudoku: list, row_no: int, column_no: int, number: int):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def copy_and_add(sudoku: list, row_no: int, column_no: int, number: int):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def copy_and_add(sudoku: list, row_no: int, column_no: int, number: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseTicTacToe = {
  type: "exercise",
  exerciseId: "part05-12_tic_tac_toe",
  title: {
    ENG: "Tic-Tac-Toe",
    CAS: "Tres en raya",
    EUS: "Artzain-jokoa"
  },
  description: {
    ENG: "Please write a function named `play_turn(game_board: list, x: int, y: int, piece: str)`, which places the given symbol at the given coordinates on the board. The function should return `True` if successful, `False` if the square is occupied or coordinates invalid. NB: x is column, y is row.",
    CAS: "Por favor escribe una función llamada `play_turn(game_board: list, x: int, y: int, piece: str)`, que coloque el símbolo dado en las coordenadas dadas en el tablero. La función debe devolver `True` si tiene éxito, `False` si la casilla está ocupada o las coordenadas no son válidas. NB: x es columna, y es fila.",
    EUS: "Mesedez idatzi `play_turn(game_board: list, x: int, y: int, piece: str)` izeneko funtzio bat, emandako ikurra taulako emandako koordenatuetan jartzen duena. Funtzioak `True` itzuli behar du arrakasta badu, `False` karratua okupatuta badago edo koordenatuak baliogabeak badira. OHARRA: x zutabea da, y errenkada."
  },
  initialCode: {
    ENG: [
      "def play_turn(game_board: list, x: int, y: int, piece: str):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def play_turn(game_board: list, x: int, y: int, piece: str):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def play_turn(game_board: list, x: int, y: int, piece: str):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseTranspose = {
  type: "exercise",
  exerciseId: "part05-13_transpose_matrix",
  title: {
    ENG: "Transpose a matrix",
    CAS: "Transponer una matriz",
    EUS: "Matrize bat irauli"
  },
  description: {
    ENG: "Please write a function named `transpose(matrix: list)`, which takes a two-dimensional integer array as its argument. The function should transpose the matrix (flip over its diagonal). The matrix should be modified directly.",
    CAS: "Por favor escribe una función llamada `transpose(matrix: list)`, que tome una matriz de enteros bidimensional como argumento. La función debe transponer la matriz (voltear sobre su diagonal). La matriz debe modificarse directamente.",
    EUS: "Mesedez idatzi `transpose(matrix: list)` izeneko funtzio bat, bi dimentsioko osoko array bat argumentu gisa hartzen duena. Funtzioak matrizea irauli behar du (bere diagonalaren gainean irauli). Matrizea zuzenean aldatu behar da."
  },
  initialCode: {
    ENG: [
      "def transpose(matrix: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def transpose(matrix: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def transpose(matrix: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const sideEffectsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Side effects of functions",
      "",
      "If a function takes a reference to a list as an argument, it will be able to modify that list. If direct modifications were not intended by the programmer, accidentally modifying the list received as a parameter could cause problems elsewhere in the program.",
      "",
      "Let's take a look at a function which is supposed to find the second smallest item in a list:",
      "",
      "```python",
      "def second_smallest(my_list: list) -> int:",
      "    # in an ordered list, the second smallest item is at index 1",
      "    my_list.sort()",
      "    return my_list[1]",
      "",
      "numbers = [1, 4, 2, 5, 3, 6, 4, 7]",
      "print(second_smallest(numbers))",
      "print(numbers)",
      "```",
      "",
      "```text",
      "2",
      "[1, 2, 3, 4, 4, 5, 6, 7]",
      "```",
      "",
      "The function does find the second smallest item reliably, but it additionally sorts the list in place, changing the order of the items. If the order is significant elsewhere in the program, calling the function could cause errors. Unintentional modifications to an object accessed through a reference is called a *side effect* of a function.",
      "",
      "We can avoid the side effect by making a small change to the function:",
      "",
      "```python",
      "def second_smallest(my_list: list) -> int:",
      "    list_copy = sorted(my_list)",
      "    return list_copy[1]",
      "",
      "numbers = [1, 4, 2, 5, 3, 6, 4, 7]",
      "print(second_smallest(numbers))",
      "print(numbers)",
      "```",
      "",
      "```text",
      "2",
      "[1, 4, 2, 5, 3, 6, 4, 7]",
      "```",
      "",
      "The function `sorted` returns a new, sorted copy of the list, so looking for the second smallest item no longer messes with the order of the original list.",
      "",
      "It is generally considered a good programming practice to avoid causing side effects with functions. Side effects can make it more difficult to verify that the program functions as intended in all situations."
    ].join("\n"),
    CAS: [
      "## Efectos secundarios de las funciones",
      "",
      "Si una función toma una referencia a una lista como argumento, podrá modificar esa lista. Si el programador no tenía la intención de realizar modificaciones directas, modificar accidentalmente la lista recibida como parámetro podría causar problemas en otras partes del programa.",
      "",
      "Echemos un vistazo a una función que se supone que encuentra el segundo elemento más pequeño en una lista:",
      "",
      "```python",
      "def segundo_mas_pequeno(mi_lista: list) -> int:",
      "    # en una lista ordenada, el segundo elemento más pequeño está en el índice 1",
      "    mi_lista.sort()",
      "    return mi_lista[1]",
      "",
      "numeros = [1, 4, 2, 5, 3, 6, 4, 7]",
      "print(segundo_mas_pequeno(numeros))",
      "print(numeros)",
      "```",
      "",
      "```text",
      "2",
      "[1, 2, 3, 4, 4, 5, 6, 7]",
      "```",
      "",
      "La función encuentra el segundo elemento más pequeño de manera confiable, pero además ordena la lista en su lugar, cambiando el orden de los elementos. Si el orden es significativo en otra parte del programa, llamar a la función podría causar errores. Las modificaciones no intencionales a un objeto al que se accede a través de una referencia se denominan *efecto secundario* de una función.",
      "",
      "Podemos evitar el efecto secundario haciendo un pequeño cambio en la función:",
      "",
      "```python",
      "def segundo_mas_pequeno(mi_lista: list) -> int:",
      "    copia_lista = sorted(mi_lista)",
      "    return copia_lista[1]",
      "",
      "numeros = [1, 4, 2, 5, 3, 6, 4, 7]",
      "print(segundo_mas_pequeno(numeros))",
      "print(numeros)",
      "```",
      "",
      "```text",
      "2",
      "[1, 4, 2, 5, 3, 6, 4, 7]",
      "```",
      "",
      "La función `sorted` devuelve una nueva copia ordenada de la lista, por lo que buscar el segundo elemento más pequeño ya no altera el orden de la lista original.",
      "",
      "Generalmente se considera una buena práctica de programación evitar causar efectos secundarios con las funciones. Los efectos secundarios pueden dificultar la verificación de que el programa funciona según lo previsto en todas las situaciones."
    ].join("\n"),
    EUS: [
      "## Funtzioen albo-efektuak",
      "",
      "Funtzio batek zerrenda baterako erreferentzia bat hartzen badu argumentu gisa, zerrenda hori aldatzeko gai izango da. Programatzaileak zuzeneko aldaketarik egiteko asmorik ez bazuen, parametro gisa jasotako zerrenda ustekabean aldatzeak arazoak sor ditzake programan beste nonbait.",
      "",
      "Ikus dezagun zerrenda bateko bigarren elementurik txikiena aurkitu behar duen funtzio bat:",
      "",
      "```python",
      "def bigarren_txikiena(nire_zerrenda: list) -> int:",
      "    # ordenatutako zerrenda batean, bigarren elementurik txikiena 1. indizean dago",
      "    nire_zerrenda.sort()",
      "    return nire_zerrenda[1]",
      "",
      "zenbakiak = [1, 4, 2, 5, 3, 6, 4, 7]",
      "print(bigarren_txikiena(zenbakiak))",
      "print(zenbakiak)",
      "```",
      "",
      "```text",
      "2",
      "[1, 2, 3, 4, 4, 5, 6, 7]",
      "```",
      "",
      "Funtzioak bigarren elementurik txikiena fidagarritasunez aurkitzen du, baina gainera zerrenda bere horretan ordenatzen du, elementuen ordena aldatuz. Ordena garrantzitsua bada programan beste nonbait, funtzioari deitzeak erroreak sor ditzake. Erreferentzia baten bidez atzitzen den objektu baten nahi gabeko aldaketei funtzio baten *albo-efektu* deitzen zaie.",
      "",
      "Albo-efektua saihestu dezakegu funtzioan aldaketa txiki bat eginez:",
      "",
      "```python",
      "def bigarren_txikiena(nire_zerrenda: list) -> int:",
      "    zerrenda_kopia = sorted(nire_zerrenda)",
      "    return zerrenda_kopia[1]",
      "",
      "zenbakiak = [1, 4, 2, 5, 3, 6, 4, 7]",
      "print(bigarren_txikiena(zenbakiak))",
      "print(zenbakiak)",
      "```",
      "",
      "```text",
      "2",
      "[1, 4, 2, 5, 3, 6, 4, 7]",
      "```",
      "",
      "`sorted` funtzioak zerrendaren kopia berri eta ordenatu bat itzultzen du, beraz, bigarren elementurik txikiena bilatzeak ez du jatorrizko zerrendaren ordena nahasten.",
      "",
      "Oro har, programazio-praktika ontzat jotzen da funtzioekin albo-efektuak sortzea saihestea. Albo-efektuek zaildu egin dezakete programak egoera guztietan nahi bezala funtzionatzen duela egiaztatzea."
    ].join("\n")
  }
};

const section2 = {
  id: "part5-2",
  title: {
    ENG: "References",
    CAS: "Referencias",
    EUS: "Erreferentziak"
  },
  blocks: [
    learningObjectives,
    introContent,
    functionsAndListsContent,
    exerciseItemsMultipliedByTwo,
    exerciseRemoveSmallest,
    exerciseSudokuPrintAndAdd,
    exerciseSudokuAddCopy,
    exerciseTicTacToe,
    exerciseTranspose,
    sideEffectsContent
  ]
};

const outputPath = path.join(__dirname, '../src/data/part5/section2.json');
fs.writeFileSync(outputPath, JSON.stringify(section2, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);
