const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will be familiar with more methods for slicing strings and lists",
      "- You will understand what immutability of strings means",
      "- You will be able to use the methods `count` and `replace`"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Estarás familiarizado con más métodos para rebanar cadenas y listas",
      "- Entenderás qué significa la inmutabilidad de las cadenas",
      "- Podrás usar los métodos `count` y `replace`"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Kateak eta zerrendak zatitzeko metodo gehiago ezagutuko dituzu",
      "- Kateen aldaezintasunak zer esan nahi duen ulertuko duzu",
      "- `count` eta `replace` metodoak erabiltzeko gai izango zara"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "You are already familiar with the `[]` syntax for accessing a part of a string:",
      "",
      "```python",
      "my_string = \"exemplary\"",
      "print(my_string[3:7])",
      "```",
      "",
      "```text",
      "mpla",
      "```",
      "",
      "The same syntax works with lists. Lists can be sliced just like strings:",
      "",
      "```python",
      "my_list = [3,4,2,4,6,1,2,4,2]",
      "print(my_list[3:7])",
      "```",
      "",
      "```text",
      "[4, 6, 1, 2]",
      "```",
      "",
      "## More slices",
      "",
      "In fact, the `[]` syntax works very similarly to the `range` function, which means we can also give it a step:",
      "",
      "```python",
      "my_string = \"exemplary\"",
      "print(my_string[0:7:2])",
      "my_list = [1,2,3,4,5,6,7,8]",
      "print(my_list[6:2:-1])",
      "```",
      "",
      "```text",
      "eepa",
      "[7, 6, 5, 4]",
      "```",
      "",
      "If we omit either of the indexes, the operator defaults to including everything. Among other things, this allows us to write a very short program to reverse a string:",
      "",
      "```python",
      "my_string = input(\"Please type in a string: \")",
      "print(my_string[::-1])",
      "```",
      "",
      "```text",
      "Please type in a string: exemplary",
      "yralpmexe",
      "```",
      "",
      "## Warning: using global variables within functions",
      "",
      "We know it is possible to assign new variables within function definitions, but the function can also see variables assigned outside it, in the main function. Such variables are called *global* variables.",
      "",
      "Using global variables from within functions is usually a bad idea. Among other issues, doing so may cause bugs which are difficult to trace.",
      "",
      "Below is an example of a function which uses a global variable \"by mistake\":",
      "",
      "```python",
      "def print_reversed(names: list):",
      "    # using the global variable instead of the parameter by accident",
      "    i = len(name_list) - 1",
      "    while i >= 0:",
      "        print(name_list[i])",
      "        i -= 1",
      "",
      "# here the global variable is assigned",
      "name_list = [\"Steve\", \"Jean\", \"Katherine\", \"Paul\"]",
      "print_reversed(name_list)",
      "print()",
      "print_reversed([\"Huey\", \"Dewey\", \"Louie\"])",
      "```",
      "",
      "```text",
      "Paul",
      "Katherine",
      "Jean",
      "Steve",
      "",
      "Paul",
      "Katherine",
      "Jean",
      "Steve",
      "```",
      "",
      "Even though both function calls have the right kind of argument, the function always prints out what is stored in the global variable `name_list`.",
      "",
      "To make matters even more muddled, remember that all code for testing your functions should be placed within the `if __name__ == \"__main__\":` block for the automatic tests. The previous example should be modified:",
      "",
      "```python",
      "def print_reversed(names: list):",
      "    # using the global variable instead of the parameter by accident",
      "    i = len(name_list) - 1",
      "    while i>=0:",
      "        print(name_list[i])",
      "        i -= 1",
      "",
      "# All the code for testing the function should be within this block",
      "if __name__ == \"__main__\":",
      "    # here the global variable is assigned",
      "    name_list = [\"Steve\", \"Jean\", \"Katherine\", \"Paul\"]",
      "    print_reversed(name_list)",
      "    print()",
      "    print_reversed([\"Huey\", \"Dewey\", \"Louie\"])",
      "```",
      "",
      "Notice the global variable is assigned within the `if` block now.",
      "",
      "The automatic tests in the TMC system are executed without running any of the code in the `if` block. So, in this latter example the function wouldn't even theoretically work, since it refers to the variable `name_list`, which doesn't exist at all when the tests are executed."
    ].join("\n"),
    CAS: [
      "Ya estás familiarizado con la sintaxis `[]` para acceder a una parte de una cadena:",
      "",
      "```python",
      "mi_cadena = \"ejemplar\"",
      "print(mi_cadena[3:7])",
      "```",
      "",
      "```text",
      "mpla",
      "```",
      "",
      "La misma sintaxis funciona con listas. Las listas se pueden rebanar igual que las cadenas:",
      "",
      "```python",
      "mi_lista = [3,4,2,4,6,1,2,4,2]",
      "print(mi_lista[3:7])",
      "```",
      "",
      "```text",
      "[4, 6, 1, 2]",
      "```",
      "",
      "## Más rebanadas",
      "",
      "De hecho, la sintaxis `[]` funciona de manera muy similar a la función `range`, lo que significa que también podemos darle un paso:",
      "",
      "```python",
      "mi_cadena = \"ejemplar\"",
      "print(mi_cadena[0:7:2])",
      "mi_lista = [1,2,3,4,5,6,7,8]",
      "print(mi_lista[6:2:-1])",
      "```",
      "",
      "```text",
      "eepa",
      "[7, 6, 5, 4]",
      "```",
      "",
      "Si omitimos cualquiera de los índices, el operador incluye todo por defecto. Entre otras cosas, esto nos permite escribir un programa muy corto para invertir una cadena:",
      "",
      "```python",
      "mi_cadena = input(\"Por favor escribe una cadena: \")",
      "print(mi_cadena[::-1])",
      "```",
      "",
      "```text",
      "Por favor escribe una cadena: ejemplar",
      "ralpmeje",
      "```",
      "",
      "## Advertencia: uso de variables globales dentro de funciones",
      "",
      "Sabemos que es posible asignar nuevas variables dentro de las definiciones de funciones, pero la función también puede ver variables asignadas fuera de ella, en la función principal. Tales variables se llaman variables *globales*.",
      "",
      "Usar variables globales desde dentro de funciones suele ser una mala idea. Entre otros problemas, hacerlo puede causar errores que son difíciles de rastrear.",
      "",
      "A continuación se muestra un ejemplo de una función que usa una variable global \"por error\":",
      "",
      "```python",
      "def imprimir_invertido(nombres: list):",
      "    # usando la variable global en lugar del parámetro por accidente",
      "    i = len(lista_nombres) - 1",
      "    while i >= 0:",
      "        print(lista_nombres[i])",
      "        i -= 1",
      "",
      "# aquí se asigna la variable global",
      "lista_nombres = [\"Steve\", \"Jean\", \"Katherine\", \"Paul\"]",
      "imprimir_invertido(lista_nombres)",
      "print()",
      "imprimir_invertido([\"Huey\", \"Dewey\", \"Louie\"])",
      "```",
      "",
      "```text",
      "Paul",
      "Katherine",
      "Jean",
      "Steve",
      "",
      "Paul",
      "Katherine",
      "Jean",
      "Steve",
      "```",
      "",
      "Aunque ambas llamadas a la función tienen el tipo correcto de argumento, la función siempre imprime lo que está almacenado en la variable global `lista_nombres`.",
      "",
      "Para complicar aún más las cosas, recuerda que todo el código para probar tus funciones debe colocarse dentro del bloque `if __name__ == \"__main__\":` para las pruebas automáticas. El ejemplo anterior debería modificarse:",
      "",
      "```python",
      "def imprimir_invertido(nombres: list):",
      "    # usando la variable global en lugar del parámetro por accidente",
      "    i = len(lista_nombres) - 1",
      "    while i>=0:",
      "        print(lista_nombres[i])",
      "        i -= 1",
      "",
      "# Todo el código para probar la función debe estar dentro de este bloque",
      "if __name__ == \"__main__\":",
      "    # aquí se asigna la variable global",
      "    lista_nombres = [\"Steve\", \"Jean\", \"Katherine\", \"Paul\"]",
      "    imprimir_invertido(lista_nombres)",
      "    print()",
      "    imprimir_invertido([\"Huey\", \"Dewey\", \"Louie\"])",
      "```",
      "",
      "Observa que la variable global se asigna dentro del bloque `if` ahora.",
      "",
      "Las pruebas automáticas en el sistema TMC se ejecutan sin ejecutar nada del código en el bloque `if`. Entonces, en este último ejemplo, la función ni siquiera funcionaría teóricamente, ya que se refiere a la variable `lista_nombres`, que no existe en absoluto cuando se ejecutan las pruebas."
    ].join("\n"),
    EUS: [
      "Jada ezagutzen duzu kate baten zati batera sartzeko `[]` sintaxia:",
      "",
      "```python",
      "nire_katea = \"eredugarria\"",
      "print(nire_katea[3:7])",
      "```",
      "",
      "```text",
      "duga",
      "```",
      "",
      "Sintaxi berak zerrendekin funtzionatzen du. Zerrendak kateen antzera zatidaitezke:",
      "",
      "```python",
      "nire_zerrenda = [3,4,2,4,6,1,2,4,2]",
      "print(nire_zerrenda[3:7])",
      "```",
      "",
      "```text",
      "[4, 6, 1, 2]",
      "```",
      "",
      "## Zati gehiago",
      "",
      "Izan ere, `[]` sintaxiak `range` funtzioaren oso antzera funtzionatzen du, horrek esan nahi du pauso bat ere eman diezaiokegula:",
      "",
      "```python",
      "nire_katea = \"eredugarria\"",
      "print(nire_katea[0:7:2])",
      "nire_zerrenda = [1,2,3,4,5,6,7,8]",
      "print(nire_zerrenda[6:2:-1])",
      "```",
      "",
      "```text",
      "eeua",
      "[7, 6, 5, 4]",
      "```",
      "",
      "Indizeetako bat omititzen badugu, eragileak lehenespenez dena barne hartzen du. Besteak beste, honek kate bat alderantzizkatzeko programa oso labur bat idazteko aukera ematen digu:",
      "",
      "```python",
      "nire_katea = input(\"Mesedez idatzi kate bat: \")",
      "print(nire_katea[::-1])",
      "```",
      "",
      "```text",
      "Mesedez idatzi kate bat: eredugarria",
      "airragudere",
      "```",
      "",
      "## Oharra: aldagai globalak erabiltzea funtzioetan",
      "",
      "Badakigu funtzio definizioetan aldagai berriak esleitzea posible dela, baina funtzioak kanpoan esleitutako aldagaiak ere ikus ditzake, funtzio nagusian. Horrelako aldagaiei aldagai *globalak* deitzen zaie.",
      "",
      "Funtzioen barrutik aldagai globalak erabiltzea ideia txarra izan ohi da. Beste arazo batzuen artean, hori egiteak arakatzen zailak diren akatsak sor ditzake.",
      "",
      "Behean aldagai global bat \"errakuntzaz\" erabiltzen duen funtzio baten adibidea dago:",
      "",
      "```python",
      "def inprimatu_alderantziz(izenak: list):",
      "    # parametroaren ordez aldagai globala erabiltzen istripuz",
      "    i = len(izen_zerrenda) - 1",
      "    while i >= 0:",
      "        print(izen_zerrenda[i])",
      "        i -= 1",
      "",
      "# hemen aldagai globala esleitzen da",
      "izen_zerrenda = [\"Steve\", \"Jean\", \"Katherine\", \"Paul\"]",
      "inprimatu_alderantziz(izen_zerrenda)",
      "print()",
      "inprimatu_alderantziz([\"Huey\", \"Dewey\", \"Louie\"])",
      "```",
      "",
      "```text",
      "Paul",
      "Katherine",
      "Jean",
      "Steve",
      "",
      "Paul",
      "Katherine",
      "Jean",
      "Steve",
      "```",
      "",
      "Nahiz eta bi funtzio deiek argumentu mota egokia izan, funtzioak beti `izen_zerrenda` aldagai globalean gordetakoa inprimatzen du.",
      "",
      "Gauzak are gehiago nahasteko, gogoratu zure funtzioak probatzeko kode guztia `if __name__ == \"__main__\":` blokearen barruan jarri behar dela proba automatikoetarako. Aurreko adibidea aldatu beharko litzateke:",
      "",
      "```python",
      "def inprimatu_alderantziz(izenak: list):",
      "    # parametroaren ordez aldagai globala erabiltzen istripuz",
      "    i = len(izen_zerrenda) - 1",
      "    while i>=0:",
      "        print(izen_zerrenda[i])",
      "        i -= 1",
      "",
      "# Funtzioa probatzeko kode guztia bloke honen barruan egon behar da",
      "if __name__ == \"__main__\":",
      "    # hemen aldagai globala esleitzen da",
      "    izen_zerrenda = [\"Steve\", \"Jean\", \"Katherine\", \"Paul\"]",
      "    inprimatu_alderantziz(izen_zerrenda)",
      "    print()",
      "    inprimatu_alderantziz([\"Huey\", \"Dewey\", \"Louie\"])",
      "```",
      "",
      "Ohartu aldagai globala orain `if` blokearen barruan esleitzen dela.",
      "",
      "TMC sistemako proba automatikoak `if` blokeko koderik exekutatu gabe exekutatzen dira. Beraz, azken adibide honetan funtzioak ez luke teorikoki ere funtzionatuko, `izen_zerrenda` aldagaia aipatzen baitu, probak exekutatzen direnean batere existitzen ez dena."
    ].join("\n")
  }
};

const exerciseEverythingReversed = {
  type: "exercise",
  exerciseId: "part04-33_everything_reversed",
  title: {
    ENG: "Everything reversed",
    CAS: "Todo invertido",
    EUS: "Dena alderantzizkatuta"
  },
  description: {
    ENG: "Please write a function named `everything_reversed`, which takes a list of strings as its argument. The function returns a new list with all of the items on the original list reversed. Also the order of items should be reversed on the new list.",
    CAS: "Por favor escribe una función llamada `everything_reversed`, que tome una lista de cadenas como argumento. La función devuelve una nueva lista con todos los elementos de la lista original invertidos. Además, el orden de los elementos debe invertirse en la nueva lista.",
    EUS: "Mesedez idatzi `everything_reversed` izeneko funtzio bat, kate zerrenda bat argumentu gisa hartzen duena. Funtzioak zerrenda berri bat itzultzen du jatorrizko zerrendako elementu guztiak alderantzizkatuta. Elementuen ordena ere alderantzizkatu behar da zerrenda berrian."
  },
  initialCode: {
    ENG: [
      "def everything_reversed(my_list: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def everything_reversed(mi_lista: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def everything_reversed(nire_zerrenda: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const stringsImmutableContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Strings are immutable",
      "",
      "Strings and lists have a lot in common, especially in the way they behave with different operators. The main difference is that strings are *immutable*. That means they cannot be changed.",
      "",
      "```python",
      "my_string = \"exemplary\"",
      "my_string[0] = \"a\"",
      "```",
      "",
      "Strings cannot be changed, so the execution of this program causes an error:",
      "",
      "```text",
      "TypeError: 'str' object does not support item assignment",
      "```",
      "",
      "A similar error follows if you try to sort a string with the `sort` method.",
      "",
      "Strings themselves are immutable, but the variables holding them are not. A string can be replaced by another string.",
      "",
      "The following two examples are thus fundamentally different:",
      "",
      "```python",
      "my_list = [1,2,3]",
      "my_list[0] = 10",
      "```",
      "",
      "![Modifying a list](images/4_6_1.png)",
      "",
      "```python",
      "my_string = \"Hey\"",
      "my_string = my_string + \"!\"",
      "```",
      "",
      "![Reassigning a string variable](images/4_6_2.png)",
      "",
      "The first example changes the contents of the referenced list. The second example replaces the reference to the original string with a reference to another string. The original string is still somewhere in computer memory, but there is no reference to it, and it cannot be used in the program any longer.",
      "",
      "We will return to this subject in the next part, where references to lists are explored in more detail.",
      "",
      "## More methods for lists and strings",
      "",
      "The method `count` counts the number of times the specified item or substring occurs in the target. The method works similarly with both strings and lists:",
      "",
      "```python",
      "my_string = \"How much wood would a woodchuck chuck if a woodchuck could chuck wood\"",
      "print(my_string.count(\"ch\"))",
      "",
      "my_list = [1,2,3,1,4,5,1,6]",
      "print(my_list.count(1))",
      "```",
      "",
      "```text",
      "5",
      "3",
      "```",
      "",
      "The method will not count overlapping occurrences. For example, in the string `aaaa` the method counts only two occurrences of the substring `aa`, even though there would actually be three if overlapping occurrences were allowed.",
      "",
      "The method `replace` creates a new string, where a specified substring is replaced with another string:",
      "",
      "```python",
      "my_string = \"Hi there\"",
      "new_string = my_string.replace(\"Hi\", \"Hey\")",
      "print(new_string)",
      "```",
      "",
      "```text",
      "Hey there",
      "```",
      "",
      "The method will replace all occurrences of the substring:",
      "",
      "```python",
      "sentence = \"sheila sells seashells on the seashore\"",
      "print(sentence.replace(\"she\", \"SHE\"))",
      "```",
      "",
      "```text",
      "SHEila sells seaSHElls on the seashore",
      "```",
      "",
      "When using the `replace` method, a typical mistake is forgetting that strings are immutable:",
      "",
      "```python",
      "my_string = \"Python is fun\"",
      "",
      "# Replaces the substring but doesn't store the result...",
      "my_string.replace(\"Python\", \"Java\")",
      "print(my_string)",
      "```",
      "",
      "```text",
      "Python is fun",
      "```",
      "",
      "If the old string is no longer needed, the new string can be assigned to the same variable:",
      "",
      "```python",
      "my_string = \"Python is fun\"",
      "",
      "# Replaces the substring and stores the result in the same variable",
      "my_string = my_string.replace(\"Python\", \"Java\")",
      "print(my_string)",
      "```",
      "",
      "```text",
      "Java is fun",
      "```"
    ].join("\n"),
    CAS: [
      "## Las cadenas son inmutables",
      "",
      "Las cadenas y las listas tienen mucho en común, especialmente en la forma en que se comportan con diferentes operadores. La principal diferencia es que las cadenas son *inmutables*. Eso significa que no se pueden cambiar.",
      "",
      "```python",
      "mi_cadena = \"ejemplar\"",
      "mi_cadena[0] = \"a\"",
      "```",
      "",
      "Las cadenas no se pueden cambiar, por lo que la ejecución de este programa causa un error:",
      "",
      "```text",
      "TypeError: 'str' object does not support item assignment",
      "```",
      "",
      "Un error similar ocurre si intentas ordenar una cadena con el método `sort`.",
      "",
      "Las cadenas en sí mismas son inmutables, pero las variables que las contienen no lo son. Una cadena puede ser reemplazada por otra cadena.",
      "",
      "Los siguientes dos ejemplos son, por lo tanto, fundamentalmente diferentes:",
      "",
      "```python",
      "mi_lista = [1,2,3]",
      "mi_lista[0] = 10",
      "```",
      "",
      "![Modificando una lista](images/4_6_1.png)",
      "",
      "```python",
      "mi_cadena = \"Hola\"",
      "mi_cadena = mi_cadena + \"!\"",
      "```",
      "",
      "![Reasignando una variable de cadena](images/4_6_2.png)",
      "",
      "El primer ejemplo cambia el contenido de la lista referenciada. El segundo ejemplo reemplaza la referencia a la cadena original con una referencia a otra cadena. La cadena original todavía está en algún lugar de la memoria del ordenador, pero no hay referencia a ella, y ya no se puede usar en el programa.",
      "",
      "Volveremos a este tema en la siguiente parte, donde se exploran las referencias a listas con más detalle.",
      "",
      "## Más métodos para listas y cadenas",
      "",
      "El método `count` cuenta el número de veces que el elemento o subcadena especificado ocurre en el objetivo. El método funciona de manera similar tanto con cadenas como con listas:",
      "",
      "```python",
      "mi_cadena = \"How much wood would a woodchuck chuck if a woodchuck could chuck wood\"",
      "print(mi_cadena.count(\"ch\"))",
      "",
      "mi_lista = [1,2,3,1,4,5,1,6]",
      "print(mi_lista.count(1))",
      "```",
      "",
      "```text",
      "5",
      "3",
      "```",
      "",
      "El método no contará apariciones superpuestas. Por ejemplo, en la cadena `aaaa` el método cuenta solo dos apariciones de la subcadena `aa`, aunque en realidad habría tres si se permitieran apariciones superpuestas.",
      "",
      "El método `replace` crea una nueva cadena, donde una subcadena especificada se reemplaza con otra cadena:",
      "",
      "```python",
      "mi_cadena = \"Hola ahí\"",
      "nueva_cadena = mi_cadena.replace(\"Hola\", \"Hey\")",
      "print(nueva_cadena)",
      "```",
      "",
      "```text",
      "Hey ahí",
      "```",
      "",
      "El método reemplazará todas las apariciones de la subcadena:",
      "",
      "```python",
      "oracion = \"sheila sells seashells on the seashore\"",
      "print(oracion.replace(\"she\", \"SHE\"))",
      "```",
      "",
      "```text",
      "SHEila sells seaSHElls on the seashore",
      "```",
      "",
      "Al usar el método `replace`, un error típico es olvidar que las cadenas son inmutables:",
      "",
      "```python",
      "mi_cadena = \"Python es divertido\"",
      "",
      "# Reemplaza la subcadena pero no guarda el resultado...",
      "mi_cadena.replace(\"Python\", \"Java\")",
      "print(mi_cadena)",
      "```",
      "",
      "```text",
      "Python es divertido",
      "```",
      "",
      "Si la cadena antigua ya no es necesaria, la nueva cadena se puede asignar a la misma variable:",
      "",
      "```python",
      "mi_cadena = \"Python es divertido\"",
      "",
      "# Reemplaza la subcadena y guarda el resultado en la misma variable",
      "mi_cadena = mi_cadena.replace(\"Python\", \"Java\")",
      "print(mi_cadena)",
      "```",
      "",
      "```text",
      "Java es divertido",
      "```"
    ].join("\n"),
    EUS: [
      "## Kateak aldaezinak dira",
      "",
      "Kateek eta zerrendek komunean asko dute, batez ere eragile ezberdinekin duten portaeran. Desberdintasun nagusia kateak *aldaezinak* direla da. Horrek esan nahi du ezin direla aldatu.",
      "",
      "```python",
      "nire_katea = \"eredugarria\"",
      "nire_katea[0] = \"a\"",
      "```",
      "",
      "Kateak ezin dira aldatu, beraz, programa honen exekuzioak errore bat eragiten du:",
      "",
      "```text",
      "TypeError: 'str' object does not support item assignment",
      "```",
      "",
      "Antzeko errore bat gertatzen da kate bat `sort` metodoarekin ordenatzen saiatzen bazara.",
      "",
      "Kateak eurak aldaezinak dira, baina haiek dituzten aldagaiak ez. Kate bat beste kate batekin ordezkatu daiteke.",
      "",
      "Hurrengo bi adibideak funtsean desberdinak dira:",
      "",
      "```python",
      "nire_zerrenda = [1,2,3]",
      "nire_zerrenda[0] = 10",
      "```",
      "",
      "![Zerrenda bat aldatzen](images/4_6_1.png)",
      "",
      "```python",
      "nire_katea = \"Aupa\"",
      "nire_katea = nire_katea + \"!\"",
      "```",
      "",
      "![Kate aldagai bat berriz esleitzen](images/4_6_2.png)",
      "",
      "Lehenengo adibideak erreferentziatutako zerrendaren edukia aldatzen du. Bigarren adibideak jatorrizko katearen erreferentzia beste kate baten erreferentziarekin ordezkatzen du. Jatorrizko katea oraindik ordenagailuaren memorian dago nonbait, baina ez dago horren erreferentziarik, eta ezin da programan gehiago erabili.",
      "",
      "Gai honetara itzuliko gara hurrengo atalean, zerrendetarako erreferentziak xehetasun gehiagorekin aztertzen direnean.",
      "",
      "## Metodo gehiago zerrenda eta kateetarako",
      "",
      "`count` metodoak zehaztutako elementua edo azpikatea helburuan zenbat aldiz agertzen den kontatzen du. Metodoak antzera funtzionatzen du bai kateekin bai zerrendekin:",
      "",
      "```python",
      "nire_katea = \"How much wood would a woodchuck chuck if a woodchuck could chuck wood\"",
      "print(nire_katea.count(\"ch\"))",
      "",
      "nire_zerrenda = [1,2,3,1,4,5,1,6]",
      "print(nire_zerrenda.count(1))",
      "```",
      "",
      "```text",
      "5",
      "3",
      "```",
      "",
      "Metodoak ez ditu gainjarritako agerraldiak kontatuko. Adibidez, `aaaa` katean metodoak `aa` azpikatearen bi agerraldi bakarrik kontatzen ditu, nahiz eta benetan hiru egongo liratekeen gainjarritako agerraldiak baimenduko balira.",
      "",
      "`replace` metodoak kate berri bat sortzen du, non zehaztutako azpikate bat beste kate batekin ordezkatzen den:",
      "",
      "```python",
      "nire_katea = \"Kaixo hor\"",
      "katea_berria = nire_katea.replace(\"Kaixo\", \"Aupa\")",
      "print(katea_berria)",
      "```",
      "",
      "```text",
      "Aupa hor",
      "```",
      "",
      "Metodoak azpikatearen agerraldi guztiak ordezkatuko ditu:",
      "",
      "```python",
      "esaldia = \"sheila sells seashells on the seashore\"",
      "print(esaldia.replace(\"she\", \"SHE\"))",
      "```",
      "",
      "```text",
      "SHEila sells seaSHElls on the seashore",
      "```",
      "",
      "`replace` metodoa erabiltzean, ohiko akats bat kateak aldaezinak direla ahaztea da:",
      "",
      "```python",
      "nire_katea = \"Python dibertigarria da\"",
      "",
      "# Azpikatea ordezkatzen du baina ez du emaitza gordetzen...",
      "nire_katea.replace(\"Python\", \"Java\")",
      "print(nire_katea)",
      "```",
      "",
      "```text",
      "Python dibertigarria da",
      "```",
      "",
      "Kate zaharra jada behar ez bada, kate berria aldagai berari esleitu dakioke:",
      "",
      "```python",
      "nire_katea = \"Python dibertigarria da\"",
      "",
      "# Azpikatea ordezkatzen du eta emaitza aldagai berean gordetzen du",
      "nire_katea = nire_katea.replace(\"Python\", \"Java\")",
      "print(nire_katea)",
      "```",
      "",
      "```text",
      "Java dibertigarria da",
      "```"
    ].join("\n")
  }
};

const exerciseMostCommonCharacter = {
  type: "exercise",
  exerciseId: "part04-34_most_common_character",
  title: {
    ENG: "Most common character",
    CAS: "Carácter más común",
    EUS: "Karaktere ohikoena"
  },
  description: {
    ENG: "Please write a function named `most_common_character`, which takes a string argument. The function returns the character which has the most occurrences within the string. If there are many characters with equally many occurrences, the one which appears first in the string should be returned.",
    CAS: "Por favor escribe una función llamada `most_common_character`, que tome un argumento de cadena. La función devuelve el carácter que tiene más apariciones dentro de la cadena. Si hay muchos caracteres con la misma cantidad de apariciones, se debe devolver el que aparece primero en la cadena.",
    EUS: "Mesedez idatzi `most_common_character` izeneko funtzio bat, kate argumentu bat hartzen duena. Funtzioak katean agerraldi gehien dituen karakterea itzultzen du. Agerraldi kopuru bera duten karaktere asko badaude, katean lehenengo agertzen dena itzuli behar da."
  },
  initialCode: {
    ENG: [
      "def most_common_character(my_string: str):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def most_common_character(mi_cadena: str):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def most_common_character(nire_katea: str):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseNoVowelsAllowed = {
  type: "exercise",
  exerciseId: "part04-35_no_vowels_allowed",
  title: {
    ENG: "No vowels allowed",
    CAS: "No se permiten vocales",
    EUS: "Bokalik ez da onartzen"
  },
  description: {
    ENG: "Please write a function named `no_vowels`, which takes a string argument. The function returns a new string, which should be the same as the original but with all vowels removed. You can assume the string will contain only characters from the lowercase English alphabet a...z.",
    CAS: "Por favor escribe una función llamada `no_vowels`, que tome un argumento de cadena. La función devuelve una nueva cadena, que debe ser la misma que la original pero con todas las vocales eliminadas. Puedes asumir que la cadena contendrá solo caracteres del alfabeto inglés en minúsculas a...z.",
    EUS: "Mesedez idatzi `no_vowels` izeneko funtzio bat, kate argumentu bat hartzen duena. Funtzioak kate berri bat itzultzen du, jatorrizkoaren berdina izan behar duena baina bokal guztiak kenduta. Suposa dezakezu kateak a...z alfabeto ingeleseko karaktere minuskulak soilik izango dituela."
  },
  initialCode: {
    ENG: [
      "def no_vowels(my_string: str):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def no_vowels(mi_cadena: str):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def no_vowels(nire_katea: str):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseNoShoutingAllowed = {
  type: "exercise",
  exerciseId: "part04-36_no_shouting_allowed",
  title: {
    ENG: "No shouting allowed",
    CAS: "No se permite gritar",
    EUS: "Ez da oihukatzea onartzen"
  },
  description: {
    ENG: "Please use the `isupper` method to write a function named `no_shouting`, which takes a list of strings as an argument. The function returns a new list, containing only those items from the original which do not consist of solely uppercase characters.",
    CAS: "Por favor usa el método `isupper` para escribir una función llamada `no_shouting`, que tome una lista de cadenas como argumento. La función devuelve una nueva lista, que contiene solo aquellos elementos del original que no consisten únicamente en caracteres en mayúsculas.",
    EUS: "Mesedez erabili `isupper` metodoa `no_shouting` izeneko funtzio bat idazteko, kate zerrenda bat argumentu gisa hartzen duena. Funtzioak zerrenda berri bat itzultzen du, jatorrizkotik karaktere larriz soilik osatuta ez dauden elementuak bakarrik dituena."
  },
  initialCode: {
    ENG: [
      "def no_shouting(my_list: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def no_shouting(mi_lista: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def no_shouting(nire_zerrenda: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseNeighboursInList = {
  type: "exercise",
  exerciseId: "part04-37_neighbours_in_list",
  title: {
    ENG: "Neighbours in a list",
    CAS: "Vecinos en una lista",
    EUS: "Auzokideak zerrenda batean"
  },
  description: {
    ENG: "Given a list of integers, let's decide that two consecutive items in the list are neighbours if their difference is 1. Please write a function named `longest_series_of_neighbours`, which looks for the longest series of neighbours within the list, and returns its length.",
    CAS: "Dada una lista de enteros, decidamos que dos elementos consecutivos en la lista son vecinos si su diferencia es 1. Por favor escribe una función llamada `longest_series_of_neighbours`, que busque la serie más larga de vecinos dentro de la lista, y devuelva su longitud.",
    EUS: "Osoko zenbakien zerrenda bat emanda, erabaki dezagun zerrendako ondoz ondoko bi elementu auzokideak direla haien aldea 1 bada. Mesedez idatzi `longest_series_of_neighbours` izeneko funtzio bat, zerrendan auzokideen serie luzeena bilatzen duena, eta bere luzera itzultzen duena."
  },
  initialCode: {
    ENG: [
      "def longest_series_of_neighbours(my_list: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def longest_series_of_neighbours(mi_lista: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def longest_series_of_neighbours(nire_zerrenda: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const largeProjectContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Developing a larger programming project",
      "",
      "This fourth part culminates in a slightly larger programming project, where you get to apply many of the techniques learnt so far.",
      "",
      "Rule No. 1 in tackling any programming project is not trying to solve everything at once. The program should be built out of smaller sections, such as helper functions. You should verify the operation of each part before moving on to the next. If you try to handle too much at once, most likely only chaos ensues.",
      "",
      "To do this you will need a way of testing your functions outside the main function. You can achieve this by defining a main function explicitly, and calling this function from outside any other function in the program. A single function call is then easy to comment out for testing. The first steps in building the following programming project could look like this:",
      "",
      "```python",
      "def main():",
      "    points = []",
      "    # your program code goes here",
      "",
      "main()",
      "```",
      "",
      "Now the helper functions can be tested without running the main function:",
      "",
      "```python",
      "# helper function for determining the grade based on the amount of points",
      "def grade(points):",
      "    # more code",
      "",
      "def main():",
      "    all_points = []",
      "    # your program code goes here",
      "",
      "# comment out the main function",
      "#main()",
      "",
      "# test the helper function",
      "student_points = 35",
      "result = grade(student_points)",
      "print(result)",
      "```",
      "",
      "## Passing data from one function to another",
      "",
      "When a program contains multiple functions, the question arises: how do you pass data from one function to another?",
      "",
      "The following example asks the user for some integer values. The program then prints out these values and performs an \"analysis\" on them. The program is divided into three separate functions:",
      "",
      "```python",
      "def input_from_user(how_many: int):",
      "    print(f\"Please type in {how_many} numbers:\")",
      "    numbers = []",
      "",
      "    for i in range(how_many):",
      "        number = int(input(f\"Number {i+1}: \"))",
      "        numbers.append(number)",
      "",
      "    return numbers",
      "",
      "def print_result(numbers: list):",
      "    print(\"The numbers are: \")",
      "    for number in numbers:",
      "        print(number)",
      "",
      "def analyze(numbers: list):",
      "    mean = sum(numbers) / len(numbers)",
      "    return f\"There are altogether {len(numbers)} numbers, the mean is {mean}, the smallest is {min(numbers)} and the greatest is {max(numbers)}\"",
      "",
      "# the \"main function\" using these functions",
      "inputs = input_from_user(5)",
      "print_result(inputs)",
      "analysis_result = analyze(inputs)",
      "print(analysis_result)",
      "```",
      "",
      "When the program is executed, it could go like this:",
      "",
      "```text",
      "Please type in 5 numbers:",
      "Number 1: 10",
      "Number 2: 34",
      "Number 3: -32",
      "Number 4: 99",
      "Number 5: -53",
      "The numbers are:",
      "10",
      "34",
      "-32",
      "99",
      "-53",
      "There are altogether 5 numbers, the mean is 11.6, the smallest is -53 and the greatest is 99",
      "```",
      "",
      "The idea here is that the main function \"saves\" all data processed by the program. In this case all that is needed is the input from the user in the variable `inputs`.",
      "",
      "If the input is needed in a function, it is passed as an argument. This happens with the functions `print_result` and `analyze`. If the function produces data that is needed elsewhere in the program, the function returns it with the `return` command, and it is stored in a variable in the main function. This happens with the functions `input_from_user` and `analyze`.",
      "",
      "You could use the global variable `inputs` from the main function directly in the helper functions. We have already covered why that is a bad idea. If functions are able to change a global variable, unexpected things may start happening in the program, especially when the number of functions grows large.",
      "",
      "Passing data into and out of functions is best handled by arguments and return values.",
      "",
      "You could also separate the implicit main function in the example above into its own function. Then the variable `inputs` would no longer be a global variable, but instead a local variable within the `main` function:",
      "",
      "```python",
      "# your main function goes here",
      "def main():",
      "    inputs = input_from_user(5)",
      "    print_result(inputs)",
      "    analysis_result = analyze(inputs)",
      "",
      "    print(analysis_result)",
      "",
      "# run the main function",
      "main()",
      "```"
    ].join("\n"),
    CAS: [
      "## Desarrollando un proyecto de programación más grande",
      "",
      "Esta cuarta parte culmina en un proyecto de programación ligeramente más grande, donde puedes aplicar muchas de las técnicas aprendidas hasta ahora.",
      "",
      "La regla número 1 al abordar cualquier proyecto de programación es no intentar resolver todo a la vez. El programa debe construirse a partir de secciones más pequeñas, como funciones auxiliares. Debes verificar el funcionamiento de cada parte antes de pasar a la siguiente. Si intentas manejar demasiado a la vez, lo más probable es que solo surja el caos.",
      "",
      "Para hacer esto, necesitarás una forma de probar tus funciones fuera de la función principal. Puedes lograr esto definiendo una función principal explícitamente y llamando a esta función desde fuera de cualquier otra función en el programa. Una sola llamada a función es entonces fácil de comentar para las pruebas. Los primeros pasos para construir el siguiente proyecto de programación podrían verse así:",
      "",
      "```python",
      "def main():",
      "    puntos = []",
      "    # tu código de programa va aquí",
      "",
      "main()",
      "```",
      "",
      "Ahora las funciones auxiliares se pueden probar sin ejecutar la función principal:",
      "",
      "```python",
      "# función auxiliar para determinar la calificación basada en la cantidad de puntos",
      "def nota(puntos):",
      "    # más código",
      "",
      "def main():",
      "    todos_puntos = []",
      "    # tu código de programa va aquí",
      "",
      "# comenta la función principal",
      "#main()",
      "",
      "# prueba la función auxiliar",
      "puntos_estudiante = 35",
      "resultado = nota(puntos_estudiante)",
      "print(resultado)",
      "```",
      "",
      "## Pasando datos de una función a otra",
      "",
      "Cuando un programa contiene múltiples funciones, surge la pregunta: ¿cómo pasas datos de una función a otra?",
      "",
      "El siguiente ejemplo pide al usuario algunos valores enteros. Luego, el programa imprime estos valores y realiza un \"análisis\" sobre ellos. El programa se divide en tres funciones separadas:",
      "",
      "```python",
      "def entrada_usuario(cuantos: int):",
      "    print(f\"Por favor escribe {cuantos} números:\")",
      "    numeros = []",
      "",
      "    for i in range(cuantos):",
      "        numero = int(input(f\"Número {i+1}: \"))",
      "        numeros.append(numero)",
      "",
      "    return numeros",
      "",
      "def imprimir_resultado(numeros: list):",
      "    print(\"Los números son: \")",
      "    for numero in numeros:",
      "        print(numero)",
      "",
      "def analizar(numeros: list):",
      "    media = sum(numeros) / len(numeros)",
      "    return f\"Hay en total {len(numeros)} números, la media es {media}, el menor es {min(numeros)} y el mayor es {max(numeros)}\"",
      "",
      "# la \"función principal\" usando estas funciones",
      "entradas = entrada_usuario(5)",
      "imprimir_resultado(entradas)",
      "resultado_analisis = analizar(entradas)",
      "print(resultado_analisis)",
      "```",
      "",
      "Cuando se ejecuta el programa, podría ir así:",
      "",
      "```text",
      "Por favor escribe 5 números:",
      "Número 1: 10",
      "Número 2: 34",
      "Número 3: -32",
      "Número 4: 99",
      "Número 5: -53",
      "Los números son:",
      "10",
      "34",
      "-32",
      "99",
      "-53",
      "Hay en total 5 números, la media es 11.6, el menor es -53 y el mayor es 99",
      "```",
      "",
      "La idea aquí es que la función principal \"guarda\" todos los datos procesados por el programa. En este caso, todo lo que se necesita es la entrada del usuario en la variable `entradas`.",
      "",
      "Si la entrada se necesita en una función, se pasa como argumento. Esto sucede con las funciones `imprimir_resultado` y `analizar`. Si la función produce datos que se necesitan en otra parte del programa, la función los devuelve con el comando `return`, y se almacena en una variable en la función principal. Esto sucede con las funciones `entrada_usuario` y `analizar`.",
      "",
      "Podrías usar la variable global `entradas` desde la función principal directamente en las funciones auxiliares. Ya hemos cubierto por qué eso es una mala idea. Si las funciones pueden cambiar una variable global, pueden empezar a suceder cosas inesperadas en el programa, especialmente cuando el número de funciones crece mucho.",
      "",
      "Pasar datos dentro y fuera de las funciones se maneja mejor mediante argumentos y valores de retorno.",
      "",
      "También podrías separar la función principal implícita en el ejemplo anterior en su propia función. Entonces la variable `entradas` ya no sería una variable global, sino una variable local dentro de la función `main`:",
      "",
      "```python",
      "# tu función principal va aquí",
      "def main():",
      "    entradas = entrada_usuario(5)",
      "    imprimir_resultado(entradas)",
      "    resultado_analisis = analizar(entradas)",
      "",
      "    print(resultado_analisis)",
      "",
      "# ejecutar la función principal",
      "main()",
      "```"
    ].join("\n"),
    EUS: [
      "## Programazio proiektu handiago bat garatzen",
      "",
      "Laugarren zati hau programazio proiektu apur bat handiago batean amaitzen da, non orain arte ikasitako teknika asko aplikatu ahal izango dituzun.",
      "",
      "Edozein programazio proiekturi ekiteko 1. araua dena batera konpontzen ez saiatzea da. Programa atal txikiagoetatik eraiki behar da, hala nola funtzio laguntzaileetatik. Zati bakoitzaren funtzionamendua egiaztatu beharko zenuke hurrengora pasa aurretik. Dena batera kudeatzen saiatzen bazara, ziurrenik kaosa bakarrik sortuko da.",
      "",
      "Hau egiteko zure funtzioak funtzio nagusitik kanpo probatzeko modu bat beharko duzu. Hori lortzeko, funtzio nagusi bat esplizituki defini dezakezu, eta funtzio honi programako beste edozein funtziotatik kanpo deitu. Funtzio dei bakar bat erraz komentatzen da probak egiteko. Hurrengo programazio proiektua eraikitzeko lehen urratsak honelakoak izan litezke:",
      "",
      "```python",
      "def main():",
      "    puntuak = []",
      "    # zure programa kodea hemen doa",
      "",
      "main()",
      "```",
      "",
      "Orain funtzio laguntzaileak probatu daitezke funtzio nagusia exekutatu gabe:",
      "",
      "```python",
      "# puntu kopuruaren arabera nota zehazteko funtzio laguntzailea",
      "def nota(puntuak):",
      "    # kode gehiago",
      "",
      "def main():",
      "    puntu_guztiak = []",
      "    # zure programa kodea hemen doa",
      "",
      "# komentatu funtzio nagusia",
      "#main()",
      "",
      "# probatu funtzio laguntzailea",
      "ikasle_puntuak = 35",
      "emaitza = nota(ikasle_puntuak)",
      "print(emaitza)",
      "```",
      "",
      "## Datuak funtzio batetik bestera pasatzen",
      "",
      "Programa batek funtzio anitz dituenean, galdera sortzen da: nola pasatzen dituzu datuak funtzio batetik bestera?",
      "",
      "Hurrengo adibideak erabiltzaileari balio oso batzuk eskatzen dizkio. Ondoren, programak balio horiek inprimatzen ditu eta haien gaineko \"analisi\" bat egiten du. Programa hiru funtzio bereizitan banatuta dago:",
      "",
      "```python",
      "def sarrera_erabiltzailetik(zenbat: int):",
      "    print(f\"Mesedez idatzi {zenbat} zenbaki:\")",
      "    zenbakiak = []",
      "",
      "    for i in range(zenbat):",
      "        zenbakia = int(input(f\"Zenbakia {i+1}: \"))",
      "        zenbakiak.append(zenbakia)",
      "",
      "    return zenbakiak",
      "",
      "def inprimatu_emaitza(zenbakiak: list):",
      "    print(\"Zenbakiak dira: \")",
      "    for zenbakia in zenbakiak:",
      "        print(zenbakia)",
      "",
      "def analizatu(zenbakiak: list):",
      "    batezbestekoa = sum(zenbakiak) / len(zenbakiak)",
      "    return f\"Guztira {len(zenbakiak)} zenbaki daude, batezbestekoa {batezbestekoa} da, txikiena {min(zenbakiak)} da eta handiena {max(zenbakiak)}\"",
      "",
      "# \"funtzio nagusia\" funtzio hauek erabiltzen",
      "sarrerak = sarrera_erabiltzailetik(5)",
      "inprimatu_emaitza(sarrerak)",
      "analisi_emaitza = analizatu(sarrerak)",
      "print(analisi_emaitza)",
      "```",
      "",
      "Programa exekutatzen denean, honela joan liteke:",
      "",
      "```text",
      "Mesedez idatzi 5 zenbaki:",
      "Zenbakia 1: 10",
      "Zenbakia 2: 34",
      "Zenbakia 3: -32",
      "Zenbakia 4: 99",
      "Zenbakia 5: -53",
      "Zenbakiak dira:",
      "10",
      "34",
      "-32",
      "99",
      "-53",
      "Guztira 5 zenbaki daude, batezbestekoa 11.6 da, txikiena -53 da eta handiena 99",
      "```",
      "",
      "Ideia hemen funtzio nagusiak programak prozesatutako datu guztiak \"gordetzen\" dituela da. Kasu honetan behar den guztia erabiltzailearen sarrera da `sarrerak` aldagaian.",
      "",
      "Sarrera funtzio batean behar bada, argumentu gisa pasatzen da. Hori `inprimatu_emaitza` eta `analizatu` funtzioekin gertatzen da. Funtzioak programan beste nonbait behar diren datuak sortzen baditu, funtzioak `return` komandoarekin itzultzen ditu, eta funtzio nagusiko aldagai batean gordetzen da. Hori `sarrera_erabiltzailetik` eta `analizatu` funtzioekin gertatzen da.",
      "",
      "Funtzio nagusiko `sarrerak` aldagai globala zuzenean erabil zenezake funtzio laguntzaileetan. Dagoeneko azaldu dugu zergatik den ideia txarra. Funtzioek aldagai global bat aldatzeko gai badira, ustekabeko gauzak gertatzen has daitezke programan, batez ere funtzio kopurua handitzen denean.",
      "",
      "Datuak funtzioetara sartzea eta ateratzea argumentu eta itzulera-balio bidez kudeatzen da ongien.",
      "",
      "Goiko adibideko funtzio nagusi inplizitua ere bere funtzioan bereiz zenezake. Orduan `sarrerak` aldagaia ez litzateke jada aldagai globala izango, baizik eta aldagai lokala `main` funtzioaren barruan:",
      "",
      "```python",
      "# zure funtzio nagusia hemen doa",
      "def main():",
      "    sarrerak = sarrera_erabiltzailetik(5)",
      "    inprimatu_emaitza(sarrerak)",
      "    analisi_emaitza = analizatu(sarrerak)",
      "",
      "    print(analisi_emaitza)",
      "",
      "# exekutatu funtzio nagusia",
      "main()",
      "```"
    ].join("\n")
  }
};

const exerciseGradeStatistics = {
  type: "exercise",
  exerciseId: "part04-38_grade_statistics",
  title: {
    ENG: "Grade statistics",
    CAS: "Estadísticas de calificaciones",
    EUS: "Kalifikazio estatistikak"
  },
  description: {
    ENG: "In this exercise you will write a program for printing out grade statistics for a university course. The program asks the user for results from different students on the course. These include exam points and numbers of exercises completed. The program then prints out statistics based on the results.",
    CAS: "En este ejercicio escribirás un programa para imprimir estadísticas de calificaciones de un curso universitario. El programa pide al usuario los resultados de diferentes estudiantes en el curso. Estos incluyen puntos de examen y número de ejercicios completados. El programa luego imprime estadísticas basadas en los resultados.",
    EUS: "Ariketa honetan unibertsitateko ikastaro bateko kalifikazio estatistikak inprimatzeko programa bat idatziko duzu. Programak ikastaroko ikasle desberdinen emaitzak eskatzen dizkio erabiltzaileari. Horien artean azterketa puntuak eta osatutako ariketa kopuruak daude. Programak ondoren emaitzetan oinarritutako estatistikak inprimatzen ditu."
  },
  initialCode: {
    ENG: "# Write your solution here",
    CAS: "# Escribe tu solución aquí",
    EUS: "# Idatzi zure soluzioa hemen"
  },
  testCode: ""
};

const section6 = {
  id: "part4-6",
  title: {
    ENG: "More strings and lists",
    CAS: "Más cadenas y listas",
    EUS: "Kate eta zerrenda gehiago"
  },
  blocks: [
    learningObjectives,
    introContent,
    exerciseEverythingReversed,
    stringsImmutableContent,
    exerciseMostCommonCharacter,
    exerciseNoVowelsAllowed,
    exerciseNoShoutingAllowed,
    exerciseNeighboursInList,
    largeProjectContent,
    exerciseGradeStatistics
  ]
};

const outputPath = path.join(__dirname, '../src/data/part4/section6.json');
fs.writeFileSync(outputPath, JSON.stringify(section6, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);