const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will know how to handle invalid input",
      "- You will understand what are exceptions in programming",
      "- You will be familiar with the most common exception types in Python",
      "- You will be able to handle exceptions in your own programs"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Sabrás cómo manejar entradas no válidas",
      "- Entenderás qué son las excepciones en programación",
      "- Estarás familiarizado con los tipos de excepciones más comunes en Python",
      "- Podrás manejar excepciones en tus propios programas"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Sarrera baliogabeak nola kudeatu jakingo duzu",
      "- Programazioan salbuespenak zer diren ulertuko duzu",
      "- Python-eko salbuespen mota ohikoenak ezagutuko dituzu",
      "- Zure programetan salbuespenak kudeatzeko gai izango zara"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "The are two basic categories of errors that come up in programming contexts:",
      "",
      "1. Syntax errors, which prevent the execution of the program",
      "2. Runtime errors, which halt the execution",
      "",
      "Errors in category 1 are usually easy to fix, as the Python interpreter flags the error location when attempting to execute the program. Common syntax errors include a missing colon at the end of a header line, or a missing quotation mark at the end of a string.",
      "",
      "Errors in category 2 can be harder to spot, as it may happen that they only occur at a certain point in the execution of a program, and only in certain circumstances. The program may work just fine in most situations, but halt due to an error in a specific marginal case. We will now concentrate on handling these types of errors.",
      "",
      "## Input validation",
      "",
      "Many errors that come up during the execution of a program have to do with invalid input. Some examples include:",
      "",
      "* missing or empty input values in mandatory fields, such as empty strings when the length of the string is critical",
      "* negative values where only positive values are accepted, such as -15 as the amount of an ingredient in a recipe",
      "* missing files or typos in filenames",
      "* values that are too small or too large, for example when working with dates and times",
      "* invalid indexes, such as trying to access index 3 in the string \"hey\"",
      "* values of a wrong type, such as strings when integers are expected",
      "",
      "Fortunately, we as programmers can prepare for most errors. Let's have a look at a program which asks the user for their age, and makes sure it is an acceptable number (between 0 and 150, in this case):",
      "",
      "```python",
      "age = int(input(\"Please type in your age: \"))",
      "if age >= 0 and age <= 150:",
      "    print(\"That is a fine age\")",
      "else:",
      "    print(\"This is not a valid age\")",
      "```",
      "",
      "```text",
      "Please type in your age: 25",
      "That is a fine age",
      "```",
      "",
      "```text",
      "Please type in your age: -3",
      "This is not a valid age",
      "```",
      "",
      "As long as the user types in an integer value, our input validation seems to work fine. But what if they type in a string?",
      "",
      "```text",
      "Please type in your age: twenty-three",
      "ValueError: invalid literal for int() with base 10: 'twenty-three'",
      "```",
      "",
      "The `int` function is unable to parse the input string `twenty-three` as a valid integer value. The execution halts and the above error message is printed."
    ].join("\n"),
    CAS: [
      "Hay dos categorías básicas de errores que surgen en contextos de programación:",
      "",
      "1. Errores de sintaxis, que impiden la ejecución del programa",
      "2. Errores de tiempo de ejecución, que detienen la ejecución",
      "",
      "Los errores en la categoría 1 suelen ser fáciles de corregir, ya que el intérprete de Python marca la ubicación del error al intentar ejecutar el programa. Los errores de sintaxis comunes incluyen la falta de dos puntos al final de una línea de encabezado o la falta de comillas al final de una cadena.",
      "",
      "Los errores en la categoría 2 pueden ser más difíciles de detectar, ya que puede suceder que solo ocurran en cierto punto de la ejecución de un programa y solo en ciertas circunstancias. El programa puede funcionar bien en la mayoría de las situaciones, pero detenerse debido a un error en un caso marginal específico. Ahora nos concentraremos en manejar este tipo de errores.",
      "",
      "## Validación de entrada",
      "",
      "Muchos errores que surgen durante la ejecución de un programa tienen que ver con entradas no válidas. Algunos ejemplos incluyen:",
      "",
      "* valores de entrada faltantes o vacíos en campos obligatorios, como cadenas vacías cuando la longitud de la cadena es crítica",
      "* valores negativos donde solo se aceptan valores positivos, como -15 como la cantidad de un ingrediente en una receta",
      "* archivos faltantes o errores tipográficos en los nombres de archivo",
      "* valores demasiado pequeños o demasiado grandes, por ejemplo al trabajar con fechas y horas",
      "* índices no válidos, como intentar acceder al índice 3 en la cadena \"hey\"",
      "* valores de un tipo incorrecto, como cadenas cuando se esperan enteros",
      "",
      "Afortunadamente, nosotros como programadores podemos prepararnos para la mayoría de los errores. Echemos un vistazo a un programa que pide al usuario su edad y se asegura de que sea un número aceptable (entre 0 y 150, en este caso):",
      "",
      "```python",
      "edad = int(input(\"Por favor escribe tu edad: \"))",
      "if edad >= 0 and edad <= 150:",
      "    print(\"Esa es una buena edad\")",
      "else:",
      "    print(\"Esta no es una edad válida\")",
      "```",
      "",
      "```text",
      "Por favor escribe tu edad: 25",
      "Esa es una buena edad",
      "```",
      "",
      "```text",
      "Por favor escribe tu edad: -3",
      "Esta no es una edad válida",
      "```",
      "",
      "Mientras el usuario escriba un valor entero, nuestra validación de entrada parece funcionar bien. ¿Pero qué pasa si escribe una cadena?",
      "",
      "```text",
      "Por favor escribe tu edad: veintitrés",
      "ValueError: invalid literal for int() with base 10: 'veintitrés'",
      "```",
      "",
      "La función `int` no puede analizar la cadena de entrada `veintitrés` como un valor entero válido. La ejecución se detiene y se imprime el mensaje de error anterior."
    ].join("\n"),
    EUS: [
      "Programazio testuinguruetan sortzen diren erroreen oinarrizko bi kategoria daude:",
      "",
      "1. Sintaxi erroreak, programaren exekuzioa eragozten dutenak",
      "2. Exekuzio erroreak, exekuzioa gelditzen dutenak",
      "",
      "1. kategoriako erroreak konpontzen errazak izan ohi dira, Python interpreteak errorearen kokapena markatzen baitu programa exekutatzen saiatzean. Sintaxi errore ohikoen artean goiburu lerro baten amaieran bi puntu falta izatea edo kate baten amaieran komatxoak falta izatea daude.",
      "",
      "2. kategoriako erroreak antzematen zailagoak izan daitezke, gerta baitaiteke programa baten exekuzioaren puntu jakin batean bakarrik gertatzea, eta zirkunstantzia jakin batzuetan bakarrik. Programak ondo funtziona dezake egoera gehienetan, baina kasu marjinal zehatz batean errore baten ondorioz gelditu. Orain errore mota hauek kudeatzen zentratuko gara.",
      "",
      "## Sarrera balidazioa",
      "",
      "Programa baten exekuzioan sortzen diren errore asko sarrera baliogabeekin lotuta daude. Adibide batzuk:",
      "",
      "* derrigorrezko eremuetan sarrera balioak falta edo hutsik egotea, adibidez kate hutsak katearen luzera kritikoa denean",
      "* balio negatiboak balio positiboak bakarrik onartzen direnean, adibidez -15 errezeta bateko osagai kopuru gisa",
      "* fitxategiak falta izatea edo fitxategi-izenetan akatsak egotea",
      "* txikiegiak edo handiegiak diren balioak, adibidez data eta orduekin lan egitean",
      "* indize baliogabeak, adibidez \"hey\" katean 3. indizera sartzen saiatzea",
      "* okerreko motako balioak, adibidez kateak zenbaki osoak espero direnean",
      "",
      "Zorionez, programatzaile gisa errore gehienetarako prestatu gaitezke. Ikus dezagun erabiltzaileari bere adina galdetzen dion programa bat, eta zenbaki onargarria dela ziurtatzen duena (0 eta 150 artean, kasu honetan):",
      "",
      "```python",
      "adina = int(input(\"Mesedez idatzi zure adina: \"))",
      "if adina >= 0 and adina <= 150:",
      "    print(\"Adin ederra da hori\")",
      "else:",
      "    print(\"Hau ez da baliozko adina\")",
      "```",
      "",
      "```text",
      "Mesedez idatzi zure adina: 25",
      "Adin ederra da hori",
      "```",
      "",
      "```text",
      "Mesedez idatzi zure adina: -3",
      "Hau ez da baliozko adina",
      "```",
      "",
      "Erabiltzaileak zenbaki oso bat idazten duen bitartean, gure sarrera balidazioak ondo funtzionatzen duela dirudi. Baina zer gertatzen da kate bat idazten badute?",
      "",
      "```text",
      "Mesedez idatzi zure adina: hogeita hiru",
      "ValueError: invalid literal for int() with base 10: 'hogeita hiru'",
      "```",
      "",
      "`int` funtzioa ez da gai `hogeita hiru` sarrera katea baliozko zenbaki oso gisa analizatzeko. Exekuzioa gelditu egiten da eta goiko errore mezua inprimatzen da."
    ].join("\n")
  }
};

const exceptionsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Exceptions",
      "",
      "Errors that occur while the program is already running are called *exceptions*. It is possible to prepare for exceptions, and handle them so that the execution continues despite them occurring.",
      "",
      "Exception handling in Python is accomplished with `try` and `except` statements. The idea is that if something within a `try` block causes an exception, Python checks if there is a corresponding `except` block. If such a block exists, it is executed and the program then continues as if nothing happened.",
      "",
      "Let's change the above example so that the program is prepared for the `ValueError` exception:",
      "",
      "```python",
      "try:",
      "    age = int(input(\"Please type in your age: \"))",
      "except ValueError:",
      "    age = -1",
      "",
      "if age >= 0 and age <= 150:",
      "    print(\"That is a fine age\")",
      "else:",
      "    print(\"This is not a valid age\")",
      "```",
      "",
      "```text",
      "Please type in your age: twenty-three",
      "This is not a valid age",
      "```",
      "",
      "We can use the `try` block to flag that the code within the block may cause an error. In the `except` statement directly after the block the relevant error is mentioned. In the above example we covered only a `ValueError` exception. If the exception had some other cause, the execution would still have halted, despite the `try` and `except` blocks.",
      "",
      "In the above example, if the error is caught, the value of `age` is set to -1. This is an invalid input value which we have already programmed behaviour for, as the program expects the age of the user to be greater than 0.",
      "",
      "In the following example we have a function `read_integer`, which asks the user to type in an integer value, but the function is also prepared for invalid input. The function keeps asking for integers until the user types in a valid input value.",
      "",
      "```python",
      "def read_integer():",
      "    while True:",
      "        try:",
      "            input_str = input(\"Please type in an integer: \")",
      "            return int(input_str)",
      "        except ValueError:",
      "            print(\"This input is invalid\")",
      "",
      "number = read_integer()",
      "print(\"Thank you!\")",
      "print(number, \"to the power of three is\", number**3)",
      "```",
      "",
      "```text",
      "Please type in an integer: three",
      "This input is invalid",
      "Please type in an integer: aybabtu",
      "This input is invalid",
      "Please type in an integer: 5",
      "Thank you!",
      "5 to the power of three is 125",
      "```"
    ].join("\n"),
    CAS: [
      "## Excepciones",
      "",
      "Los errores que ocurren mientras el programa ya se está ejecutando se llaman *excepciones*. Es posible prepararse para las excepciones y manejarlas para que la ejecución continúe a pesar de que ocurran.",
      "",
      "El manejo de excepciones en Python se logra con las declaraciones `try` y `except`. La idea es que si algo dentro de un bloque `try` causa una excepción, Python verifica si hay un bloque `except` correspondiente. Si tal bloque existe, se ejecuta y el programa continúa como si nada hubiera pasado.",
      "",
      "Cambiemos el ejemplo anterior para que el programa esté preparado para la excepción `ValueError`:",
      "",
      "```python",
      "try:",
      "    edad = int(input(\"Por favor escribe tu edad: \"))",
      "except ValueError:",
      "    edad = -1",
      "",
      "if edad >= 0 and edad <= 150:",
      "    print(\"Esa es una buena edad\")",
      "else:",
      "    print(\"Esta no es una edad válida\")",
      "```",
      "",
      "```text",
      "Por favor escribe tu edad: veintitrés",
      "Esta no es una edad válida",
      "```",
      "",
      "Podemos usar el bloque `try` para indicar que el código dentro del bloque puede causar un error. En la declaración `except` directamente después del bloque se menciona el error relevante. En el ejemplo anterior cubrimos solo una excepción `ValueError`. Si la excepción tuviera alguna otra causa, la ejecución aún se habría detenido, a pesar de los bloques `try` y `except`.",
      "",
      "En el ejemplo anterior, si se detecta el error, el valor de `edad` se establece en -1. Este es un valor de entrada no válido para el que ya hemos programado un comportamiento, ya que el programa espera que la edad del usuario sea mayor que 0.",
      "",
      "En el siguiente ejemplo tenemos una función `leer_entero`, que pide al usuario que escriba un valor entero, pero la función también está preparada para entradas no válidas. La función sigue pidiendo enteros hasta que el usuario escribe un valor de entrada válido.",
      "",
      "```python",
      "def leer_entero():",
      "    while True:",
      "        try:",
      "            cadena_entrada = input(\"Por favor escribe un entero: \")",
      "            return int(cadena_entrada)",
      "        except ValueError:",
      "            print(\"Esta entrada no es válida\")",
      "",
      "numero = leer_entero()",
      "print(\"¡Gracias!\")",
      "print(numero, \"elevado al cubo es\", numero**3)",
      "```",
      "",
      "```text",
      "Por favor escribe un entero: tres",
      "Esta entrada no es válida",
      "Por favor escribe un entero: aybabtu",
      "Esta entrada no es válida",
      "Por favor escribe un entero: 5",
      "¡Gracias!",
      "5 elevado al cubo es 125",
      "```"
    ].join("\n"),
    EUS: [
      "## Salbuespenak",
      "",
      "Programa exekutatzen ari den bitartean gertatzen diren erroreei *salbuespen* deitzen zaie. Salbuespenetarako prestatzea posible da, eta haiek kudeatzea exekuzioak aurrera egin dezan gertatu arren.",
      "",
      "Python-en salbuespenen kudeaketa `try` eta `except` sententziekin lortzen da. Ideia da `try` bloke baten barruan zerbaitek salbuespen bat eragiten badu, Python-ek egiaztatzen duela dagokion `except` bloke bat dagoen. Horrelako bloke bat existitzen bada, exekutatu egiten da eta programak ezer gertatu ez balitz bezala jarraitzen du.",
      "",
      "Alda dezagun goiko adibidea programa `ValueError` salbuespenerako prestatuta egon dadin:",
      "",
      "```python",
      "try:",
      "    adina = int(input(\"Mesedez idatzi zure adina: \"))",
      "except ValueError:",
      "    adina = -1",
      "",
      "if adina >= 0 and adina <= 150:",
      "    print(\"Adin ederra da hori\")",
      "else:",
      "    print(\"Hau ez da baliozko adina\")",
      "```",
      "",
      "```text",
      "Mesedez idatzi zure adina: hogeita hiru",
      "Hau ez da baliozko adina",
      "```",
      "",
      "`try` blokea erabil dezakegu blokearen barruko kodeak errore bat eragin dezakeela adierazteko. Blokearen ondorengo `except` sententzian errore garrantzitsua aipatzen da. Goiko adibidean `ValueError` salbuespena bakarrik estali dugu. Salbuespenak beste kausaren bat izan balu, exekuzioa oraindik ere geldituko zatekeen, `try` eta `except` blokeak egon arren.",
      "",
      "Goiko adibidean, errorea harrapatzen bada, `adina` balioa -1 ezartzen da. Hau jada programatuta daukagun sarrera balio baliogabe bat da, programak erabiltzailearen adina 0 baino handiagoa izatea espero baitu.",
      "",
      "Hurrengo adibidean `irakurri_osoa` funtzioa dugu, erabiltzaileari balio oso bat idazteko eskatzen diona, baina funtzioa sarrera baliogabeetarako ere prestatuta dago. Funtzioak zenbaki osoak eskatzen jarraitzen du erabiltzaileak baliozko sarrera bat idatzi arte.",
      "",
      "```python",
      "def irakurri_osoa():",
      "    while True:",
      "        try:",
      "            sarrera_katea = input(\"Mesedez idatzi zenbaki oso bat: \")",
      "            return int(sarrera_katea)",
      "        except ValueError:",
      "            print(\"Sarrera hau baliogabea da\")",
      "",
      "zenbakia = irakurri_osoa()",
      "print(\"Eskerrik asko!\")",
      "print(zenbakia, \"ber hiru da\", zenbakia**3)",
      "```",
      "",
      "```text",
      "Mesedez idatzi zenbaki oso bat: hiru",
      "Sarrera hau baliogabea da",
      "Mesedez idatzi zenbaki oso bat: aybabtu",
      "Sarrera hau baliogabea da",
      "Mesedez idatzi zenbaki oso bat: 5",
      "Eskerrik asko!",
      "5 ber hiru da 125",
      "```"
    ].join("\n")
  }
};

const exerciseReadInput = {
  type: "exercise",
  exerciseId: "part06-17_read_input",
  title: {
    ENG: "Reading input",
    CAS: "Leyendo entrada",
    EUS: "Sarrera irakurtzen"
  },
  description: {
    ENG: "Please write a function named `read_input`, which asks the user for input until the user types in an integer which falls within the bounds given as arguments to the function. The function should return the final valid integer value typed in by the user.",
    CAS: "Por favor escribe una función llamada `read_input`, que pida al usuario una entrada hasta que el usuario escriba un entero que caiga dentro de los límites dados como argumentos a la función. La función debe devolver el valor entero válido final escrito por el usuario.",
    EUS: "Mesedez idatzi `read_input` izeneko funtzio bat, erabiltzaileari sarrera eskatzen diona funtzioari argumentu gisa emandako mugen barruan dagoen zenbaki oso bat idatzi arte. Funtzioak erabiltzaileak idatzitako azken baliozko zenbaki osoa itzuli behar du."
  },
  initialCode: {
    ENG: [
      "def read_input(prompt, lower, upper):",
      "    # Write your solution here",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    number = read_input(\"Please type in a number: \", 5, 10)",
      "    print(\"You typed in:\", number)"
    ].join("\n"),
    CAS: [
      "def read_input(mensaje, inferior, superior):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    numero = read_input(\"Por favor escribe un número: \", 5, 10)",
      "    print(\"Escribiste:\", numero)"
    ].join("\n"),
    EUS: [
      "def read_input(mezua, behekoa, goikoa):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "if __name__ == \"__main__\":",
      "    zenbakia = read_input(\"Mesedez idatzi zenbaki bat: \", 5, 10)",
      "    print(\"Idatzi duzu:\", zenbakia)"
    ].join("\n")
  },
  testCode: ""
};

const raisingExceptionsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Raising exceptions",
      "",
      "You can also raise exceptions, with the command `raise`. It may seem like an odd idea to purposefully cause errors in your programs, but it can, in fact, be a very useful mechanism.",
      "",
      "For instance, it can sometimes be a good idea to raise an error when detecting invalid parameters. So far we have usually printed out messages when validating input, but if we are writing a function which is executed from elsewhere, just printing something out can go unnoticed when the function is called. Raising an error can make debugging easier.",
      "",
      "In the following example we have a function which calculates factorials (for example, the factorial of the number 5 is 1 * 2 * 3 * 4 * 5). If the argument passed to the function is negative, the function raises an error:",
      "",
      "```python",
      "def factorial(n):",
      "    if n < 0:",
      '        raise ValueError("The input was negative: " + str(n))',
      "    k = 1",
      "    for i in range(2, n + 1):",
      "        k *= i",
      "    return k",
      "",
      "print(factorial(3))",
      "print(factorial(6))",
      "print(factorial(-1))",
      "```",
      "",
      "```text",
      "6",
      "720",
      "Traceback (most recent call last):",
      "  File \"test.py\", line 11, in <module>",
      "    print(factorial(-1))",
      "  File \"test.py\", line 3, in factorial",
      "    raise ValueError(\"The input was negative: \" + str(n))",
      "ValueError: The input was negative: -1",
      "```"
    ].join("\n"),
    CAS: [
      "## Lanzando excepciones",
      "",
      "También puedes lanzar excepciones, con el comando `raise`. Puede parecer una idea extraña causar errores a propósito en tus programas, pero de hecho puede ser un mecanismo muy útil.",
      "",
      "Por ejemplo, a veces puede ser una buena idea lanzar un error al detectar parámetros no válidos. Hasta ahora, generalmente hemos impreso mensajes al validar la entrada, pero si estamos escribiendo una función que se ejecuta desde otro lugar, simplemente imprimir algo puede pasar desapercibido cuando se llama a la función. Lanzar un error puede facilitar la depuración.",
      "",
      "En el siguiente ejemplo tenemos una función que calcula factoriales (por ejemplo, el factorial del número 5 es 1 * 2 * 3 * 4 * 5). Si el argumento pasado a la función es negativo, la función lanza un error:",
      "",
      "```python",
      "def factorial(n):",
      "    if n < 0:",
      '        raise ValueError("La entrada fue negativa: " + str(n))',
      "    k = 1",
      "    for i in range(2, n + 1):",
      "        k *= i",
      "    return k",
      "",
      "print(factorial(3))",
      "print(factorial(6))",
      "print(factorial(-1))",
      "```",
      "",
      "```text",
      "6",
      "720",
      "Traceback (most recent call last):",
      "  File \"test.py\", line 11, in <module>",
      "    print(factorial(-1))",
      "  File \"test.py\", line 3, in factorial",
      "    raise ValueError(\"La entrada fue negativa: \" + str(n))",
      "ValueError: La entrada fue negativa: -1",
      "```"
    ].join("\n"),
    EUS: [
      "## Salbuespenak sortzen",
      "",
      "Salbuespenak ere sor ditzakezu, `raise` komandoarekin. Ideia arraroa eman dezake zure programetan nahita erroreak eragitea, baina, izan ere, oso mekanismo erabilgarria izan daiteke.",
      "",
      "Adibidez, batzuetan ideia ona izan daiteke errore bat sortzea parametro baliogabeak detektatzean. Orain arte mezuak inprimatu ohi ditugu sarrera balidatzean, baina beste nonbaitetik exekutatzen den funtzio bat idazten ari bagara, zerbait inprimatzea oharkabean pasa daiteke funtzioa deitzean. Errore bat sortzeak arazketa erraztu dezake.",
      "",
      "Hurrengo adibidean faktorialak kalkulatzen dituen funtzio bat dugu (adibidez, 5 zenbakiaren faktoriala 1 * 2 * 3 * 4 * 5 da). Funtzioari pasatako argumentua negatiboa bada, funtzioak errore bat sortzen du:",
      "",
      "```python",
      "def faktoriala(n):",
      "    if n < 0:",
      '        raise ValueError("Sarrera negatiboa zen: " + str(n))',
      "    k = 1",
      "    for i in range(2, n + 1):",
      "        k *= i",
      "    return k",
      "",
      "print(faktoriala(3))",
      "print(faktoriala(6))",
      "print(faktoriala(-1))",
      "```",
      "",
      "```text",
      "6",
      "720",
      "Traceback (most recent call last):",
      "  File \"test.py\", line 11, in <module>",
      "    print(faktoriala(-1))",
      "  File \"test.py\", line 3, in faktoriala",
      "    raise ValueError(\"Sarrera negatiboa zen: \" + str(n))",
      "ValueError: Sarrera negatiboa zen: -1",
      "```"
    ].join("\n")
  }
};

const exerciseParameterValidation = {
  type: "exercise",
  exerciseId: "part06-18_parameter_validation",
  title: {
    ENG: "Parameter validation",
    CAS: "Validación de parámetros",
    EUS: "Parametroen balidazioa"
  },
  description: {
    ENG: "Please write a function named `new_person(name: str, age: int)`, which creates and returns a tuple containing the data in the arguments. The function should throw a `ValueError` exception if the name is empty, too short, or too long, or if the age is negative or too large.",
    CAS: "Por favor escribe una función llamada `new_person(name: str, age: int)`, que cree y devuelva una tupla que contenga los datos en los argumentos. La función debe lanzar una excepción `ValueError` si el nombre está vacío, es demasiado corto o demasiado largo, o si la edad es negativa o demasiado grande.",
    EUS: "Mesedez idatzi `new_person(name: str, age: int)` izeneko funtzio bat, argumentuetako datuak dituen tupla bat sortu eta itzultzen duena. Funtzioak `ValueError` salbuespena bota behar du izena hutsik badago, laburregia edo luzeegia bada, edo adina negatiboa edo handiegia bada."
  },
  initialCode: {
    ENG: [
      "def new_person(name: str, age: int):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def new_person(nombre: str, edad: int):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def new_person(izena: str, adina: int):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const exerciseIncorrectLotteryNumbers = {
  type: "exercise",
  exerciseId: "part06-19_incorrect_lottery_numbers",
  title: {
    ENG: "Incorrect lottery numbers",
    CAS: "Números de lotería incorrectos",
    EUS: "Loteria zenbaki okerrak"
  },
  description: {
    ENG: "The file `lottery_numbers.csv` contains winning lottery numbers, but it has been corrupted. Please write a function named `filter_incorrect()`, which creates a file called `correct_numbers.csv` containing only the correctly formatted lines from the original file.",
    CAS: "El archivo `lottery_numbers.csv` contiene números ganadores de lotería, pero se ha corrompido. Por favor escribe una función llamada `filter_incorrect()`, que cree un archivo llamado `correct_numbers.csv` que contenga solo las líneas con formato correcto del archivo original.",
    EUS: "`lottery_numbers.csv` fitxategiak loteria zenbaki irabazleak ditu, baina hondatu egin da. Mesedez idatzi `filter_incorrect()` izeneko funtzio bat, `correct_numbers.csv` izeneko fitxategi bat sortzen duena jatorrizko fitxategiko formatu zuzena duten lerroak bakarrik dituena."
  },
  initialCode: {
    ENG: [
      "def filter_incorrect():",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def filter_incorrect():",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def filter_incorrect():",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const section3 = {
  id: "part6-3",
  title: {
    ENG: "Handling errors",
    CAS: "Manejo de errores",
    EUS: "Erroreak kudeatzen"
  },
  blocks: [
    learningObjectives,
    introContent,
    exceptionsContent,
    exerciseReadInput,
    raisingExceptionsContent,
    exerciseParameterValidation,
    exerciseIncorrectLotteryNumbers
  ]
};

const outputPath = path.join(__dirname, '../src/data/part6/section3.json');
fs.writeFileSync(outputPath, JSON.stringify(section3, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);
