const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will know what is meant by a local variable",
      "- You will know how the scope of a variable affects how it is used",
      "- You will know what the Python keyword `global` means",
      "- You will be able to use local and global variables in the correct contexts"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Sabrás qué se entiende por variable local",
      "- Sabrás cómo el ámbito de una variable afecta cómo se usa",
      "- Sabrás qué significa la palabra clave `global` en Python",
      "- Podrás usar variables locales y globales en los contextos correctos"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Aldagai lokal batekin zer esan nahi den jakingo duzu",
      "- Aldagai baten eremuak nola erabiltzen den nola eragiten duen jakingo duzu",
      "- Python-eko `global` hitz gakoak zer esan nahi duen jakingo duzu",
      "- Aldagai lokalak eta globalak testuinguru egokietan erabiltzeko gai izango zara"
    ].join("\n")
  }
};

const localVariablesContent = {
  type: "markdown",
  content: {
    ENG: [
      "The *scope* of a variable refers to the sections of a program where a variable is accessible. A *local* variable is only accessible in a defined section of the program, while a *global* variable is available for use in any section of the program.",
      "",
      "## Local variables",
      "",
      "Variables defined within a Python function are local variables, only available within the function. This applies to both function parameters, and other variables defined within the function definition. A variable which is local to a function *does not exist outside the function*.",
      "",
      "In the following example we are trying to access the variable `x` in the main function, but this causes an error:",
      "",
      "```python",
      "def testing():",
      "    x = 5",
      "    print(x)",
      "",
      "testing()",
      "print(x)",
      "```",
      "",
      "```text",
      "5",
      "NameError: name 'x' is not defined",
      "```",
      "",
      "The variable `x` only exists while the function `testing` is being executed. Other functions or the main function cannot access the variable."
    ].join("\n"),
    CAS: [
      "El *ámbito* de una variable se refiere a las secciones de un programa donde una variable es accesible. Una variable *local* solo es accesible en una sección definida del programa, mientras que una variable *global* está disponible para su uso en cualquier sección del programa.",
      "",
      "## Variables locales",
      "",
      "Las variables definidas dentro de una función Python son variables locales, solo disponibles dentro de la función. Esto se aplica tanto a los parámetros de la función como a otras variables definidas dentro de la definición de la función. Una variable que es local a una función *no existe fuera de la función*.",
      "",
      "En el siguiente ejemplo estamos tratando de acceder a la variable `x` en la función principal, pero esto causa un error:",
      "",
      "```python",
      "def prueba():",
      "    x = 5",
      "    print(x)",
      "",
      "prueba()",
      "print(x)",
      "```",
      "",
      "```text",
      "5",
      "NameError: name 'x' is not defined",
      "```",
      "",
      "La variable `x` solo existe mientras se ejecuta la función `prueba`. Otras funciones o la función principal no pueden acceder a la variable."
    ].join("\n"),
    EUS: [
      "Aldagai baten *eremua* aldagai bat eskuragarri dagoen programako atalei dagokie. Aldagai *lokal* bat programaren atal zehatz batean bakarrik dago eskuragarri, eta aldagai *global* bat programaren edozein ataletan erabiltzeko eskuragarri dago.",
      "",
      "## Aldagai lokalak",
      "",
      "Python funtzio baten barruan definitutako aldagaiak aldagai lokalak dira, funtzioaren barruan bakarrik eskuragarri daudenak. Hau funtzioaren parametroei zein funtzioaren definizioaren barruan definitutako beste aldagai batzuei aplikatzen zaie. Funtzio baterako lokala den aldagai bat *ez da existitzen funtziotik kanpo*.",
      "",
      "Hurrengo adibidean `x` aldagaia funtzio nagusian atzitzen saiatzen ari gara, baina honek errore bat eragiten du:",
      "",
      "```python",
      "def proba():",
      "    x = 5",
      "    print(x)",
      "",
      "proba()",
      "print(x)",
      "```",
      "",
      "```text",
      "5",
      "NameError: name 'x' is not defined",
      "```",
      "",
      "`x` aldagaia `proba` funtzioa exekutatzen ari den bitartean bakarrik existitzen da. Beste funtzio batzuek edo funtzio nagusiak ezin dute aldagaia atzitu."
    ].join("\n")
  }
};

const globalVariablesContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Global variables",
      "",
      "Variables defined within the main function are global variables. We previously defined the main function as those sections of code in a Python program which do not fall within any other function. The value stored in a global variable can be accessed from any other function in the program, so the following does not cause any errors:",
      "",
      "```python",
      "def testing():",
      "    print(x)",
      "",
      "x = 3",
      "testing()",
      "```",
      "",
      "```text",
      "3",
      "```",
      "",
      "A global variable cannot be changed directly from within another function. The following function *has no effect* on the value stored in the global variable:",
      "",
      "```python",
      "def testing():",
      "    x = 5",
      "    print(x)",
      "",
      "x = 3",
      "testing()",
      "print(x)",
      "```",
      "",
      "```text",
      "5",
      "3",
      "```",
      "",
      "Here the function `testing` creates a *new, local* variable `x`, which \"masks\" the global variable while the function is being executed. This variable has the value 5, but it is a different variable than the global `x` which is defined in the main function.",
      "",
      "But what would the following code do?",
      "",
      "```python",
      "def testing():",
      "    print(x)",
      "    x = 5",
      "",
      "x = 3",
      "testing()",
      "print(x)",
      "```",
      "",
      "```text",
      "UnboundLocalError: local variable 'x' referenced before assignment",
      "```",
      "",
      "The function `testing` assigns a value to the variable `x`, so Python interprets `x` to be a local variable instead of the global variable of the same name. The function attempts to access the variable before it is defined, so there is an error.",
      "",
      "If we wish to specify that we mean to change the global variable within a function, we will need the Python keyword `global`:",
      "",
      "```python",
      "def testing():",
      "    global x",
      "    x = 3",
      "    print(x)",
      "",
      "x = 5",
      "testing()",
      "print(x)",
      "```",
      "",
      "```text",
      "3",
      "3",
      "```",
      "",
      "Now the assignment `x = 3` within the function also affects the main function. All sections of the program are using the same global variable `x`."
    ].join("\n"),
    CAS: [
      "## Variables globales",
      "",
      "Las variables definidas dentro de la función principal son variables globales. Anteriormente definimos la función principal como aquellas secciones de código en un programa Python que no caen dentro de ninguna otra función. Se puede acceder al valor almacenado en una variable global desde cualquier otra función del programa, por lo que lo siguiente no causa ningún error:",
      "",
      "```python",
      "def prueba():",
      "    print(x)",
      "",
      "x = 3",
      "prueba()",
      "```",
      "",
      "```text",
      "3",
      "```",
      "",
      "Una variable global no se puede cambiar directamente desde dentro de otra función. La siguiente función *no tiene efecto* sobre el valor almacenado en la variable global:",
      "",
      "```python",
      "def prueba():",
      "    x = 5",
      "    print(x)",
      "",
      "x = 3",
      "prueba()",
      "print(x)",
      "```",
      "",
      "```text",
      "5",
      "3",
      "```",
      "",
      "Aquí la función `prueba` crea una *nueva variable local* `x`, que \"oculta\" la variable global mientras se ejecuta la función. Esta variable tiene el valor 5, pero es una variable diferente a la `x` global que se define en la función principal.",
      "",
      "Pero, ¿qué haría el siguiente código?",
      "",
      "```python",
      "def prueba():",
      "    print(x)",
      "    x = 5",
      "",
      "x = 3",
      "prueba()",
      "print(x)",
      "```",
      "",
      "```text",
      "UnboundLocalError: local variable 'x' referenced before assignment",
      "```",
      "",
      "La función `prueba` asigna un valor a la variable `x`, por lo que Python interpreta que `x` es una variable local en lugar de la variable global del mismo nombre. La función intenta acceder a la variable antes de que se defina, por lo que hay un error.",
      "",
      "Si deseamos especificar que queremos cambiar la variable global dentro de una función, necesitaremos la palabra clave de Python `global`:",
      "",
      "```python",
      "def prueba():",
      "    global x",
      "    x = 3",
      "    print(x)",
      "",
      "x = 5",
      "prueba()",
      "print(x)",
      "```",
      "",
      "```text",
      "3",
      "3",
      "```",
      "",
      "Ahora la asignación `x = 3` dentro de la función también afecta a la función principal. Todas las secciones del programa están utilizando la misma variable global `x`."
    ].join("\n"),
    EUS: [
      "## Aldagai globalak",
      "",
      "Funtzio nagusiaren barruan definitutako aldagaiak aldagai globalak dira. Aurretik funtzio nagusia definitu genuen Python programa batean beste ezein funtzioren barruan ez dauden kode atal gisa. Aldagai global batean gordetako balioa programako beste edozein funtziotatik atzitu daiteke, beraz, hurrengoak ez du errorerik eragiten:",
      "",
      "```python",
      "def proba():",
      "    print(x)",
      "",
      "x = 3",
      "proba()",
      "```",
      "",
      "```text",
      "3",
      "```",
      "",
      "Aldagai global bat ezin da zuzenean aldatu beste funtzio baten barrutik. Hurrengo funtzioak *ez du eraginik* aldagai globalean gordetako balioan:",
      "",
      "```python",
      "def proba():",
      "    x = 5",
      "    print(x)",
      "",
      "x = 3",
      "proba()",
      "print(x)",
      "```",
      "",
      "```text",
      "5",
      "3",
      "```",
      "",
      "Hemen `proba` funtzioak `x` aldagai *lokal berri* bat sortzen du, aldagai globala \"ezkutatzen\" duena funtzioa exekutatzen ari den bitartean. Aldagai honek 5 balioa du, baina funtzio nagusian definitutako `x` globala baino aldagai desberdina da.",
      "",
      "Baina zer egingo luke hurrengo kodeak?",
      "",
      "```python",
      "def proba():",
      "    print(x)",
      "    x = 5",
      "",
      "x = 3",
      "proba()",
      "print(x)",
      "```",
      "",
      "```text",
      "UnboundLocalError: local variable 'x' referenced before assignment",
      "```",
      "",
      "`proba` funtzioak balio bat esleitzen dio `x` aldagaiari, beraz, Python-ek interpretatzen du `x` aldagai lokal bat dela izen bereko aldagai globalaren ordez. Funtzioa aldagaia definitu aurretik atzitzen saiatzen da, beraz, errore bat dago.",
      "",
      "Funtzio baten barruan aldagai globala aldatu nahi dugula zehaztu nahi badugu, Python-eko `global` hitz gakoa beharko dugu:",
      "",
      "```python",
      "def proba():",
      "    global x",
      "    x = 3",
      "    print(x)",
      "",
      "x = 5",
      "proba()",
      "print(x)",
      "```",
      "",
      "```text",
      "3",
      "3",
      "```",
      "",
      "Orain funtzio barruko `x = 3` esleipenak funtzio nagusiari ere eragiten dio. Programako atal guztiak `x` aldagai global bera erabiltzen ari dira."
    ].join("\n")
  }
};

const whenToUseGlobalContent = {
  type: "markdown",
  content: {
    ENG: [
      "## When should you use global variables?",
      "",
      "Global variables are not a way to bypass function parameters or return values, and they should not be used as such. That is, it is *possible* to write a function which stores its results directly in a global variable:",
      "",
      "```python",
      "def calculate_sum(a, b):",
      "    global result",
      "    result = a + b",
      "",
      "calculate_sum(2, 3)",
      "print(result)",
      "```",
      "",
      "It is better to write a function with a return value, as we are used to do by now:",
      "",
      "```python",
      "def calculate_sum(a, b):",
      "    return a + b",
      "",
      "result = calculate_sum(2, 3)",
      "print(result)",
      "```",
      "",
      "The advantage of the latter approach is that the function is an *independent* whole. It has certain, defined parameters, and it returns a result. It has no side effects, so it can be tested and changed independently of the other sections of the program.",
      "",
      "Global variables are useful in situations where we need to have some common, \"higher level\" information available to all functions in the program."
    ].join("\n"),
    CAS: [
      "## ¿Cuándo deberías usar variables globales?",
      "",
      "Las variables globales no son una forma de eludir los parámetros de función o los valores de retorno, y no deben usarse como tales. Es decir, es *posible* escribir una función que almacene sus resultados directamente en una variable global:",
      "",
      "```python",
      "def calcular_suma(a, b):",
      "    global resultado",
      "    resultado = a + b",
      "",
      "calcular_suma(2, 3)",
      "print(resultado)",
      "```",
      "",
      "Es mejor escribir una función con un valor de retorno, como estamos acostumbrados a hacer por ahora:",
      "",
      "```python",
      "def calcular_suma(a, b):",
      "    return a + b",
      "",
      "resultado = calcular_suma(2, 3)",
      "print(resultado)",
      "```",
      "",
      "La ventaja del último enfoque es que la función es un todo *independiente*. Tiene ciertos parámetros definidos y devuelve un resultado. No tiene efectos secundarios, por lo que se puede probar y cambiar independientemente de las otras secciones del programa.",
      "",
      "Las variables globales son útiles en situaciones en las que necesitamos tener alguna información común de \"nivel superior\" disponible para todas las funciones del programa."
    ].join("\n"),
    EUS: [
      "## Noiz erabili beharko zenituzke aldagai globalak?",
      "",
      "Aldagai globalak ez dira funtzio parametroak edo itzulera-balioak saihesteko modu bat, eta ez lirateke horrela erabili behar. Hau da, *posible* da emaitzak zuzenean aldagai global batean gordetzen dituen funtzio bat idaztea:",
      "",
      "```python",
      "def batura_kalkulatu(a, b):",
      "    global emaitza",
      "    emaitza = a + b",
      "",
      "batura_kalkulatu(2, 3)",
      "print(emaitza)",
      "```",
      "",
      "Hobe da itzulera-balioa duen funtzio bat idaztea, orain arte egitera ohitu garen bezala:",
      "",
      "```python",
      "def batura_kalkulatu(a, b):",
      "    return a + b",
      "",
      "emaitza = batura_kalkulatu(2, 3)",
      "print(emaitza)",
      "```",
      "",
      "Azken ikuspegi horren abantaila da funtzioa osotasun *independente* bat dela. Parametro zehatz eta definitu batzuk ditu, eta emaitza bat itzultzen du. Ez du albo-efekturik, beraz, probatu eta aldatu daiteke programako beste ataletatik independenteki.",
      "",
      "Aldagai globalak erabilgarriak dira programako funtzio guztientzat eskuragarri egon behar duen informazio komun, \"maila altuagoko\" bat behar dugun egoeretan."
    ].join("\n")
  }
};

const section4 = {
  id: "part6-4",
  title: {
    ENG: "Local and global variables",
    CAS: "Variables locales y globales",
    EUS: "Aldagai lokalak eta globalak"
  },
  blocks: [
    learningObjectives,
    localVariablesContent,
    globalVariablesContent,
    whenToUseGlobalContent
  ]
};

const outputPath = path.join(__dirname, '../src/data/part6/section4.json');
fs.writeFileSync(outputPath, JSON.stringify(section4, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);