const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will know how to use arguments to format the result of the `print` command",
      "- You will be able to use f-strings to format printouts"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Sabrás cómo usar argumentos para formatear el resultado del comando `print`",
      "- Serás capaz de usar f-strings para formatear impresiones"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- `print` komandoaren emaitza formateatzeko argumentuak nola erabili jakingo duzu",
      "- Inprimaketak formateatzeko f-kateak (f-strings) erabiltzeko gai izango zara"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "So far we have learnt three methods for formulating the argument given to the `print` command.",
      "",
      "The first is the `+` operator for strings. It allows simple concatenation of string segments:",
      "",
      "```python",
      "name = \"Mark\"",
      "age = 37",
      "print(\"Hi \" + name + \" your age is \" + str(age) + \" years\" )",
      "```",
      "",
      "This method will not work if any of the segments are not strings. In the example above, the variable `age` has been converted into a string with the `str` function, since it is an integer and cannot be concatenated as is.",
      "",
      "The second method is considering each segment of the argument as a separate argument, and splitting them up with commas:",
      "",
      "```python",
      "print(\"Hi\", name, \"your age is\", age, \"years\" )",
      "```",
      "",
      "This code produces the exact same result as the previous version. The `print` command normally adds a space character between each argument.The advantage here is that the segments can be of different types, so there is no need to convert anything into a string.",
      "",
      "If you want to remove the automatically added spaces, you can add a special named argument `sep`:",
      "",
      "```python",
      "print(\"Hi\", name, \"your age is\", age, \"years\", sep=\"\")",
      "```",
      "",
      "This prints out",
      "",
      "```text",
      "HiMarkyour age is37years",
      "```",
      "",
      "The argument `sep=\"\"` is a *keyword argument*, and its name is short for *separator*. It specifies that the other arguments should now be separated by an empty string. You can set the separator to any string you like. For example, if you wanted each argument on a separate line, you could set the separator to `\"\\n\"`, which is the newline character:",
      "",
      "```python",
      "print(\"Hi\", name, \"your age is\", age, \"years\", sep=\"\\n\")",
      "```",
      "",
      "```text",
      "Hi",
      "Mark",
      "your age is",
      "37",
      "years",
      "```",
      "",
      "By default, the print command always ends in a newline character, but you can change this as well. The keyword argument `end` specifies what is put at the end of a line. Setting `end` to an empty string means that there is no newline character at the end of the printout:",
      "",
      "```python",
      "print(\"Hi \", end=\"\")",
      "print(\"there!\")",
      "```",
      "",
      "```text",
      "Hi there!",
      "```",
      "",
      "## f-strings",
      "",
      "The third method to prepare strings is f-strings. The previous example with the name and the age would look like this formulated with f-strings:",
      "",
      "```python",
      "name = \"Erkki\"",
      "age = 39",
      "print(f\"Hi {name} your age is {age} years\")",
      "```",
      "",
      "Thus far we have only used very simple f-strings, but they can be very versatile in formatting string type content. One very common use case is setting the number of decimals that are printed out with a floating point number. By default the number is quite high:",
      "",
      "```python",
      "number = 1/3",
      "print(f\"The number is {number}\")",
      "```",
      "",
      "```text",
      "The number is 0.333333333333333",
      "```",
      "",
      "The specific format we want the number to be displayed in can be set within the curly brackets of the variable expression. Let's add a colon character and a *format specifier* after the variable name:",
      "",
      "```python",
      "number = 1/3",
      "print(f\"The number is {number:.2f}\")",
      "```",
      "",
      "```text",
      "The number is 0.33",
      "```",
      "",
      "The format specifier `.2f` states that we want to display 2 decimals. The letter *f* at the end means that we want the variable to be displayed as a `float`, i.e. a floating point number.",
      "",
      "Here's another example, where we specify the amount of whitespace reserved for the variable in the printout. Both times the variable `name` is included in the resulting string, it has a space of 15 characters reserved. First the names are justified to the left, and then they are justified to the right:",
      "",
      "```python",
      "names =  [ \"Steve\", \"Jean\", \"Katherine\", \"Paul\" ]",
      "for name in names:",
      "  print(f\"{name:15} centre {name:>15}\")",
      "```",
      "",
      "```text",
      "Steve           centre           Steve",
      "Jean            centre            Jean",
      "Katherine       centre       Katherine",
      "Paul            centre            Paul",
      "```",
      "",
      "The uses of f-strings are not restricted to `print` commands. They can be assigned to variables and combined with other strings:",
      "",
      "```python",
      "name = \"Larry\"",
      "age = 48",
      "city = \"Palo Alto\"",
      "greeting = f\"Hi {name}, you are {age} years of age\"",
      "print(greeting + f\", and you live in {city}\")",
      "```",
      "",
      "```text",
      "Hi Larry, you are 48 years of age, and you live in Palo Alto",
      "```",
      "",
      "You can think of an f-string as a sort of function, which creates a normal string based on the \"arguments\" within the curly brackets."
    ].join("\n"),
    CAS: [
      "Hasta ahora hemos aprendido tres métodos para formular el argumento dado al comando `print`.",
      "",
      "El primero es el operador `+` para cadenas. Permite la concatenación simple de segmentos de cadena:",
      "",
      "```python",
      "nombre = \"Mark\"",
      "edad = 37",
      "print(\"Hola \" + nombre + \" tu edad es \" + str(edad) + \" años\" )",
      "```",
      "",
      "Este método no funcionará si alguno de los segmentos no son cadenas. En el ejemplo anterior, la variable `edad` se ha convertido en una cadena con la función `str`, ya que es un entero y no se puede concatenar tal cual.",
      "",
      "El segundo método es considerar cada segmento del argumento como un argumento separado, y dividirlos con comas:",
      "",
      "```python",
      "print(\"Hola\", nombre, \"tu edad es\", edad, \"años\" )",
      "```",
      "",
      "Este código produce exactamente el mismo resultado que la versión anterior. El comando `print` normalmente añade un carácter de espacio entre cada argumento. La ventaja aquí es que los segmentos pueden ser de diferentes tipos, por lo que no hay necesidad de convertir nada en una cadena.",
      "",
      "Si quieres eliminar los espacios añadidos automáticamente, puedes añadir un argumento especial llamado `sep`:",
      "",
      "```python",
      "print(\"Hola\", nombre, \"tu edad es\", edad, \"años\", sep=\"\")",
      "```",
      "",
      "Esto imprime",
      "",
      "```text",
      "HolaMarktu edad es37años",
      "```",
      "",
      "El argumento `sep=\"\"` es un *argumento de palabra clave*, y su nombre es una abreviatura de *separador*. Especifica que los otros argumentos ahora deben estar separados por una cadena vacía. Puedes establecer el separador en cualquier cadena que desees. Por ejemplo, si quisieras cada argumento en una línea separada, podrías establecer el separador en `\"\\n\"`, que es el carácter de nueva línea:",
      "",
      "```python",
      "print(\"Hola\", nombre, \"tu edad es\", edad, \"años\", sep=\"\\n\")",
      "```",
      "",
      "```text",
      "Hola",
      "Mark",
      "tu edad es",
      "37",
      "años",
      "```",
      "",
      "Por defecto, el comando print siempre termina con un carácter de nueva línea, pero puedes cambiar esto también. El argumento de palabra clave `end` especifica qué se pone al final de una línea. Establecer `end` en una cadena vacía significa que no hay carácter de nueva línea al final de la impresión:",
      "",
      "```python",
      "print(\"Hola \", end=\"\")",
      "print(\"ahí!\")",
      "```",
      "",
      "```text",
      "Hola ahí!",
      "```",
      "",
      "## f-strings",
      "",
      "El tercer método para preparar cadenas son las f-strings (cadenas f). El ejemplo anterior con el nombre y la edad se vería así formulado con f-strings:",
      "",
      "```python",
      "nombre = \"Erkki\"",
      "edad = 39",
      "print(f\"Hola {nombre} tu edad es {edad} años\")",
      "```",
      "",
      "Hasta ahora solo hemos usado f-strings muy simples, pero pueden ser muy versátiles al formatear contenido de tipo cadena. Un caso de uso muy común es establecer el número de decimales que se imprimen con un número de punto flotante. Por defecto, el número es bastante alto:",
      "",
      "```python",
      "numero = 1/3",
      "print(f\"El número es {numero}\")",
      "```",
      "",
      "```text",
      "El número es 0.333333333333333",
      "```",
      "",
      "El formato específico en el que queremos que se muestre el número se puede establecer dentro de las llaves de la expresión variable. Vamos a añadir un carácter de dos puntos y un *especificador de formato* después del nombre de la variable:",
      "",
      "```python",
      "numero = 1/3",
      "print(f\"El número es {numero:.2f}\")",
      "```",
      "",
      "```text",
      "El número es 0.33",
      "```",
      "",
      "El especificador de formato `.2f` indica que queremos mostrar 2 decimales. La letra *f* al final significa que queremos que la variable se muestre como un `float`, es decir, un número de punto flotante.",
      "",
      "Aquí hay otro ejemplo, donde especificamos la cantidad de espacio en blanco reservado para la variable en la impresión. Ambas veces que la variable `nombre` se incluye en la cadena resultante, tiene un espacio de 15 caracteres reservado. Primero los nombres se justifican a la izquierda, y luego se justifican a la derecha:",
      "",
      "```python",
      "nombres =  [ \"Steve\", \"Jean\", \"Katherine\", \"Paul\" ]",
      "for nombre in nombres:",
      "  print(f\"{nombre:15} centro {nombre:>15}\")",
      "```",
      "",
      "```text",
      "Steve           centro           Steve",
      "Jean            centro            Jean",
      "Katherine       centro       Katherine",
      "Paul            centro            Paul",
      "```",
      "",
      "Los usos de las f-strings no se limitan a los comandos `print`. Se pueden asignar a variables y combinar con otras cadenas:",
      "",
      "```python",
      "nombre = \"Larry\"",
      "edad = 48",
      "ciudad = \"Palo Alto\"",
      "saludo = f\"Hola {nombre}, tienes {edad} años de edad\"",
      "print(saludo + f\", y vives en {ciudad}\")",
      "```",
      "",
      "```text",
      "Hola Larry, tienes 48 años de edad, y vives en Palo Alto",
      "```",
      "",
      "Puedes pensar en una f-string como una especie de función, que crea una cadena normal basada en los \"argumentos\" dentro de las llaves."
    ].join("\n"),
    EUS: [
      "Orain arte hiru metodo ikasi ditugu `print` komandoari ematen zaion argumentua formulatzeko.",
      "",
      "Lehenengoa kateentzako `+` eragilea da. Kate zatien elkarketa sinplea ahalbidetzen du:",
      "",
      "```python",
      "izena = \"Mark\"",
      "adina = 37",
      "print(\"Kaixo \" + izena + \" zure adina da \" + str(adina) + \" urte\" )",
      "```",
      "",
      "Metodo honek ez du funtzionatuko zatietakoren bat kateak ez badira. Goiko adibidean, `adina` aldagaia kate bihurtu da `str` funtzioarekin, osoko zenbakia baita eta ezin baita bere horretan elkartu.",
      "",
      "Bigarren metodoa argumentuaren zati bakoitza argumentu bereizi gisa hartzea da, eta komekin bereiztea:",
      "",
      "```python",
      "print(\"Kaixo\", izena, \"zure adina da\", adina, \"urte\" )",
      "```",
      "",
      "Kode honek aurreko bertsioaren emaitza zehatz bera sortzen du. `print` komandoak normalean espazio karaktere bat gehitzen du argumentu bakoitzaren artean. Hemen abantaila zatiak mota desberdinetakoak izan daitezkeela da, beraz, ez dago ezer kate bihurtu beharrik.",
      "",
      "Automatikoki gehitutako espazioak kendu nahi badituzu, `sep` izeneko argumentu berezia gehi dezakezu:",
      "",
      "```python",
      "print(\"Kaixo\", izena, \"zure adina da\", adina, \"urte\", sep=\"\")",
      "```",
      "",
      "Honek hau inprimatzen du",
      "",
      "```text",
      "KaixoMarkzure adina da37urte",
      "```",
      "",
      "`sep=\"\"` argumentua *hitz gako argumentua* da, eta bere izena *separator* (bereizle) hitzaren laburdura da. Beste argumentuak orain kate huts batekin bereizi behar direla zehazten du. Bereizlea nahi duzun edozein katetara ezar dezakezu. Adibidez, argumentu bakoitza lerro bereizi batean nahi bazenu, bereizlea `\"\\n\"`-ra ezar zenezake, hau da, lerro berri karakterea:",
      "",
      "```python",
      "print(\"Kaixo\", izena, \"zure adina da\", adina, \"urte\", sep=\"\\n\")",
      "```",
      "",
      "```text",
      "Kaixo",
      "Mark",
      "zure adina da",
      "37",
      "urte",
      "```",
      "",
      "Lehenespenez, print komandoa beti lerro berri karaktere batekin amaitzen da, baina hau ere alda dezakezu. `end` hitz gako argumentuak zehazten du zer jartzen den lerro baten amaieran. `end` kate huts batera ezartzeak esan nahi du ez dagoela lerro berri karaktererik inprimaketaren amaieran:",
      "",
      "```python",
      "print(\"Kaixo \", end=\"\")",
      "print(\"hor!\")",
      "```",
      "",
      "```text",
      "Kaixo hor!",
      "```",
      "",
      "## f-strings",
      "",
      "Kateak prestatzeko hirugarren metodoa f-strings (f-kateak) dira. Izena eta adinarekin aurreko adibidea horrela ikusiko litzateke f-string-ekin formulatuta:",
      "",
      "```python",
      "izena = \"Erkki\"",
      "adina = 39",
      "print(f\"Kaixo {izena}, {adina} urte dituzu\" )",
      "```",
      "",
      "Orain arte f-kate oso sinpleak bakarrik erabili ditugu, baina oso moldakorrak izan daitezke kate motako edukia formateatzean. Erabilera kasu oso ohiko bat koma mugikorreko zenbaki batekin inprimatzen diren hamartar kopurua ezartzea da. Lehenespenez kopurua nahiko handia da:",
      "",
      "```python",
      "zenbakia = 1/3",
      "print(f\"Zenbakia da {zenbakia}\")",
      "```",
      "",
      "```text",
      "Zenbakia da 0.333333333333333",
      "```",
      "",
      "Zenbakia bistaratzea nahi dugun formatu zehatza aldagai adierazpenaren giltzen barruan ezar daiteke. Gehi ditzagun bi puntu karaktere bat eta *formatu zehazle* bat aldagai izenaren ondoren:",
      "",
      "```python",
      "zenbakia = 1/3",
      "print(f\"Zenbakia da {zenbakia:.2f}\")",
      "```",
      "",
      "```text",
      "Zenbakia da 0.33",
      "```",
      "",
      "`.2f` formatu zehazleak 2 hamartar bistaratu nahi ditugula adierazten du. Amaierako *f* letrak aldagaia `float` gisa bistaratu nahi dugula esan nahi du, hau da, koma mugikorreko zenbaki gisa.",
      "",
      "Hona hemen beste adibide bat, non aldagaiarentzat inprimaketan gordetako zuriune kopurua zehazten dugun. `izena` aldagaia ondoriozko katean sartzen den bi aldietan, 15 karaktereko espazioa du gordeta. Lehenik izenak ezkerretara justifikatzen dira, eta gero eskuinera justifikatzen dira:",
      "",
      "```python",
      "izenak =  [ \"Steve\", \"Jean\", \"Katherine\", \"Paul\" ]",
      "for izena in izenak:",
      "  print(f\"{izena:15} zentroa {izena:>15}\")",
      "```",
      "",
      "```text",
      "Steve           zentroa           Steve",
      "Jean            zentroa            Jean",
      "Katherine       zentroa       Katherine",
      "Paul            zentroa            Paul",
      "```",
      "",
      "f-kateen erabilerak ez daude `print` komandoetara mugatuta. Aldagaiei esleitu eta beste kate batzuekin konbina daitezke:",
      "",
      "```python",
      "izena = \"Larry\"",
      "adina = 48",
      "hiria = \"Palo Alto\"",
      "agurra = f\"Kaixo {izena}, {adina} urte dituzu\"",
      "print(agurra + f\", eta {hiria}-n bizi zara\")",
      "```",
      "",
      "```text",
      "Kaixo Larry, 48 urte dituzu, eta Palo Alto-n bizi zara",
      "```",
      "",
      "F-kate bat funtzio moduko bat bezala pentsa dezakezu, giltzen barruko \"argumentuetan\" oinarritutako kate normal bat sortzen duena."
    ].join("\n")
  }
};

const exerciseIntegersToStrings = {
  type: "exercise",
  exerciseId: "part04-32_integers_to_strings",
  title: {
    ENG: "Integers to strings",
    CAS: "Enteros a cadenas",
    EUS: "Osokoak kateetara"
  },
  description: {
    ENG: "Please write a function named `formatted`, which takes a list of floating point numbers as its argument. The function returns a new list, which contains each element of the original list in string format, rounded to two decimal points. The order of the items in the list should remain unchanged.",
    CAS: "Por favor escribe una función llamada `formatted`, que tome una lista de números de punto flotante como argumento. La función devuelve una nueva lista, que contiene cada elemento de la lista original en formato de cadena, redondeado a dos decimales. El orden de los elementos en la lista debe permanecer sin cambios.",
    EUS: "Mesedez idatzi `formatted` izeneko funtzio bat, koma mugikorreko zenbakien zerrenda bat argumentu gisa hartzen duena. Funtzioak zerrenda berri bat itzultzen du, jatorrizko zerrendako elementu bakoitza kate formatuan duena, bi dezimaletara biribilduz. Zerrendako elementuen ordenak aldatu gabe egon behar du."
  },
  initialCode: {
    ENG: [
      "def formatted(my_list: list):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def formatted(mi_lista: list):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def formatted(nire_zerrenda: list):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const section5 = {
  id: "part4-5",
  title: {
    ENG: "Print statement formatting",
    CAS: "Formato de declaraciones de impresión",
    EUS: "Inprimaketa sententziaren formateatzea"
  },
  blocks: [
    learningObjectives,
    introContent,
    exerciseIntegersToStrings
  ]
};

const outputPath = path.join(__dirname, '../src/data/part4/section5.json');
fs.writeFileSync(outputPath, JSON.stringify(section5, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);
