const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will be familiar with some more Python features"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Estarás familiarizado con algunas características más de Python"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Python-en ezaugarri gehiago ezagutuko dituzu"
    ].join("\n")
  }
};

const moreFeaturesContent = {
  type: "markdown",
  content: {
    ENG: [
      "To finish off this course, here you will find various useful Python features.",
      "",
      "## Single line conditionals",
      "",
      "The following two statements produce the exact same results:",
      "",
      "```python",
      "if x%2 == 0:",
      "    print(\"even\")",
      "else:",
      "    print(\"odd\")",
      "```",
      "",
      "```python",
      "print(\"even\" if x%2 == 0 else \"odd\")",
      "```",
      "",
      "In the latter example we have a conditional expression on a single line: `a if [condition] else b`. The value of this expression evaluates to `a` if the condition is true, and `b` if it is false. This structure is sometimes referred to as a *ternary operator*.",
      "",
      "Conditional expressions can be very useful when you need to assign something *conditionally*. For example, if you had the variables `x` and `y`, and you wanted to either increment or set the value of `y` depending on the parity of `x`, you could write it in a normal `if else` statement, like so:",
      "",
      "```python",
      "if x%2 == 0:",
      "    y += 1",
      "else:",
      "    y = 0",
      "```",
      "",
      "The same could be achieved with a nifty one-liner:",
      "",
      "```python",
      "y = y + 1 if x%2 == 0 else 0",
      "```",
      "",
      "## An \"empty\" block",
      "",
      "You may remember from the previous part that you are not allowed to have an empty block in a Python program. If you need to have a block of code which does nothing, for example when testing some other functionality, the `pass` command will let you do this. You could, for instance, write a function which does nothing:",
      "",
      "```python",
      "def testing():",
      "    pass",
      "```",
      "",
      "This function would simply return immediately. Leaving the `pass` command out, i.e. having a completely empty block, would produce an error.",
      "",
      "```python",
      "def testing():  # this causes an error!",
      "```",
      "",
      "## Loops with else blocks",
      "",
      "In Python, loops can have `else` blocks, too. This section of code is executed if the loop finishes normally.",
      "",
      "For example, in the following example we are looking through a list of numbers. If there is an even number on the list, the program prints out a message and the loop is broken. If there are no even numbers, the loop finishes normally, but a different message is then printed out.",
      "",
      "```python",
      "my_list = [3,5,2,8,1]",
      "for x in my_list:",
      "    if x%2 == 0:",
      "        print(\"found an even number\", x)",
      "        break",
      "else:",
      "    print(\"there were no even numbers\")",
      "```",
      "",
      "A more traditional way to achieve this would be to use a helper variable to remember whether the desired item was found:",
      "",
      "```python",
      "my_list = [3,5,2,8,1]",
      "found = False",
      "for x in my_list:",
      "    if x%2 == 0:",
      "        print(\"found an even number\", x)",
      "        found = True",
      "        break",
      "if not found:",
      "    print(\"there were no even numbers\")",
      "```",
      "",
      "Using a `for else` statement saves us the trouble of writing a separate variable.",
      "",
      "## Default parameter value",
      "",
      "A Python function can have a default parameter value. It is used whenever no argument is passed to the function. See the following example:",
      "",
      "```python",
      "def say_hello(name=\"Emily\"):",
      "    print(\"Hi there,\", name)",
      "",
      "say_hello()",
      "say_hello(\"Eric\")",
      "say_hello(\"Matthew\")",
      "say_hello(\"\")",
      "```",
      "",
      "```text",
      "Hi there, Emily",
      "Hi there, Eric",
      "Hi there, Matthew",
      "Hi there,",
      "```",
      "",
      "NB: an empty string is still a string, so the default parameter is not used if an empty string is passed to the function.",
      "",
      "## A variable number of parameters",
      "",
      "You can also define a function with a variable number of parameters, by adding a star before the parameter name. All the remaining arguments passed to the function are contained in a tuple, and can be accessed through the named parameter.",
      "",
      "The following function counts the number and sum of its arguments:",
      "",
      "```python",
      "def testing(*my_args):",
      "    print(\"You passed\", len(my_args), \"arguments\")",
      "    print(\"The sum of the arguments is\", sum(my_args))",
      "",
      "testing(1, 2, 3, 4, 5)",
      "```",
      "",
      "```text",
      "You passed 5 arguments",
      "The sum of the arguments is 15",
      "```"
    ].join("\n"),
    CAS: [
      "Para terminar este curso, aquí encontrarás varias características útiles de Python.",
      "",
      "## Condicionales de una sola línea",
      "",
      "Las siguientes dos declaraciones producen exactamente los mismos resultados:",
      "",
      "```python",
      "if x%2 == 0:",
      "    print(\"par\")",
      "else:",
      "    print(\"impar\")",
      "```",
      "",
      "```python",
      "print(\"par\" if x%2 == 0 else \"impar\")",
      "```",
      "",
      "En el último ejemplo tenemos una expresión condicional en una sola línea: `a if [condición] else b`. El valor de esta expresión se evalúa como `a` si la condición es verdadera, y `b` si es falsa. Esta estructura a veces se denomina *operador ternario*.",
      "",
      "Las expresiones condicionales pueden ser muy útiles cuando necesitas asignar algo *condicionalmente*. Por ejemplo, si tuvieras las variables `x` e `y`, y quisieras incrementar o establecer el valor de `y` dependiendo de la paridad de `x`, podrías escribirlo en una declaración normal `if else`, así:",
      "",
      "```python",
      "if x%2 == 0:",
      "    y += 1",
      "else:",
      "    y = 0",
      "```",
      "",
      "Lo mismo se podría lograr con una ingeniosa línea:",
      "",
      "```python",
      "y = y + 1 if x%2 == 0 else 0",
      "```",
      "",
      "## Un bloque \"vacío\"",
      "",
      "Tal vez recuerdes de la parte anterior que no se te permite tener un bloque vacío en un programa Python. Si necesitas tener un bloque de código que no haga nada, por ejemplo al probar alguna otra funcionalidad, el comando `pass` te permitirá hacerlo. Podrías, por ejemplo, escribir una función que no haga nada:",
      "",
      "```python",
      "def testing():",
      "    pass",
      "```",
      "",
      "Esta función simplemente regresaría inmediatamente. Omitir el comando `pass`, es decir, tener un bloque completamente vacío, produciría un error.",
      "",
      "```python",
      "def testing():  # ¡esto causa un error!",
      "```",
      "",
      "## Bucles con bloques else",
      "",
      "En Python, los bucles también pueden tener bloques `else`. Esta sección de código se ejecuta si el bucle termina normally.",
      "",
      "Por ejemplo, en el siguiente ejemplo estamos buscando en una lista de números. Si hay un número par en la lista, el programa imprime un mensaje y se rompe el bucle. Si no hay números pares, el bucle termina normalmente, pero luego se imprime un mensaje diferente.",
      "",
      "```python",
      "mi_lista = [3,5,2,8,1]",
      "for x in mi_lista:",
      "    if x%2 == 0:",
      "        print(\"encontré un número par\", x)",
      "        break",
      "else:",
      "    print(\"no había números pares\")",
      "```",
      "",
      "Una forma más tradicional de lograr esto sería usar una variable auxiliar para recordar si se encontró el elemento deseado:",
      "",
      "```python",
      "mi_lista = [3,5,2,8,1]",
      "encontrado = False",
      "for x in mi_lista:",
      "    if x%2 == 0:",
      "        print(\"encontré un número par\", x)",
      "        encontrado = True",
      "        break",
      "if not encontrado:",
      "    print(\"no había números pares\")",
      "```",
      "",
      "Usar una declaración `for else` nos ahorra la molestia de escribir una variable separada.",
      "",
      "## Valor de parámetro predeterminado",
      "",
      "Una función de Python puede tener un valor de parámetro predeterminado. Se utiliza siempre que no se pasa ningún argumento a la función. Mira el siguiente ejemplo:",
      "",
      "```python",
      "def saludar(nombre=\"Emily\"):",
      "    print(\"Hola,\", nombre)",
      "",
      "saludar()",
      "saludar(\"Eric\")",
      "saludar(\"Matthew\")",
      "saludar(\"\")",
      "```",
      "",
      "```text",
      "Hola, Emily",
      "Hola, Eric",
      "Hola, Matthew",
      "Hola,",
      "```",
      "",
      "Nota: una cadena vacía sigue siendo una cadena, por lo que el parámetro predeterminado no se utiliza si se pasa una cadena vacía a la función.",
      "",
      "## Un número variable de parámetros",
      "",
      "También puedes definir una función con un número variable de parámetros, añadiendo una estrella antes del nombre del parámetro. Todos los argumentos restantes pasados a la función están contenidos en una tupla, y se puede acceder a ellos a través del parámetro nombrado.",
      "",
      "La siguiente función cuenta el número y la suma de sus argumentos:",
      "",
      "```python",
      "def prueba(*mis_args):",
      "    print(\"Pasaste\", len(mis_args), \"argumentos\")",
      "    print(\"La suma de los argumentos es\", sum(mis_args))",
      "",
      "prueba(1, 2, 3, 4, 5)",
      "```",
      "",
      "```text",
      "Pasaste 5 argumentos",
      "La suma de los argumentos es 15",
      "```"
    ].join("\n"),
    EUS: [
      "Ikastaro hau amaitzeko, hemen Python-en hainbat ezaugarri erabilgarri aurkituko dituzu.",
      "",
      "## Lerro bakarreko baldintzak",
      "",
      "Hurrengo bi adierazpenek emaitza zehatz berberak ematen dituzte:",
      "",
      "```python",
      "if x%2 == 0:",
      "    print(\"bikoitia\")",
      "else:",
      "    print(\"bakoitia\")",
      "```",
      "",
      "```python",
      "print(\"bikoitia\" if x%2 == 0 else \"bakoitia\")",
      "```",
      "",
      "Azken adibidean lerro bakarreko baldintzazko adierazpen bat dugu: `a if [baldintza] else b`. Adierazpen honen balioa `a` da baldintza egia bada, eta `b` faltsua bada. Egitura honi batzuetan *eragile hirutarra* deitzen zaio.",
      "",
      "Baldintzazko adierazpenak oso erabilgarriak izan daitezke zerbait *baldintzapean* esleitu behar duzunean. Adibidez, `x` eta `y` aldagaiak bazenitu, eta `y`-ren balioa handitu edo ezarri nahi bazenu `x`-ren paritatearen arabera, ohiko `if else` adierazpen batean idatz zenezake, honela:",
      "",
      "```python",
      "if x%2 == 0:",
      "    y += 1",
      "else:",
      "    y = 0",
      "```",
      "",
      "Gauza bera lor liteke lerro bakarreko txukun batekin:",
      "",
      "```python",
      "y = y + 1 if x%2 == 0 else 0",
      "```",
      "",
      "## Bloke \"huts\" bat",
      "",
      "Agian gogoan izango duzu aurreko zatitik ez duzula baimenik Python programa batean bloke huts bat izateko. Ezer egiten ez duen kode bloke bat izan behar baduzu, adibidez beste funtzionalitateren bat probatzean, `pass` komandoak hori egiten utziko dizu. Adibidez, ezer egiten ez duen funtzio bat idatz zenezake:",
      "",
      "```python",
      "def probatzen():",
      "    pass",
      "```",
      "",
      "Funtzio honek berehala itzuliko luke. `pass` komandoa kanpoan uzteak, hau da, bloke guztiz huts bat izateak, errore bat sortuko luke.",
      "",
      "```python",
      "def probatzen():  # honek errore bat eragiten du!",
      "```",
      "",
      "## Begiztak else blokeekin",
      "",
      "Python-en, begiztek `else` blokeak ere izan ditzakete. Kode atal hau begizta normalean amaitzen bada exekutatzen da.",
      "",
      "Adibidez, hurrengo adibidean zenbaki zerrenda bat aztertzen ari gara. Zerrendan zenbaki bikoiti bat badago, programak mezu bat inprimatzen du eta begizta apurtzen da. Zenbaki bikoitirik ez badago, begizta normalean amaitzen da, baina orduan mezu desberdin bat inprimatzen da.",
      "",
      "```python",
      "nire_zerrenda = [3,5,2,8,1]",
      "for x in nire_zerrenda:",
      "    if x%2 == 0:",
      "        print(\"zenbaki bikoitia aurkitu da\", x)",
      "        break",
      "else:",
      "    print(\"ez zegoen zenbaki bikoitirik\")",
      "```",
      "",
      "Hau lortzeko modu tradizionalago bat aldagai laguntzaile bat erabiltzea litzateke, nahi den elementua aurkitu den gogoratzeko:",
      "",
      "```python",
      "nire_zerrenda = [3,5,2,8,1]",
      "aurkitua = False",
      "for x in nire_zerrenda:",
      "    if x%2 == 0:",
      "        print(\"zenbaki bikoitia aurkitu da\", x)",
      "        aurkitua = True",
      "        break",
      "if not aurkitua:",
      "    print(\"ez zegoen zenbaki bikoitirik\")",
      "```",
      "",
      "`for else` sententzia bat erabiltzeak aldagai bereizi bat idazteko lana aurrezten digu.",
      "",
      "## Parametro balio lehenetsia",
      "",
      "Python funtzio batek parametro balio lehenetsia izan dezake. Funtzioari argumenturik pasatzen ez zaionean erabiltzen da. Ikusi hurrengo adibidea:",
      "",
      "```python",
      "def kaixo_esan(izena=\"Emily\"):",
      "    print(\"Kaixo,\", izena)",
      "",
      "kaixo_esan()",
      "kaixo_esan(\"Eric\")",
      "kaixo_esan(\"Matthew\")",
      "kaixo_esan(\"\")",
      "```",
      "",
      "```text",
      "Kaixo, Emily",
      "Kaixo, Eric",
      "Kaixo, Matthew",
      "Kaixo,",
      "```",
      "",
      "OHARRA: kate huts bat oraindik kate bat da, beraz, parametro lehenetsia ez da erabiltzen funtzioari kate huts bat pasatzen bazaio.",
      "",
      "## Parametro kopuru aldakorra",
      "",
      "Parametro kopuru aldakorreko funtzio bat ere defini dezakezu, parametro izenaren aurretik izar bat gehituz. Funtzioari pasatako gainerako argumentu guztiak tupla batean daude, eta izendatutako parametroaren bidez atzitu daitezke.",
      "",
      "Hurrengo funtzioak bere argumentuen kopurua eta batura kontatzen ditu:",
      "",
      "```python",
      "def probatzen(*nire_arg):",
      "    print(\"Zuk\", len(nire_arg), \"argumentu pasatu dituzu\")",
      "    print(\"Argumentuen batura\", sum(nire_arg), \"da\")",
      "",
      "probatzen(1, 2, 3, 4, 5)",
      "```",
      "",
      "```text",
      "Zuk 5 argumentu pasatu dituzu",
      "Argumentuen batura 15 da",
      "```"
    ].join("\n")
  }
};

const exerciseOwnLanguage = {
  type: "exercise",
  exerciseId: "part07-18_own_programming_language",
  title: {
    ENG: "Your own programming language",
    CAS: "Tu propio lenguaje de programación",
    EUS: "Zure programazio lengoaia"
  },
  description: {
    ENG: "In this exercise you will write your own programming language executor. The programs will consist of commands like PRINT, MOV, ADD, SUB, MUL, JUMP, IF...JUMP, END. You need to implement a function `run(program)` that executes these commands.",
    CAS: "En este ejercicio escribirás tu propio ejecutor de lenguaje de programación. Los programas consistirán en comandos como PRINT, MOV, ADD, SUB, MUL, JUMP, IF...JUMP, END. Necesitas implementar una función `run(program)` que ejecute estos comandos.",
    EUS: "Ariketa honetan zure programazio lengoaia exekutatzailea idatziko duzu. Programak PRINT, MOV, ADD, SUB, MUL, JUMP, IF...JUMP, END bezalako komandoez osatuta egongo dira. Komando hauek exekutatzen dituen `run(program)` funtzioa inplementatu behar duzu."
  },
  initialCode: {
    ENG: [
      "def run(program):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def run(programa):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def run(programa):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const section6 = {
  id: "part7-6",
  title: {
    ENG: "More Python features",
    CAS: "Más características de Python",
    EUS: "Python ezaugarri gehiago"
  },
  blocks: [
    learningObjectives,
    moreFeaturesContent,
    exerciseOwnLanguage
  ]
};

const outputPath = path.join(__dirname, '../src/data/part7/section6.json');
fs.writeFileSync(outputPath, JSON.stringify(section6, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);
