const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "- You will know what lists are in Python",
      "- You will be able access a specified item within a list",
      "- You will know how to add items to a list, and how to remove them",
      "- You will be familiar with built-in list functions and methods"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "- Sabrás qué son las listas en Python",
      "- Podrás acceder a un elemento específico dentro de una lista",
      "- Sabrás cómo añadir elementos a una lista y cómo eliminarlos",
      "- Te familiarizarás con las funciones y métodos de lista incorporados"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "- Jakingo duzu zer diren zerrendak Python-en",
      "- Zerrenda bateko elementu zehatz batera sartzeko gai izango zara",
      "- Jakingo duzu nola gehitu elementuak zerrenda batera, eta nola kendu",
      "- Zerrenda-funtzio eta metodo integratuak ezagutuko dituzu"
    ].join("\n")
  }
};

const introContent = {
  type: "markdown",
  content: {
    ENG: [
      "Thus far in our programs we have stored data with variables, each bit of data usually having its own named variable. This obviously has some limitations, as it can get cumbersome to define separate variables for everything when there is a lot of data to handle.",
      "",
      "A Python *list* is a collection of values which is accessed via a single variable name. The contents of the list are written within square brackets. The values contained in the list are called *items*, or sometimes *elements*.",
      "",
      "The following command creates a new, empty list",
      "",
      "```python",
      "my_list = []",
      "```",
      "",
      "whereas this command creates a list with five items in it:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "```",
      "",
      "## Accessing items in a list",
      "",
      "A single list item can be accessed just like a single character in a string is accessed, with square brackets:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "",
      "print(my_list[0])",
      "print(my_list[1])",
      "print(my_list[3])",
      "",
      "print(\"The sum of the first two items:\", my_list[0] + my_list[1])",
      "```",
      "",
      "```text",
      "7",
      "2",
      "5",
      "The sum of the first two items: 9",
      "```",
      "",
      "The entire contents of the list can also be printed out:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "```",
      "",
      "Unlike strings, lists are mutable, which means their contents can change. You can assign a new value to an item within a list, just like you can assign a new value to a variable:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "print(my_list)",
      "my_list[1] = 3",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "[7, 3, 2, 5, 2]",
      "```",
      "",
      "The function `len` gives you the number of items in a list:",
      "",
      "```python",
      "my_list = [7, 2, 2, 5, 2]",
      "print(len(my_list))",
      "```",
      "",
      "```text",
      "5",
      "```"
    ].join("\n"),
    CAS: [
      "Hasta ahora en nuestros programas hemos almacenado datos con variables, donde cada dato suele tener su propia variable con nombre. Esto obviamente tiene algunas limitaciones, ya que puede resultar engorroso definir variables separadas para todo cuando hay muchos datos que manejar.",
      "",
      "Una *lista* de Python es una colección de valores a los que se accede a través de un único nombre de variable. El contenido de la lista se escribe entre corchetes. Los valores contenidos en la lista se denominan *elementos*.",
      "",
      "El siguiente comando crea una lista nueva y vacía",
      "",
      "```python",
      "mi_lista = []",
      "```",
      "",
      "mientras que este comando crea una lista con cinco elementos en ella:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "```",
      "",
      "## Accediendo a elementos en una lista",
      "",
      "Se puede acceder a un solo elemento de la lista tal como se accede a un solo carácter en una cadena, con corchetes:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "",
      "print(mi_lista[0])",
      "print(mi_lista[1])",
      "print(mi_lista[3])",
      "",
      "print(\"La suma de los dos primeros elementos:\", mi_lista[0] + mi_lista[1])",
      "```",
      "",
      "```text",
      "7",
      "2",
      "5",
      "La suma de los dos primeros elementos: 9",
      "```",
      "",
      "El contenido completo de la lista también se puede imprimir:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "```",
      "",
      "A diferencia de las cadenas, las listas son mutables, lo que significa que su contenido puede cambiar. Puedes asignar un nuevo valor a un elemento dentro de una lista, al igual que puedes asignar un nuevo valor a una variable:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "print(mi_lista)",
      "mi_lista[1] = 3",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "[7, 3, 2, 5, 2]",
      "```",
      "",
      "La función `len` te da el número de elementos en una lista:",
      "",
      "```python",
      "mi_lista = [7, 2, 2, 5, 2]",
      "print(len(mi_lista))",
      "```",
      "",
      "```text",
      "5",
      "```"
    ].join("\n"),
    EUS: [
      "Orain arte gure programetan datuak aldagaiekin gorde ditugu, datu bakoitzak normalean bere izeneko aldagaia duelarik. Honek, jakina, muga batzuk ditu; izan ere, maneiatzeko datu asko daudenean astuna izan daiteke denatarako aldagai bereiziak definitzea.",
      "",
      "Python *zerrenda* aldagai-izen bakar baten bidez atzitzen den balio bilduma bat da. Zerrendaren edukia kortxete artean idazten da. Zerrendan dauden balioei *elementu* deitzen zaie.",
      "",
      "Hurrengo komandoak zerrenda berri eta huts bat sortzen du",
      "",
      "```python",
      "nire_zerrenda = []",
      "```",
      "",
      "komando honek, berriz, bost elementu dituen zerrenda bat sortzen du:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "```",
      "",
      "## Zerrenda bateko elementuak atzitzen",
      "",
      "Zerrendako elementu bakar batera sartu daiteke kate bateko karaktere bakar batera sartzen den modu berean, kortxeteekin:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "",
      "print(nire_zerrenda[0])",
      "print(nire_zerrenda[1])",
      "print(nire_zerrenda[3])",
      "",
      "print(\"Lehen bi elementuen batura:\", nire_zerrenda[0] + nire_zerrenda[1])",
      "```",
      "",
      "```text",
      "7",
      "2",
      "5",
      "Lehen bi elementuen batura: 9",
      "```",
      "",
      "Zerrendaren eduki osoa ere inprimatu daiteke:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "```",
      "",
      "Kateak ez bezala, zerrendak aldagarriak dira, hau da, haien edukia alda daiteke. Balio berri bat esleitu diezaiokezu zerrenda bateko elementu bati, aldagai bati balio berria esleitzen diozun bezala:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "print(nire_zerrenda)",
      "nire_zerrenda[1] = 3",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[7, 2, 2, 5, 2]",
      "[7, 3, 2, 5, 2]",
      "```",
      "",
      "`len` funtzioak zerrenda bateko elementu kopurua ematen dizu:",
      "",
      "```python",
      "nire_zerrenda = [7, 2, 2, 5, 2]",
      "print(len(nire_zerrenda))",
      "```",
      "",
      "```text",
      "5",
      "```"
    ].join("\n")
  }
};

const exerciseChangeValue = {
  type: "exercise",
  exerciseId: "part04-12_change_value_of_item",
  title: {
    ENG: "Change the value of an item",
    CAS: "Cambiar el valor de un elemento",
    EUS: "Elementu baten balioa aldatu"
  },
  description: {
    ENG: "Write a program that initializes a list with the values `[1, 2, 3, 4, 5]`. Then, ask the user for an index and a new value, replace the item at that index, and print the list. Continue until the user inputs -1 for the index.",
    CAS: "Escribe un programa que inicialice una lista con los valores `[1, 2, 3, 4, 5]`. Luego, pide al usuario un índice y un nuevo valor, reemplaza el elemento en ese índice e imprime la lista. Continúa hasta que el usuario introduzca -1 para el índice.",
    EUS: "Idatzi programa bat zerrenda bat hasieratzen duena `[1, 2, 3, 4, 5]` balioekin. Ondoren, eskatu erabiltzaileari indize bat eta balio berri bat, ordezkatu indize horretako elementua eta inprimatu zerrenda. Jarraitu erabiltzaileak indizean -1 sartu arte."
  },
  initialCode: {
    ENG: "# Write your solution here\nmy_list = [1, 2, 3, 4, 5]",
    CAS: "# Escribe tu solución aquí\nmy_list = [1, 2, 3, 4, 5]",
    EUS: "# Idatzi zure soluzioa hemen\nmy_list = [1, 2, 3, 4, 5]"
  },
  testCode: "\nimport unittest\nclass TestChangeItem(unittest.TestCase):\n    def test_run(self):\n        inputs = [\"0\", \"10\", \"2\", \"20\", \"-1\"]\n        out = run_student_code(inputs=inputs)\n        self.assertIn(\"[10, 2, 3, 4, 5]\", out)\n        self.assertIn(\"[10, 2, 20, 4, 5]\", out)\n"
};

const addingItemsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Adding items to a list",
      "",
      "The `append` method adds items to the end of a list. It works like this:",
      "",
      "```python",
      "numbers = []",
      "numbers.append(5)",
      "numbers.append(10)",
      "numbers.append(3)",
      "print(numbers)",
      "```",
      "",
      "```text",
      "[5, 10, 3]",
      "```",
      "",
      "The following example makes use of two separate lists:",
      "",
      "```python",
      "numbers = []",
      "shoe_sizes = []",
      "",
      "numbers.append(5)",
      "numbers.append(10)",
      "numbers.append(3)",
      "",
      "shoe_sizes.append(37)",
      "shoe_sizes.append(44)",
      "shoe_sizes.append(40)",
      "shoe_sizes.append(28)",
      "",
      "print(\"Numbers:\")",
      "print(numbers)",
      "",
      "print(\"Shoe sizes:\")",
      "print(shoe_sizes)",
      "```",
      "",
      "The item is appended to the list on which the method is called:",
      "",
      "```text",
      "Numbers:",
      "[5, 10, 3]",
      "Shoe sizes:",
      "[37, 44, 40, 28]",
      "```",
      "",
      "## Adding to a specific location",
      "",
      "If you want to specify a location in the list where an item should be added, you can use the `insert` method. The method adds an item at the specified index. All the items already in the list with an index equal to or higher than the specified index are moved one index further, \"to the right:\"",
      "",
      "![Inserting an item to a list](images/4_3_2.png)",
      "",
      "So, for instance this program",
      "",
      "```python",
      "numbers = [1, 2, 3, 4, 5, 6]",
      "numbers.insert(0, 10)",
      "print(numbers)",
      "numbers.insert(2, 20)",
      "print(numbers)",
      "```",
      "",
      "prints out this:",
      "",
      "```text",
      "[10, 1, 2, 3, 4, 5, 6]",
      "[10, 1, 20, 2, 3, 4, 5, 6]",
      "```"
    ].join("\n"),
    CAS: [
      "## Añadir elementos a una lista",
      "",
      "El método `append` añade elementos al final de una lista. Funciona así:",
      "",
      "```python",
      "numeros = []",
      "numeros.append(5)",
      "numeros.append(10)",
      "numeros.append(3)",
      "print(numeros)",
      "```",
      "",
      "```text",
      "[5, 10, 3]",
      "```",
      "",
      "El siguiente ejemplo hace uso de dos listas separadas:",
      "",
      "```python",
      "numeros = []",
      "tallas_zapatos = []",
      "",
      "numeros.append(5)",
      "numeros.append(10)",
      "numeros.append(3)",
      "",
      "tallas_zapatos.append(37)",
      "tallas_zapatos.append(44)",
      "tallas_zapatos.append(40)",
      "tallas_zapatos.append(28)",
      "",
      "print(\"Números:\")",
      "print(numeros)",
      "",
      "print(\"Tallas de zapatos:\")",
      "print(tallas_zapatos)",
      "```",
      "",
      "El elemento se añade a la lista sobre la que se llama el método:",
      "",
      "```text",
      "Números:",
      "[5, 10, 3]",
      "Tallas de zapatos:",
      "[37, 44, 40, 28]",
      "```",
      "",
      "## Añadir a una ubicación específica",
      "",
      "Si quieres especificar una ubicación en la lista donde se debe añadir un elemento, puedes usar el método `insert`. El método añade un elemento en el índice especificado. Todos los elementos que ya están en la lista con un índice igual o superior al índice especificado se mueven un índice más allá, \"a la derecha:\"",
      "",
      "![Insertar un elemento en una lista](images/4_3_2.png)",
      "",
      "Así, por ejemplo, este programa",
      "",
      "```python",
      "numeros = [1, 2, 3, 4, 5, 6]",
      "numeros.insert(0, 10)",
      "print(numeros)",
      "numeros.insert(2, 20)",
      "print(numeros)",
      "```",
      "",
      "imprime esto:",
      "",
      "```text",
      "[10, 1, 2, 3, 4, 5, 6]",
      "[10, 1, 20, 2, 3, 4, 5, 6]",
      "```"
    ].join("\n"),
    EUS: [
      "## Elementuak zerrenda batera gehitzen",
      "",
      "`append` metodoak elementuak gehitzen ditu zerrenda baten amaieran. Horrela funtzionatzen du:",
      "",
      "```python",
      "zenbakiak = []",
      "zenbakiak.append(5)",
      "zenbakiak.append(10)",
      "zenbakiak.append(3)",
      "print(zenbakiak)",
      "```",
      "",
      "```text",
      "[5, 10, 3]",
      "```",
      "",
      "Hurrengo adibideak bi zerrenda bereizi erabiltzen ditu:",
      "",
      "```python",
      "zenbakiak = []",
      "oinetako_neurriak = []",
      "",
      "zenbakiak.append(5)",
      "zenbakiak.append(10)",
      "zenbakiak.append(3)",
      "",
      "oinetako_neurriak.append(37)",
      "oinetako_neurriak.append(44)",
      "oinetako_neurriak.append(40)",
      "oinetako_neurriak.append(28)",
      "",
      "print(\"Zenbakiak:\")",
      "print(zenbakiak)",
      "",
      "print(\"Oinetako neurriak:\")",
      "print(oinetako_neurriak)",
      "```",
      "",
      "Elementua metodoa deitzen den zerrendari gehitzen zaio:",
      "",
      "```text",
      "Zenbakiak:",
      "[5, 10, 3]",
      "Oinetako neurriak:",
      "[37, 44, 40, 28]",
      "```",
      "",
      "## Kokapen zehatz batera gehitzen",
      "",
      "Elementu bat zerrendako zein kokapenetan gehitu behar den zehaztu nahi baduzu, `insert` metodoa erabil dezakezu. Metodoak elementu bat gehitzen du zehaztutako indizean. Zerrendan lehendik dauden elementu guztiak, zehaztutako indizearen berdina edo handiagoa dutenak, indize bat harago mugitzen dira, \"eskuinera:\"",
      "",
      "![Elementu bat zerrenda batera txertatzen](images/4_3_2.png)",
      "",
      "Beraz, adibidez programa honek",
      "",
      "```python",
      "zenbakiak = [1, 2, 3, 4, 5, 6]",
      "zenbakiak.insert(0, 10)",
      "print(zenbakiak)",
      "zenbakiak.insert(2, 20)",
      "print(zenbakiak)",
      "```",
      "",
      "hau inprimatzen du:",
      "",
      "```text",
      "[10, 1, 2, 3, 4, 5, 6]",
      "[10, 1, 20, 2, 3, 4, 5, 6]",
      "```"
    ].join("\n")
  }
};

const exerciseAddItems = {
  type: "exercise",
  exerciseId: "part04-13_add_items_to_list",
  title: {
    ENG: "Add items to a list",
    CAS: "Añadir elementos a una lista",
    EUS: "Gehitu elementuak zerrenda batera"
  },
  description: {
    ENG: "Write a program that asks the user to input the number of items they want to add to a list. Then, ask for the items one by one and add them to the list. Finally, print the list.",
    CAS: "Escribe un programa que pida al usuario el número de elementos que quiere añadir a una lista. Luego, pide los elementos uno por uno y añádelos a la lista. Finalmente, imprime la lista.",
    EUS: "Idatzi programa bat erabiltzaileari galdetzen diona zenbat elementu gehitu nahi dituen zerrenda batera. Ondoren, eskatu elementuak banan-banan eta gehitu zerrendara. Azkenik, inprimatu zerrenda."
  },
  initialCode: {
    ENG: "# Write your solution here",
    CAS: "# Escribe tu solución aquí",
    EUS: "# Idatzi zure soluzioa hemen"
  },
  testCode: "\nimport unittest\nclass TestAddItems(unittest.TestCase):\n    def test_run(self):\n        inputs = [\"3\", \"10\", \"20\", \"30\"]\n        out = run_student_code(inputs=inputs)\n        self.assertIn(\"[10, 20, 30]\", out)\n"
};

const removingItemsContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Removing items from a list",
      "",
      "There are two different approaches to removing an item from a list:",
      "",
      "- If the *index* of the item is known, you can use the method `pop`.",
      "- If the *contents* of the item are known, you can use the method `remove`.",
      "",
      "So, the method `pop` takes the index of the item you want to remove as its argument. The following program removes items at indexes 2 and 3 from the list. Notice how the indexes of the remaining items change when one is removed.",
      "",
      "```python",
      "my_list = [1, 2, 3, 4, 5, 6]",
      "",
      "my_list.pop(2)",
      "print(my_list)",
      "my_list.pop(3)",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[1, 2, 4, 5, 6]",
      "[1, 2, 4, 6]",
      "```",
      "",
      "It's useful to remember that the method `pop` also *returns* the removed item:",
      "",
      "```python",
      "my_list = [4, 2, 7, 2, 5]",
      "",
      "number = my_list.pop(2)",
      "print(number)",
      "print(my_list)",
      "```",
      "",
      "```text",
      "7",
      "[4, 2, 2, 5]",
      "```",
      "",
      "The method `remove`, on the other hand, takes the value of the item to be removed as its argument. For example, this program",
      "",
      "```python",
      "my_list = [1, 2, 3, 4, 5, 6]",
      "",
      "my_list.remove(2)",
      "print(my_list)",
      "my_list.remove(5)",
      "print(my_list)",
      "```",
      "",
      "prints out this:",
      "",
      "```text",
      "[1, 3, 4, 5, 6]",
      "[1, 3, 4, 6]",
      "```",
      "",
      "The method removes the *first* occurrence of the value in the list, much like the string function `find` returns the first occurrence of a substring:",
      "",
      "```python",
      "my_list = [1, 2, 1, 2]",
      "",
      "my_list.remove(1)",
      "print(my_list)",
      "my_list.remove(1)",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[2, 1, 2]",
      "[2, 2]",
      "```",
      "",
      "If the specified item is not in the list, the `remove` function causes an error. Just like with strings, we can check for the presence of an item with the `in` operator:",
      "",
      "```python",
      "my_list = [1, 3, 4]",
      "",
      "if 1 in my_list:",
      "    print(\"The list contains item 1\")",
      "",
      "if 2 in my_list:",
      "    print(\"The list contains item 2\")",
      "```",
      "",
      "```text",
      "The list contains item 1",
      "```"
    ].join("\n"),
    CAS: [
      "## Eliminando elementos de una lista",
      "",
      "Hay dos enfoques diferentes para eliminar un elemento de una lista:",
      "",
      "- Si se conoce el *índice* del elemento, puedes usar el método `pop`.",
      "- Si se conoce el *contenido* del elemento, puedes usar el método `remove`.",
      "",
      "Así, el método `pop` toma el índice del elemento que quieres eliminar como argumento. El siguiente programa elimina los elementos en los índices 2 y 3 de la lista. Observa cómo cambian los índices de los elementos restantes cuando se elimina uno.",
      "",
      "```python",
      "mi_lista = [1, 2, 3, 4, 5, 6]",
      "",
      "mi_lista.pop(2)",
      "print(mi_lista)",
      "mi_lista.pop(3)",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[1, 2, 4, 5, 6]",
      "[1, 2, 4, 6]",
      "```",
      "",
      "Es útil recordar que el método `pop` también *devuelve* el elemento eliminado:",
      "",
      "```python",
      "mi_lista = [4, 2, 7, 2, 5]",
      "",
      "numero = mi_lista.pop(2)",
      "print(numero)",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "7",
      "[4, 2, 2, 5]",
      "```",
      "",
      "El método `remove`, por otro lado, toma el valor del elemento a eliminar como argumento. Por ejemplo, este programa",
      "",
      "```python",
      "mi_lista = [1, 2, 3, 4, 5, 6]",
      "",
      "mi_lista.remove(2)",
      "print(mi_lista)",
      "mi_lista.remove(5)",
      "print(mi_lista)",
      "```",
      "",
      "imprime esto:",
      "",
      "```text",
      "[1, 3, 4, 5, 6]",
      "[1, 3, 4, 6]",
      "```",
      "",
      "El método elimina la *primera* aparición del valor en la lista, muy parecido a como la función de cadena `find` devuelve la primera aparición de una subcadena:",
      "",
      "```python",
      "mi_lista = [1, 2, 1, 2]",
      "",
      "mi_lista.remove(1)",
      "print(mi_lista)",
      "mi_lista.remove(1)",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[2, 1, 2]",
      "[2, 2]",
      "```",
      "",
      "Si el elemento especificado no está en la lista, la función `remove` causa un error. Al igual que con las cadenas, podemos verificar la presencia de un elemento con el operador `in`:",
      "",
      "```python",
      "mi_lista = [1, 3, 4]",
      "",
      "if 1 in mi_lista:",
      "    print(\"La lista contiene el elemento 1\")",
      "",
      "if 2 in mi_lista:",
      "    print(\"La lista contiene el elemento 2\")",
      "```",
      "",
      "```text",
      "La lista contiene el elemento 1",
      "```"
    ].join("\n"),
    EUS: [
      "## Elementuak zerrenda batetik kentzen",
      "",
      "Zerrenda batetik elementu bat kentzeko bi ikuspegi desberdin daude:",
      "",
      "- Elementuaren *indizea* ezaguna bada, `pop` metodoa erabil dezakezu.",
      "- Elementuaren *edukia* ezaguna bada, `remove` metodoa erabil dezakezu.",
      "",
      "Beraz, `pop` metodoak kendu nahi duzun elementuaren indizea hartzen du argumentu gisa. Hurrengo programak 2 eta 3 indizeetako elementuak kentzen ditu zerrendatik. Ohartu nola aldatzen diren gainerako elementuen indizeak bat kentzen denean.",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 3, 4, 5, 6]",
      "",
      "nire_zerrenda.pop(2)",
      "print(nire_zerrenda)",
      "nire_zerrenda.pop(3)",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[1, 2, 4, 5, 6]",
      "[1, 2, 4, 6]",
      "```",
      "",
      "Komenigarria da gogoratzea `pop` metodoak kendutako elementua ere *itzultzen* duela:",
      "",
      "```python",
      "nire_zerrenda = [4, 2, 7, 2, 5]",
      "",
      "zenbakia = nire_zerrenda.pop(2)",
      "print(zenbakia)",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "7",
      "[4, 2, 2, 5]",
      "```",
      "",
      "`remove` metodoak, bestalde, kendu beharreko elementuaren balioa hartzen du argumentu gisa. Adibidez, programa honek",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 3, 4, 5, 6]",
      "",
      "nire_zerrenda.remove(2)",
      "print(nire_zerrenda)",
      "nire_zerrenda.remove(5)",
      "print(nire_zerrenda)",
      "```",
      "",
      "hau inprimatzen du:",
      "",
      "```text",
      "[1, 3, 4, 5, 6]",
      "[1, 3, 4, 6]",
      "```",
      "",
      "Metodoak zerrendako balioaren *lehenengo* agerraldia kentzen du, kateen `find` funtzioak azpikate baten lehen agerraldia itzultzen duen antzera:",
      "",
      "```python",
      "nire_zerrenda = [1, 2, 1, 2]",
      "",
      "nire_zerrenda.remove(1)",
      "print(nire_zerrenda)",
      "nire_zerrenda.remove(1)",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[2, 1, 2]",
      "[2, 2]",
      "```",
      "",
      "Zehaztutako elementua ez badago zerrendan, `remove` funtzioak errore bat eragiten du. Kateekin bezala, elementu baten presentzia egiaztatu dezakegu `in` eragilearekin:",
      "",
      "```python",
      "nire_zerrenda = [1, 3, 4]",
      "",
      "if 1 in nire_zerrenda:",
      "    print(\"Zerrendak 1 elementua dauka\")",
      "",
      "if 2 in nire_zerrenda:",
      "    print(\"Zerrendak 2 elementua dauka\")",
      "```",
      "",
      "```text",
      "Zerrendak 1 elementua dauka",
      "```"
    ].join("\n")
  }
};

const exerciseAddRemove = {
  type: "exercise",
  exerciseId: "part04-14_addition_and_removal",
  title: {
    ENG: "Addition and removal",
    CAS: "Adición y eliminación",
    EUS: "Gehiketa eta ezabaketa"
  },
  description: {
    ENG: "Write a program that asks the user to choose between adding (d), removing (r) or exiting (x). The program starts with an empty list. 'd' adds the next integer (starting from 1) to the end of the list. 'r' removes the last item. Print the list after each operation.",
    CAS: "Escribe un programa que pida al usuario elegir entre añadir (d), eliminar (r) o salir (x). El programa comienza con una lista vacía. 'd' añade el siguiente entero (comenzando desde 1) al final de la lista. 'r' elimina el último elemento. Imprime la lista después de cada operación.",
    EUS: "Idatzi programa bat erabiltzaileari aukeratzeko eskatzen diona gehitzea (d), kentzea (r) edo irtetea (x). Programa zerrenda huts batekin hasten da. 'd'-k hurrengo zenbaki osoa (1etik hasita) gehitzen du zerrendaren amaieran. 'r'-k azken elementua kentzen du. Inprimatu zerrenda eragiketa bakoitzaren ondoren."
  },
  initialCode: {
    ENG: "# Write your solution here",
    CAS: "# Escribe tu solución aquí",
    EUS: "# Idatzi zure soluzioa hemen"
  },
  testCode: "\nimport unittest\nclass TestAddRemove(unittest.TestCase):\n    def test_run(self):\n        inputs = [\"d\", \"d\", \"r\", \"x\"]\n        out = run_student_code(inputs=inputs)\n        self.assertIn(\"[1, 2]\", out)\n        self.assertIn(\"[1]\", out)\n"
};

const restContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Sorting lists",
      "",
      "The items in a list can be *sorted* from smallest to greatest with the method `sort`.",
      "",
      "```python",
      "my_list = [2,5,1,2,4]",
      "my_list.sort()",
      "print(my_list)",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Notice how the method modifies the list itself. Sometimes we don't want to change the original list, so we use the function `sorted` instead. It *returns* a sorted list:",
      "",
      "```python",
      "my_list = [2,5,1,2,4]",
      "print(sorted(my_list))",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Remember the difference between the two: `sort` changes the order of the original list in place, whereas `sorted` creates a new, ordered copy of the list. With `sorted` we can preserve the original order of the list:",
      "",
      "```python",
      "original = [2, 5, 1, 2, 4]",
      "in_order = sorted(original)",
      "print(original)",
      "print(in_order)",
      "```",
      "",
      "```text",
      "[2, 5, 1, 2, 4]",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "## Maximum, minimum and sum",
      "",
      "The functions `max` and `min`, short for maximum and minimum, return the greatest and smallest item in a list, respectively. The function `sum` returns the sum of all items in a list.",
      "",
      "```python",
      "my_list = [5, 2, 3, 1, 4]",
      "",
      "greatest = max(my_list)",
      "smallest = min(my_list)",
      "list_sum = sum(my_list)",
      "",
      "print(\"Smallest:\", smallest)",
      "print(\"Greatest:\", greatest)",
      "print(\"Sum:\", list_sum)",
      "```",
      "",
      "```text",
      "Smallest: 1",
      "Greatest: 5",
      "Sum: 15",
      "```",
      "",
      "## Methods vs functions",
      "",
      "There are two different ways of processing lists in Python, which can get confusing. For the most part you will use list *methods*, such as `append` and `sort`. They are used with the dot `.` operator on the list variable:",
      "",
      "```python",
      "my_list = []",
      "",
      "# method calls",
      "my_list.append(3)",
      "my_list.append(1)",
      "my_list.append(7)",
      "my_list.append(2)",
      "",
      "# another method call",
      "my_list.sort()",
      "```",
      "",
      "Some *functions* are happy to take a list as an argument. Above we saw the functions `max`, `min`, `len` and `sorted` do just that:",
      "",
      "```python",
      "my_list = [3, 2, 7, 1]",
      "",
      "# function calls take the list as an argument",
      "greatest = max(my_list)",
      "smallest = min(my_list)",
      "length = len(my_list)",
      "",
      "print(\"Smallest:\", smallest)",
      "print(\"Greatest:\", greatest)",
      "print(\"Length of the list:\", length)",
      "",
      "# another function call",
      "# the list itself is an argument, the function returns a sorted copy",
      "in_order = sorted(my_list)",
      "print(in_order)",
      "```",
      "",
      "```text",
      "Smallest: 1",
      "Greatest: 7",
      "Length of the list: 4",
      "[1, 2, 3, 7]",
      "```",
      "",
      "## A list as an argument or a return value",
      "",
      "Just like the built-in functions above, our own functions can also take a list as an argument and produce a list as a return value. The following function works out the central value in an ordered list, also called the *median* value:",
      "",
      "```python",
      "def median(my_list: list):",
      "    ordered = sorted(my_list)",
      "    list_centre = len(ordered) // 2",
      "    return ordered[list_centre]",
      "```",
      "",
      "The function creates an ordered version of the list given as an argument and returns the item in the very middle. Notice the integer division operator `//` used here. The index of a list should always be an integer.",
      "",
      "The function works like this:",
      "",
      "```python",
      "shoe_sizes = [45, 44, 36, 39, 40]",
      "print(\"The median of the shoe sizes is\", median(shoe_sizes))",
      "",
      "ages = [1, 56, 34, 22, 5, 77, 5]",
      "print(\"The median of the ages is\", median(ages))",
      "```",
      "",
      "```text",
      "The median of the shoe sizes is 40",
      "The median of the ages is 22",
      "```",
      "",
      "A function can also return a list. The following function asks the user to type in integers and returns the input as a list:",
      "",
      "```python",
      "def input_numbers():",
      "    numbers = []",
      "    while True:",
      "        user_input = input(\"Please type in an integer, leave empty to exit: \")",
      "        if len(user_input) == 0:",
      "            break",
      "        numbers.append(int(user_input))",
      "    return numbers",
      "```",
      "",
      "The function makes use of a helper variable `numbers`, which is a list. All the numbers typed in by the user are added to the list. When the loop is exited from, the function returns the list with the statement `return numbers`.",
      "",
      "Calling the function like this",
      "",
      "```python",
      "numbers = input_numbers()",
      "",
      "print(\"The greatest number is\", max(numbers))",
      "print(\"The median of the numbers is\", median(numbers))",
      "```",
      "",
      "could print this, for example:",
      "",
      "```text",
      "Please type in an integer, leave empty to exit: 5",
      "Please type in an integer, leave empty to exit: -22",
      "Please type in an integer, leave empty to exit: 4",
      "Please type in an integer, leave empty to exit: 35",
      "Please type in an integer, leave empty to exit: 1",
      "Please type in an integer, leave empty to exit:",
      "The greatest number is 35",
      "The median of the numbers is 4",
      "```",
      "",
      "This small example demonstrates one of the most important uses of functions: they can help you divide your code into smaller, easily understandable and logical wholes.",
      "",
      "Of course the same functionality could be achieved without writing any of our own functions:",
      "",
      "```python",
      "numbers = []",
      "while True:",
      "    user_input = input(\"Please type in an integer, leave empty to exit: \")",
      "    if len(user_input) == 0:",
      "        break",
      "    numbers.append(int(user_input))",
      "",
      "ordered = sorted(numbers)",
      "list_centre = len(ordered) // 2",
      "median = ordered[list_centre]",
      "",
      "print(\"The greatest number is\", max(numbers))",
      "print(\"The median of the numbers is\", median)",
      "```",
      "",
      "In this version, following the programming logic is more difficult, as it is no longer clear which commands are a part of which functionality. The code fulfils the same purposes - reading in input, calculating the median value, and so on - but the structure is less clear.",
      "",
      "Organising your code into separate functions will improve you program's readability, but also make it easier to handle logical wholes. This in turn helps you verify that the program works as intended, as each function can be tested separately.",
      "",
      "Another important use for functions is making code *reusable*. If you need to achieve some functionality multiple times in your program, it is a good idea to create your own function and name it appropriately:",
      "",
      "```python",
      "print(\"Shoe sizes:\")",
      "shoe_sizes = input_numbers()",
      "",
      "print(\"Weights:\")",
      "weights = input_numbers()",
      "",
      "print(\"Heights:\")",
      "heights = input_numbers()",
      "```"
    ].join("\n"),
    CAS: [
      "## Ordenando listas",
      "",
      "Los elementos en una lista se pueden *ordenar* de menor a mayor con el método `sort`.",
      "",
      "```python",
      "mi_lista = [2,5,1,2,4]",
      "mi_lista.sort()",
      "print(mi_lista)",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Observa cómo el método modifica la lista en sí. A veces no queremos cambiar la lista original, por lo que usamos la función `sorted` en su lugar. Esta *devuelve* una lista ordenada:",
      "",
      "```python",
      "mi_lista = [2,5,1,2,4]",
      "print(sorted(mi_lista))",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Recuerda la diferencia entre los dos: `sort` cambia el orden de la lista original in situ, mientras que `sorted` crea una copia nueva y ordenada de la lista. Con `sorted` podemos preservar el orden original de la lista:",
      "",
      "```python",
      "original = [2, 5, 1, 2, 4]",
      "en_orden = sorted(original)",
      "print(original)",
      "print(en_orden)",
      "```",
      "",
      "```text",
      "[2, 5, 1, 2, 4]",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "## Máximo, mínimo y suma",
      "",
      "Las funciones `max` y `min`, abreviaturas de máximo y mínimo, devuelven el elemento mayor y menor de una lista, respectivamente. La función `sum` devuelve la suma de todos los elementos en una lista.",
      "",
      "```python",
      "mi_lista = [5, 2, 3, 1, 4]",
      "",
      "mayor = max(mi_lista)",
      "menor = min(mi_lista)",
      "suma_lista = sum(mi_lista)",
      "",
      "print(\"Menor:\", menor)",
      "print(\"Mayor:\", mayor)",
      "print(\"Suma:\", suma_lista)",
      "```",
      "",
      "```text",
      "Menor: 1",
      "Mayor: 5",
      "Suma: 15",
      "```",
      "",
      "## Métodos vs funciones",
      "",
      "Hay dos formas diferentes de procesar listas en Python, lo que puede resultar confuso. En su mayor parte, utilizarás *métodos* de lista, como `append` y `sort`. Se utilizan con el operador punto `.` en la variable de la lista:",
      "",
      "```python",
      "mi_lista = []",
      "",
      "# llamadas a métodos",
      "mi_lista.append(3)",
      "mi_lista.append(1)",
      "mi_lista.append(7)",
      "mi_lista.append(2)",
      "",
      "# otra llamada a método",
      "mi_lista.sort()",
      "```",
      "",
      "Algunas *funciones* aceptan una lista como argumento. Arriba vimos que las funciones `max`, `min`, `len` y `sorted` hacen exactamente eso:",
      "",
      "```python",
      "mi_lista = [3, 2, 7, 1]",
      "",
      "# las llamadas a funciones toman la lista como argumento",
      "mayor = max(mi_lista)",
      "menor = min(mi_lista)",
      "longitud = len(mi_lista)",
      "",
      "print(\"Menor:\", menor)",
      "print(\"Mayor:\", mayor)",
      "print(\"Longitud de la lista:\", longitud)",
      "",
      "# otra llamada a función",
      "# la lista en sí es un argumento, la función devuelve una copia ordenada",
      "en_orden = sorted(mi_lista)",
      "print(en_orden)",
      "```",
      "",
      "```text",
      "Menor: 1",
      "Mayor: 7",
      "Longitud de la lista: 4",
      "[1, 2, 3, 7]",
      "```",
      "",
      "## Una lista como argumento o valor de retorno",
      "",
      "Al igual que las funciones incorporadas anteriores, nuestras propias funciones también pueden tomar una lista como argumento y producir una lista como valor de retorno. La siguiente función calcula el valor central en una lista ordenada, también llamado valor *mediano*:",
      "",
      "```python",
      "def mediana(mi_lista: list):",
      "    ordenada = sorted(mi_lista)",
      "    centro_lista = len(ordenada) // 2",
      "    return ordenada[centro_lista]",
      "```",
      "",
      "La función crea una versión ordenada de la lista dada como argumento y devuelve el elemento en el mismo centro. Observa el operador de división entera `//` utilizado aquí. El índice de una lista siempre debe ser un entero.",
      "",
      "La función funciona así:",
      "",
      "```python",
      "tallas_zapatos = [45, 44, 36, 39, 40]",
      "print(\"La mediana de las tallas de zapatos es\", mediana(tallas_zapatos))",
      "",
      "edades = [1, 56, 34, 22, 5, 77, 5]",
      "print(\"La mediana de las edades es\", mediana(edades))",
      "```",
      "",
      "```text",
      "La mediana de las tallas de zapatos es 40",
      "La mediana de las edades es 22",
      "```",
      "",
      "Una función también puede devolver una lista. La siguiente función pide al usuario que escriba números enteros y devuelve la entrada como una lista:",
      "",
      "```python",
      "def ingresar_numeros():",
      "    numeros = []",
      "    while True:",
      "        entrada_usuario = input(\"Por favor escribe un entero, deja vacío para salir: \")",
      "        if len(entrada_usuario) == 0:",
      "            break",
      "        numeros.append(int(entrada_usuario))",
      "    return numeros",
      "```",
      "",
      "La función hace uso de una variable auxiliar `numeros`, que es una lista. Todos los números escritos por el usuario se añaden a la lista. Cuando se sale del bucle, la función devuelve la lista con la sentencia `return numeros`.",
      "",
      "Llamando a la función así",
      "",
      "```python",
      "numeros = ingresar_numeros()",
      "",
      "print(\"El número mayor es\", max(numeros))",
      "print(\"La mediana de los números es\", mediana(numeros))",
      "```",
      "",
      "podría imprimir esto, por ejemplo:",
      "",
      "```text",
      "Por favor escribe un entero, deja vacío para salir: 5",
      "Por favor escribe un entero, deja vacío para salir: -22",
      "Por favor escribe un entero, deja vacío para salir: 4",
      "Por favor escribe un entero, deja vacío para salir: 35",
      "Por favor escribe un entero, deja vacío para salir: 1",
      "Por favor escribe un entero, deja vacío para salir:",
      "El número mayor es 35",
      "La mediana de los números es 4",
      "```",
      "",
      "Este pequeño ejemplo demuestra uno de los usos más importantes de las funciones: pueden ayudarte a dividir tu código en partes lógicas más pequeñas y fáciles de entender.",
      "",
      "Por supuesto, la misma funcionalidad se podría lograr sin escribir ninguna de nuestras propias funciones:",
      "",
      "```python",
      "numeros = []",
      "while True:",
      "    entrada_usuario = input(\"Por favor escribe un entero, deja vacío para salir: \")",
      "    if len(entrada_usuario) == 0:",
      "        break",
      "    numeros.append(int(entrada_usuario))",
      "",
      "ordenada = sorted(numeros)",
      "centro_lista = len(ordenada) // 2",
      "mediana = ordenada[centro_lista]",
      "",
      "print(\"El número mayor es\", max(numeros))",
      "print(\"La mediana de los números es\", mediana)",
      "```",
      "",
      "En esta versión, seguir la lógica de programación es más difícil, ya que ya no está claro qué comandos son parte de qué funcionalidad. El código cumple los mismos propósitos (leer la entrada, calcular el valor mediano, etc.), pero la estructura es menos clara.",
      "",
      "Organizar tu código en funciones separadas mejorará la legibilidad de tu programa, pero también facilitará el manejo de conjuntos lógicos. Esto a su vez te ayuda a verificar que el programa funciona según lo previsto, ya que cada función se puede probar por separado.",
      "",
      "Otro uso importante para las funciones es hacer que el código sea *reutilizable*. Si necesitas lograr alguna funcionalidad varias veces en tu programa, es una buena idea crear tu propia función y nombrarla adecuadamente:",
      "",
      "```python",
      "print(\"Tallas de zapatos:\")",
      "tallas_zapatos = ingresar_numeros()",
      "",
      "print(\"Pesos:\")",
      "pesos = ingresar_numeros()",
      "",
      "print(\"Alturas:\")",
      "alturas = ingresar_numeros()",
      "```"
    ].join("\n"),
    EUS: [
      "## Zerrendak ordenatzen",
      "",
      "Zerrenda bateko elementuak txikienetik handienera *ordenatu* daitezke `sort` metodoarekin.",
      "",
      "```python",
      "nire_zerrenda = [2,5,1,2,4]",
      "nire_zerrenda.sort()",
      "print(nire_zerrenda)",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Ohartu metodoak zerrenda bera aldatzen duela. Batzuetan ez dugu jatorrizko zerrenda aldatu nahi, beraz, `sorted` funtzioa erabiltzen dugu horren ordez. Honek zerrenda ordenatu bat *itzultzen* du:",
      "",
      "```python",
      "nire_zerrenda = [2,5,1,2,4]",
      "print(sorted(nire_zerrenda))",
      "```",
      "",
      "```text",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "Gogoratu bien arteko aldea: `sort`-ek jatorrizko zerrendaren ordena aldatzen du, eta `sorted`-ek zerrendaren kopia berri eta ordenatu bat sortzen du. `sorted`-ekin zerrendaren jatorrizko ordena gorde dezakegu:",
      "",
      "```python",
      "jatorrizkoa = [2, 5, 1, 2, 4]",
      "ordenatua = sorted(jatorrizkoa)",
      "print(jatorrizkoa)",
      "print(ordenatua)",
      "```",
      "",
      "```text",
      "[2, 5, 1, 2, 4]",
      "[1, 2, 2, 4, 5]",
      "```",
      "",
      "## Maximoa, minimoa eta batura",
      "",
      "`max` eta `min` funtzioek, maximo eta minimoaren laburdurak, zerrenda bateko elementu handiena eta txikiena itzultzen dute, hurrenez hurren. `sum` funtzioak zerrenda bateko elementu guztien batura itzultzen du.",
      "",
      "```python",
      "nire_zerrenda = [5, 2, 3, 1, 4]",
      "",
      "handiena = max(nire_zerrenda)",
      "txikiena = min(nire_zerrenda)",
      "zerrenda_batura = sum(nire_zerrenda)",
      "",
      "print(\"Txikiena:\", txikiena)",
      "print(\"Handiena:\", handiena)",
      "print(\"Batura:\", zerrenda_batura)",
      "```",
      "",
      "```text",
      "Txikiena: 1",
      "Handiena: 5",
      "Batura: 15",
      "```",
      "",
      "## Metodoak vs funtzioak",
      "",
      "Python-en zerrendak prozesatzeko bi modu desberdin daude, eta horrek nahasmena sor dezake. Gehienetan zerrenda *metodoak* erabiliko dituzu, adibidez `append` eta `sort`. Puntu `.` eragilearekin erabiltzen dira zerrenda aldagaian:",
      "",
      "```python",
      "nire_zerrenda = []",
      "",
      "# metodo deiak",
      "nire_zerrenda.append(3)",
      "nire_zerrenda.append(1)",
      "nire_zerrenda.append(7)",
      "nire_zerrenda.append(2)",
      "",
      "# beste metodo dei bat",
      "nire_zerrenda.sort()",
      "```",
      "",
      "*Funtzio* batzuek zerrenda bat argumentu gisa onartzen dute. Goian ikusi ditugu `max`, `min`, `len` eta `sorted` funtzioak horixe:",
      "",
      "```python",
      "nire_zerrenda = [3, 2, 7, 1]",
      "",
      "# funtzio deiek zerrenda argumentu gisa hartzen dute",
      "handiena = max(nire_zerrenda)",
      "txikiena = min(nire_zerrenda)",
      "luzera = len(nire_zerrenda)",
      "",
      "print(\"Txikiena:\", txikiena)",
      "print(\"Handiena:\", handiena)",
      "print(\"Zerrendaren luzera:\", luzera)",
      "",
      "# beste funtzio dei bat",
      "# zerrenda bera da argumentua, funtzioak kopia ordenatu bat itzultzen du",
      "ordenatua = sorted(nire_zerrenda)",
      "print(ordenatua)",
      "```",
      "",
      "```text",
      "Txikiena: 1",
      "Handiena: 7",
      "Zerrendaren luzera: 4",
      "[1, 2, 3, 7]",
      "```",
      "",
      "## Zerrenda bat argumentu edo itzulera-balio gisa",
      "",
      "Goiko funtzio integratuak bezala, gure funtzioek ere zerrenda bat har dezakete argumentu gisa eta zerrenda bat sor dezakete itzulera-balio gisa. Hurrengo funtzioak zerrenda ordenatu bateko erdiko balioa kalkulatzen du, *mediana* balioa ere deitua:",
      "",
      "```python",
      "def mediana(nire_zerrenda: list):",
      "    ordenatua = sorted(nire_zerrenda)",
      "    zerrenda_erdia = len(ordenatua) // 2",
      "    return ordenatua[zerrenda_erdia]",
      "```",
      "",
      "Funtzioak argumentu gisa emandako zerrendaren bertsio ordenatu bat sortzen du eta erdian dagoen elementua itzultzen du. Ohartu hemen erabilitako `//` zatiketa osoaren eragileaz. Zerrenda baten indizeak beti zenbaki osoa izan behar du.",
      "",
      "Funtzioak horrela funtzionatzen du:",
      "",
      "```python",
      "oinetako_neurriak = [45, 44, 36, 39, 40]",
      "print(\"Oinetako neurrien mediana da\", mediana(oinetako_neurriak))",
      "",
      "adinak = [1, 56, 34, 22, 5, 77, 5]",
      "print(\"Adinen mediana da\", mediana(adinak))",
      "```",
      "",
      "```text",
      "Oinetako neurrien mediana da 40",
      "Adinen mediana da 22",
      "```",
      "",
      "Funtzio batek zerrenda bat ere itzul dezake. Hurrengo funtzioak erabiltzaileari zenbaki osoak idazteko eskatzen dio eta sarrera zerrenda gisa itzultzen du:",
      "",
      "```python",
      "def zenbakiak_sartu():",
      "    zenbakiak = []",
      "    while True:",
      "        erabiltzaile_sarrera = input(\"Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: \")",
      "        if len(erabiltzaile_sarrera) == 0:",
      "            break",
      "        zenbakiak.append(int(erabiltzaile_sarrera))",
      "    return zenbakiak",
      "```",
      "",
      "Funtzioak `zenbakiak` aldagai laguntzailea erabiltzen du, zerrenda bat dena. Erabiltzaileak idatzitako zenbaki guztiak zerrendara gehitzen dira. Begiztatik irteten denean, funtzioak zerrenda itzultzen du `return zenbakiak` sententziarekin.",
      "",
      "Funtzioa horrela deituz",
      "",
      "```python",
      "zenbakiak = zenbakiak_sartu()",
      "",
      "print(\"Zenbaki handiena da\", max(zenbakiak))",
      "print(\"Zenbakien mediana da\", mediana(zenbakiak))",
      "```",
      "",
      "hau inprimatu lezake, adibidez:",
      "",
      "```text",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 5",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: -22",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 4",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 35",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: 1",
      "Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko:",
      "Zenbaki handiena da 35",
      "Zenbakien mediana da 4",
      "```",
      "",
      "Adibide txiki honek funtzioen erabilera garrantzitsuenetako bat erakusten du: zure kodea zati logiko txikiago eta ulerterrazagoetan banatzen lagun dezakete.",
      "",
      "Jakina, funtzionalitate bera lor liteke gure funtziorik idatzi gabe:",
      "",
      "```python",
      "zenbakiak = []",
      "while True:",
      "    erabiltzaile_sarrera = input(\"Mesedez idatzi zenbaki oso bat, utzi hutsik irteteko: \")",
      "    if len(erabiltzaile_sarrera) == 0:",
      "        break",
      "    zenbakiak.append(int(erabiltzaile_sarrera))",
      "",
      "ordenatua = sorted(zenbakiak)",
      "zerrenda_erdia = len(ordenatua) // 2",
      "mediana = ordenatua[zerrenda_erdia]",
      "",
      "print(\"Zenbaki handiena da\", max(zenbakiak))",
      "print(\"Zenbakien mediana da\", mediana)",
      "```",
      "",
      "Bertsio honetan, programazio-logika jarraitzea zailagoa da, jada ez baitago argi zein komando diren zein funtzionalitateren parte. Kodeak helburu berberak betetzen ditu - sarrera irakurtzea, mediana kalkulatzea, eta abar - baina egitura ez da hain argia.",
      "",
      "Zure kodea funtzio bereizietan antolatzeak zure programaren irakurgarritasuna hobetuko du, baina baita osotasun logikoak maneiatzea erraztuko ere. Honek, aldi berean, programak nahi bezala funtzionatzen duela egiaztatzen laguntzen dizu, funtzio bakoitza bere aldetik probatu baitaiteke.",
      "",
      "Funtzioen beste erabilera garrantzitsu bat kodea *berrerabilgarria* egitea da. Zure programan funtzionalitateren bat hainbat aldiz lortu behar baduzu, ideia ona da zure funtzioa sortzea eta egoki izendatzea:",
      "",
      "```python",
      "print(\"Oinetako neurriak:\")",
      "oinetako_neurriak = zenbakiak_sartu()",
      "",
      "print(\"Pisuak:\")",
      "pisuak = zenbakiak_sartu()",
      "",
      "print(\"Altuerak:\")",
      "altuerak = zenbakiak_sartu()",
      "```"
    ].join("\n")
  }
};

const section3 = {
  id: "part4-3",
  title: {
    ENG: "Lists",
    CAS: "Listas",
    EUS: "Zerrendak"
  },
  blocks: [
    learningObjectives,
    introContent,
    exerciseChangeValue,
    addingItemsContent,
    exerciseAddItems,
    removingItemsContent,
    exerciseAddRemove,
    restContent
  ]
};

const outputPath = path.join(__dirname, '../src/data/part4/section3.json');
fs.writeFileSync(outputPath, JSON.stringify(section3, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);