const fs = require('fs');
const path = require('path');

const learningObjectives = {
  type: "markdown",
  content: {
    ENG: [
      "# Learning objectives",
      "",
      "After this section",
      "",
      "- You will be able to write your own modules",
      "- You will know what the Python variable `__name__` and the value `__main__` signify"
    ].join("\n"),
    CAS: [
      "# Objetivos de aprendizaje",
      "",
      "Después de esta sección",
      "",
      "- Podrás escribir tus propios módulos",
      "- Sabrás qué significan la variable de Python `__name__` y el valor `__main__`"
    ].join("\n"),
    EUS: [
      "# Ikas-helburuak",
      "",
      "Atal honen ondoren",
      "",
      "- Zure modulu propioak idazteko gai izango zara",
      "- `__name__` Python aldagaia eta `__main__` balioak zer esan nahi duten jakingo duzu"
    ].join("\n")
  }
};

const creatingModulesContent = {
  type: "markdown",
  content: {
    ENG: [
      "Writing your own Python modules is easy. Any file containing valid Python code can be imported as a module. Let's assume we have a file named `words.py` with the following contents:",
      "",
      "```python",
      "def first_word(my_string: str):",
      "    parts = my_string.split(\" \")",
      "    return parts[0]",
      "",
      "def last_word(my_string: str):",
      "    parts = my_string.split(\" \")",
      "    return parts[-1]",
      "",
      "def number_of_words(my_string: str):",
      "    parts = my_string.split(\" \")",
      "    return len(parts)",
      "```",
      "",
      "The functions defined in the file can be accessed by importing the file:",
      "",
      "```python",
      "import words",
      "",
      "my_string = \"Sheila sells seashells by the seashore\"",
      "",
      "print(words.first_word(my_string))",
      "print(words.last_word(my_string))",
      "print(words.number_of_words(my_string))",
      "```",
      "",
      "```text",
      "Sheila",
      "seashore",
      "6",
      "```",
      "",
      "NB: the file containing the Python module must be located either in the same directory with the program importing it, or in one of the default Python directories, or else the Python interpreter will not find it when the `import` statement is executed.",
      "",
      "We can use our own modules just as we have learnt to use the modules from the Python standard library:",
      "",
      "```python",
      "from words import first_word, last_word",
      "",
      "sentence = input(\"Please type in a sentence: \")",
      "",
      "print(\"The first word was: \" + first_word(sentence))",
      "print(\"The last word was: \" + last_word(sentence))",
      "```",
      "",
      "```text",
      "Please type in a sentence: Python is a swell programming language",
      "The first word was: Python",
      "The last word was: language",
      "```"
    ].join("\n"),
    CAS: [
      "Escribir tus propios módulos de Python es fácil. Cualquier archivo que contenga código Python válido puede importarse como un módulo. Supongamos que tenemos un archivo llamado `palabras.py` con el siguiente contenido:",
      "",
      "```python",
      "def primera_palabra(mi_cadena: str):",
      "    partes = mi_cadena.split(\" \")",
      "    return partes[0]",
      "",
      "def ultima_palabra(mi_cadena: str):",
      "    partes = mi_cadena.split(\" \")",
      "    return partes[-1]",
      "",
      "def numero_de_palabras(mi_cadena: str):",
      "    partes = mi_cadena.split(\" \")",
      "    return len(partes)",
      "```",
      "",
      "Se puede acceder a las funciones definidas en el archivo importando el archivo:",
      "",
      "```python",
      "import palabras",
      "",
      "mi_cadena = \"Sheila vende conchas de mar a la orilla del mar\"",
      "",
      "print(palabras.primera_palabra(mi_cadena))",
      "print(palabras.ultima_palabra(mi_cadena))",
      "print(palabras.numero_de_palabras(mi_cadena))",
      "```",
      "",
      "```text",
      "Sheila",
      "mar",
      "10",
      "```",
      "",
      "Nota: el archivo que contiene el módulo de Python debe estar ubicado en el mismo directorio que el programa que lo importa, o en uno de los directorios predeterminados de Python, de lo contrario, el intérprete de Python no lo encontrará cuando se ejecute la declaración `import`.",
      "",
      "Podemos usar nuestros propios módulos tal como hemos aprendido a usar los módulos de la biblioteca estándar de Python:",
      "",
      "```python",
      "from palabras import primera_palabra, ultima_palabra",
      "",
      "oracion = input(\"Por favor escribe una oración: \")",
      "",
      "print(\"La primera palabra fue: \" + primera_palabra(oracion))",
      "print(\"La última palabra fue: \" + ultima_palabra(oracion))",
      "```",
      "",
      "```text",
      "Por favor escribe una oración: Python es un lenguaje de programación genial",
      "La primera palabra fue: Python",
      "La última palabra fue: genial",
      "```"
    ].join("\n"),
    EUS: [
      "Zure Python modulu propioak idaztea erraza da. Baliozko Python kodea duen edozein fitxategi modulu gisa inporta daiteke. Demagun `hitzak.py` izeneko fitxategi bat dugula honako edukiarekin:",
      "",
      "```python",
      "def lehen_hitza(nire_katea: str):",
      "    zatiak = nire_katea.split(\" \")",
      "    return zatiak[0]",
      "",
      "def azken_hitza(nire_katea: str):",
      "    zatiak = nire_katea.split(\" \")",
      "    return zatiak[-1]",
      "",
      "def hitz_kopurua(nire_katea: str):",
      "    zatiak = nire_katea.split(\" \")",
      "    return len(zatiak)",
      "```",
      "",
      "Fitxategian definitutako funtzioetara fitxategia inportatuz sar daiteke:",
      "",
      "```python",
      "import hitzak",
      "",
      "nire_katea = \"Sheila sells seashells by the seashore\"",
      "",
      "print(hitzak.lehen_hitza(nire_katea))",
      "print(hitzak.azken_hitza(nire_katea))",
      "print(hitzak.hitz_kopurua(nire_katea))",
      "```",
      "",
      "```text",
      "Sheila",
      "seashore",
      "6",
      "```",
      "",
      "OHARRA: Python modulua duen fitxategiak inportatzen duen programaren direktorio berean egon behar du, edo Python direktorio lehenetsietako batean, bestela Python interpreteak ez du aurkituko `import` sententzia exekutatzen denean.",
      "",
      "Gure modulu propioak erabil ditzakegu Python liburutegi estandarreko moduluak erabiltzen ikasi dugun modu berean:",
      "",
      "```python",
      "from hitzak import lehen_hitza, azken_hitza",
      "",
      "esaldia = input(\"Mesedez idatzi esaldi bat: \")",
      "",
      "print(\"Lehen hitza izan da: \" + lehen_hitza(esaldia))",
      "print(\"Azken hitza izan da: \" + azken_hitza(esaldia))",
      "```",
      "",
      "```text",
      "Mesedez idatzi esaldi bat: Python programazio hizkuntza bikaina da",
      "Lehen hitza izan da: Python",
      "Azken hitza izan da: da",
      "```"
    ].join("\n")
  }
};

const mainFunctionContent = {
  type: "markdown",
  content: {
    ENG: [
      "## Main function code in a module",
      "",
      "If a module contains any code which is not contained within a function definition (that is, if the module contains code in the main function of the module), this code is executed automatically whenever the module is imported.",
      "",
      "Luckily, there is a solution, and it is one which you have used many times before in the exercises on this course. We just need to test if the program is being executed on its own, or if the code has been imported with an `import` statement. Python has a built-in variable `__name__`, which contains the name of the program being executed. If the program is being executed on its own, the value of the variable is `\"__main__\"`. If the program has been imported, the value of the variable is the name of the imported module.",
      "",
      "Knowing this, we can add a conditional statement, which lets us only execute the text cases if the program is executed on its own. As you can see below, the structure looks familiar:",
      "",
      "```python",
      "if __name__ == \"__main__\":",
      "    # testing functionality",
      "    print(first_word(\"This is a test\"))",
      "    print(last_word(\"Here we are still testing\"))",
      "    print(number_of_words(\"One two three four five\"))",
      "```",
      "",
      "In the exercises on this course, whenever you were asked to write functions, you were usually also expected to wrap test cases in an `if __name__ == \"__main__\"` block exactly like the one above. Now you know why."
    ].join("\n"),
    CAS: [
      "## Código de función principal en un módulo",
      "",
      "Si un módulo contiene algún código que no está contenido dentro de una definición de función (es decir, si el módulo contiene código en la función principal del módulo), este código se ejecuta automáticamente cada vez que se importa el módulo.",
      "",
      "Afortunadamente, hay una solución, y es una que has usado muchas veces antes en los ejercicios de este curso. Solo necesitamos probar si el programa se está ejecutando por sí solo, o si el código se ha importado con una declaración `import`. Python tiene una variable incorporada `__name__`, que contiene el nombre del programa que se está ejecutando. Si el programa se está ejecutando por sí solo, el valor de la variable es `\"__main__\"`. Si el programa ha sido importado, el valor de la variable es el nombre del módulo importado.",
      "",
      "Sabiendo esto, podemos agregar una declaración condicional, que nos permite ejecutar los casos de prueba solo si el programa se ejecuta por sí solo. Como puedes ver a continuación, la estructura parece familiar:",
      "",
      "```python",
      "if __name__ == \"__main__\":",
      "    # funcionalidad de prueba",
      "    print(primera_palabra(\"Esto es una prueba\"))",
      "    print(ultima_palabra(\"Aquí seguimos probando\"))",
      "    print(numero_de_palabras(\"Uno dos tres cuatro cinco\"))",
      "```",
      "",
      "En los ejercicios de este curso, cada vez que se te pidió que escribieras funciones, generalmente también se esperaba que envolvieras los casos de prueba en un bloque `if __name__ == \"__main__\"` exactamente como el de arriba. Ahora sabes por qué."
    ].join("\n"),
    EUS: [
      "## Funtzio nagusiko kodea modulu batean",
      "",
      "Modulu batek funtzio definizio baten barruan ez dagoen koderik badu (hau da, moduluak moduluaren funtzio nagusian kodea badu), kode hau automatikoki exekutatzen da modulua inportatzen den bakoitzean.",
      "",
      "Zorionez, badago irtenbide bat, eta ikastaro honetako ariketetan askotan erabili duzun bat da. Programa berez exekutatzen ari den ala kodea `import` sententzia batekin inportatu den probatu besterik ez dugu behar. Python-ek `__name__` aldagai integratua du, exekutatzen ari den programaren izena duena. Programa berez exekutatzen ari bada, aldagaiaren balioa `\"__main__\"` da. Programa inportatu bada, aldagaiaren balioa inportatutako moduluaren izena da.",
      "",
      "Hau jakinda, baldintzazko sententzia bat gehi dezakegu, testu kasuak programa berez exekutatzen denean bakarrik exekutatzeko aukera ematen diguna. Behean ikus dezakezunez, egitura ezaguna dirudi:",
      "",
      "```python",
      "if __name__ == \"__main__\":",
      "    # proba funtzionalitatea",
      "    print(lehen_hitza(\"Hau proba bat da\"))",
      "    print(azken_hitza(\"Hemen oraindik probatzen ari gara\"))",
      "    print(hitz_kopurua(\"Bat bi hiru lau bost\"))",
      "```",
      "",
      "Ikastaro honetako ariketetan, funtzioak idazteko eskatu zitzaizun bakoitzean, normalean proba kasuak `if __name__ == \"__main__\"` bloke batean biltzea ere espero zen, goikoa bezalaxe. Orain badakizu zergatik."
    ].join("\n")
  }
};

const exerciseStringHelper = {
  type: "exercise",
  exerciseId: "part07-17_string_helper",
  title: {
    ENG: "String helper",
    CAS: "Ayudante de cadenas",
    EUS: "Kate laguntzailea"
  },
  description: {
    ENG: "Please write a module named `string_helper`, which contains the functions `change_case(orig_string: str)`, `split_in_half(orig_string: str)`, and `remove_special_characters(orig_string: str)`.",
    CAS: "Por favor escribe un módulo llamado `string_helper`, que contenga las funciones `change_case(orig_string: str)`, `split_in_half(orig_string: str)`, y `remove_special_characters(orig_string: str)`.",
    EUS: "Mesedez idatzi `string_helper` izeneko modulu bat, `change_case(orig_string: str)`, `split_in_half(orig_string: str)`, eta `remove_special_characters(orig_string: str)` funtzioak dituena."
  },
  initialCode: {
    ENG: [
      "def change_case(orig_string: str):",
      "    # Write your solution here",
      "    pass",
      "",
      "def split_in_half(orig_string: str):",
      "    # Write your solution here",
      "    pass",
      "",
      "def remove_special_characters(orig_string: str):",
      "    # Write your solution here",
      "    pass"
    ].join("\n"),
    CAS: [
      "def change_case(cadena_orig: str):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "def split_in_half(cadena_orig: str):",
      "    # Escribe tu solución aquí",
      "    pass",
      "",
      "def remove_special_characters(cadena_orig: str):",
      "    # Escribe tu solución aquí",
      "    pass"
    ].join("\n"),
    EUS: [
      "def change_case(jatorrizko_katea: str):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "def split_in_half(jatorrizko_katea: str):",
      "    # Idatzi zure soluzioa hemen",
      "    pass",
      "",
      "def remove_special_characters(jatorrizko_katea: str):",
      "    # Idatzi zure soluzioa hemen",
      "    pass"
    ].join("\n")
  },
  testCode: ""
};

const section5 = {
  id: "part7-5",
  title: {
    ENG: "Creating your own modules",
    CAS: "Creando tus propios módulos",
    EUS: "Zure modulu propioak sortzen"
  },
  blocks: [
    learningObjectives,
    creatingModulesContent,
    mainFunctionContent,
    exerciseStringHelper
  ]
};

const outputPath = path.join(__dirname, '../src/data/part7/section5.json');
fs.writeFileSync(outputPath, JSON.stringify(section5, null, 2), 'utf-8');
console.log(`Successfully created ${outputPath}`);
